// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBAccessFlags
import kotlinx.cinterop.ExperimentalForeignApi
import platform.Foundation.NSNumber

@OptIn(ExperimentalForeignApi::class)
fun AccessFlags.toObjc(): DBAccessFlags {
    return when(this) {
        AccessFlags.NOBODY -> TestSuite.DBAccessFlagsNobody
        AccessFlags.OWNER_READ -> TestSuite.DBAccessFlagsOwnerRead
        AccessFlags.OWNER_WRITE -> TestSuite.DBAccessFlagsOwnerWrite
        AccessFlags.OWNER_EXECUTE -> TestSuite.DBAccessFlagsOwnerExecute
        AccessFlags.GROUP_READ -> TestSuite.DBAccessFlagsGroupRead
        AccessFlags.GROUP_WRITE -> TestSuite.DBAccessFlagsGroupWrite
        AccessFlags.GROUP_EXECUTE -> TestSuite.DBAccessFlagsGroupExecute
        AccessFlags.SYSTEM_READ -> TestSuite.DBAccessFlagsSystemRead
        AccessFlags.SYSTEM_WRITE -> TestSuite.DBAccessFlagsSystemWrite
        AccessFlags.SYSTEM_EXECUTE -> TestSuite.DBAccessFlagsSystemExecute
        AccessFlags.EVERYBODY -> TestSuite.DBAccessFlagsEverybody
    }
}

@OptIn(ExperimentalForeignApi::class)
fun AccessFlags.toNSNumber(): NSNumber {
    return NSNumber(long = toObjc())
}

@OptIn(ExperimentalForeignApi::class)
fun AccessFlags.Companion.fromObjc(e: DBAccessFlags): AccessFlags {
    return when(e) {
        TestSuite.DBAccessFlagsNobody -> AccessFlags.NOBODY
        TestSuite.DBAccessFlagsOwnerRead -> AccessFlags.OWNER_READ
        TestSuite.DBAccessFlagsOwnerWrite -> AccessFlags.OWNER_WRITE
        TestSuite.DBAccessFlagsOwnerExecute -> AccessFlags.OWNER_EXECUTE
        TestSuite.DBAccessFlagsGroupRead -> AccessFlags.GROUP_READ
        TestSuite.DBAccessFlagsGroupWrite -> AccessFlags.GROUP_WRITE
        TestSuite.DBAccessFlagsGroupExecute -> AccessFlags.GROUP_EXECUTE
        TestSuite.DBAccessFlagsSystemRead -> AccessFlags.SYSTEM_READ
        TestSuite.DBAccessFlagsSystemWrite -> AccessFlags.SYSTEM_WRITE
        TestSuite.DBAccessFlagsSystemExecute -> AccessFlags.SYSTEM_EXECUTE
        TestSuite.DBAccessFlagsEverybody -> AccessFlags.EVERYBODY
         else -> throw IllegalArgumentException("Unknown AccessFlags: $e")
    }
}

@OptIn(ExperimentalForeignApi::class)
fun AccessFlags.Companion.fromNSNumber(e: NSNumber): AccessFlags {
    return fromObjc(e.integerValue)
}
