// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primtypes.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBAssortedPrimitives
import kotlinx.cinterop.ExperimentalForeignApi
import platform.Foundation.NSNumber

@OptIn(ExperimentalForeignApi::class)
fun AssortedPrimitives.toObjc(): DBAssortedPrimitives {
    return DBAssortedPrimitives(
        this.b,
        this.eight,
        this.sixteen,
        this.thirtytwo,
        this.sixtyfour,
        this.fthirtytwo,
        this.fsixtyfour,
        this.oB?.let { NSNumber(bool = it) },
        this.oEight?.let { NSNumber(char = it) },
        this.oSixteen?.let { NSNumber(short = it) },
        this.oThirtytwo?.let { NSNumber(int = it) },
        this.oSixtyfour?.let { NSNumber(long = it) },
        this.oFthirtytwo?.let { NSNumber(float = it) },
        this.oFsixtyfour?.let { NSNumber(double = it) }
    )
}

@OptIn(ExperimentalForeignApi::class)
fun DBAssortedPrimitives.toKotlin(): AssortedPrimitives {
    return AssortedPrimitives(
        b = this.b,
        eight = this.eight,
        sixteen = this.sixteen,
        thirtytwo = this.thirtytwo,
        sixtyfour = this.sixtyfour,
        fthirtytwo = this.fthirtytwo,
        fsixtyfour = this.fsixtyfour,
        oB = this.oB?.boolValue(),
        oEight = this.oEight?.charValue(),
        oSixteen = this.oSixteen?.shortValue(),
        oThirtytwo = this.oThirtytwo?.intValue(),
        oSixtyfour = this.oSixtyfour?.longValue(),
        oFthirtytwo = this.oFthirtytwo?.floatValue(),
        oFsixtyfour = this.oFsixtyfour?.doubleValue()
    )
}
