// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBAsyncInterfaceProtocol
import TestSuite.DJFuture
import kotlinx.cinterop.ExperimentalForeignApi
import platform.darwin.NSObject

@OptIn(ExperimentalForeignApi::class)
class DBAsyncInterfaceImpl(private val asyncInterface: AsyncInterface): NSObject(), DBAsyncInterfaceProtocol {
    override fun futureRoundtrip(f: DJFuture): DJFuture {
        val ret = asyncInterface.futureRoundtrip(TODO("Map external type: com.safetyculture.djinni.support.Future"))

        return TODO("Map external type: com.safetyculture.djinni.support.Future")
    }
}
