// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBClientInterfaceProtocol
import TestSuite.DBClientReturnedRecord
import kotlinx.cinterop.ExperimentalForeignApi
import platform.darwin.NSObject

@OptIn(ExperimentalForeignApi::class)
class DBClientInterfaceImpl(private val clientInterface: ClientInterface): NSObject(), DBClientInterfaceProtocol {
    override fun getRecord(
        recordID: Long,
        utf8string: String,
        misc: String?
    ): DBClientReturnedRecord {
        val ret = clientInterface.getRecord(
            recordID,
            utf8string,
            misc
        )

        return ret.toObjc()
    }

    override fun identifierCheck(
        data: Buffer,
        r: Int,
        jret: Long
    ): Double {
        val ret = clientInterface.identifierCheck(
            TODO("Map: MBinary"),
            r,
            jret
        )

        return ret
    }

    override fun returnStr(): String {
        val ret = clientInterface.returnStr()

        return ret
    }

    override fun methTakingInterface(i: DBClientInterfaceProtocol): String {
        val ret = clientInterface.methTakingInterface(throw UnsupportedOperationException("Impossible to map id<DBClientInterface> in this direction"))

        return ret
    }

    override fun methTakingOptionalInterface(i: DBClientInterfaceProtocol?): String {
        val ret = clientInterface.methTakingOptionalInterface(throw UnsupportedOperationException("Impossible to map id<DBClientInterface> in this direction"))

        return ret
    }
}
