// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBClientReturnedRecord
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun ClientReturnedRecord.toObjc(): DBClientReturnedRecord {
    return DBClientReturnedRecord(
        this.recordId,
        this.content,
        this.misc
    )
}

@OptIn(ExperimentalForeignApi::class)
fun DBClientReturnedRecord.toKotlin(): ClientReturnedRecord {
    return ClientReturnedRecord(
        recordId = this.recordID,
        content = this.content,
        misc = this.misc
    )
}
