// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBColor
import kotlinx.cinterop.ExperimentalForeignApi
import platform.Foundation.NSNumber

@OptIn(ExperimentalForeignApi::class)
fun Color.toObjc(): DBColor {
    return when(this) {
        Color.RED -> TestSuite.DBColorRed
        Color.ORANGE -> TestSuite.DBColorOrange
        Color.YELLOW -> TestSuite.DBColorYellow
        Color.GREEN -> TestSuite.DBColorGreen
        Color.BLUE -> TestSuite.DBColorBlue
        Color.INDIGO -> TestSuite.DBColorIndigo
        Color.VIOLET -> TestSuite.DBColorViolet
    }
}

@OptIn(ExperimentalForeignApi::class)
fun Color.toNSNumber(): NSNumber {
    return NSNumber(long = toObjc())
}

@OptIn(ExperimentalForeignApi::class)
fun Color.Companion.fromObjc(e: DBColor): Color {
    return when(e) {
        TestSuite.DBColorRed -> Color.RED
        TestSuite.DBColorOrange -> Color.ORANGE
        TestSuite.DBColorYellow -> Color.YELLOW
        TestSuite.DBColorGreen -> Color.GREEN
        TestSuite.DBColorBlue -> Color.BLUE
        TestSuite.DBColorIndigo -> Color.INDIGO
        TestSuite.DBColorViolet -> Color.VIOLET
         else -> throw IllegalArgumentException("Unknown Color: $e")
    }
}

@OptIn(ExperimentalForeignApi::class)
fun Color.Companion.fromNSNumber(e: NSNumber): Color {
    return fromObjc(e.integerValue)
}
