// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBConflictUser
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
class ConflictUserImpl(private val conflictUser: DBConflictUser): ConflictUser {
    override fun Conflict(): Conflict? {
        val ret = conflictUser.Conflict()
        return ret?.let { ConflictImpl(it) }
    }

    override fun conflictArg(cs: Set<Conflict>): Boolean {
        val ret = conflictUser.conflictArg(cs.map { TODO("Impossible to map Conflict in this direction") }.toSet())
        return ret
    }
}
