// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBConstantRecord
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun ConstantRecord.toObjc(): DBConstantRecord {
    return DBConstantRecord(
        this.someInteger,
        this.someString
    )
}

@OptIn(ExperimentalForeignApi::class)
fun DBConstantRecord.toKotlin(): ConstantRecord {
    return ConstantRecord(
        someInteger = this.someInteger,
        someString = this.someString
    )
}
