// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBConstantEnum
import kotlinx.cinterop.ExperimentalForeignApi
import platform.Foundation.NSNumber

@OptIn(ExperimentalForeignApi::class)
fun ConstantEnum.toObjc(): DBConstantEnum {
    return when(this) {
        ConstantEnum.SOME_VALUE -> TestSuite.DBConstantEnumSomeValue
        ConstantEnum.SOME_OTHER_VALUE -> TestSuite.DBConstantEnumSomeOtherValue
    }
}

@OptIn(ExperimentalForeignApi::class)
fun ConstantEnum.toNSNumber(): NSNumber {
    return NSNumber(long = toObjc())
}

@OptIn(ExperimentalForeignApi::class)
fun ConstantEnum.Companion.fromObjc(e: DBConstantEnum): ConstantEnum {
    return when(e) {
        TestSuite.DBConstantEnumSomeValue -> ConstantEnum.SOME_VALUE
        TestSuite.DBConstantEnumSomeOtherValue -> ConstantEnum.SOME_OTHER_VALUE
         else -> throw IllegalArgumentException("Unknown ConstantEnum: $e")
    }
}

@OptIn(ExperimentalForeignApi::class)
fun ConstantEnum.Companion.fromNSNumber(e: NSNumber): ConstantEnum {
    return fromObjc(e.integerValue)
}
