// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBConstantsInterface
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
class ConstantsInterfaceImpl(private val constantsInterface: DBConstantsInterface): ConstantsInterface {
    override fun dummy() {
        constantsInterface.dummy()
    }
}
