// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBConstants
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun Constants.toObjc(): DBConstants {
    return DBConstants()
}

@OptIn(ExperimentalForeignApi::class)
fun DBConstants.toKotlin(): Constants {
    return Constants()
}
