// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBConstantInterfaceWithEnum
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
class ConstantInterfaceWithEnumImpl(private val constantInterfaceWithEnum: DBConstantInterfaceWithEnum): ConstantInterfaceWithEnum {
}
