// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBConstantWithEnum
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun ConstantWithEnum.toObjc(): DBConstantWithEnum {
    return DBConstantWithEnum()
}

@OptIn(ExperimentalForeignApi::class)
fun DBConstantWithEnum.toKotlin(): ConstantWithEnum {
    return ConstantWithEnum()
}
