// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from exception.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBCppException
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
internal actual fun getCppException(): CppException? {
    val ret = DBCppException.get()
    return ret?.let { CppExceptionImpl(it) }
}

@OptIn(ExperimentalForeignApi::class)
class CppExceptionImpl(private val cppException: DBCppException): CppException {
    override fun throwAnException(): Int {
        val ret = cppException.throwAnException()
        return ret
    }

    override fun callThrowingInterface(cb: ThrowingInterface): Int {
        val ret = cppException.callThrowingInterface(TODO("Impossible to map ThrowingInterface in this direction"))
        return ret
    }

    override fun callThrowingAndCatch(cb: ThrowingInterface): String {
        val ret = cppException.callThrowingAndCatch(TODO("Impossible to map ThrowingInterface in this direction"))
        return ret
    }
}
