// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBDateRecord
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun DateRecord.toObjc(): DBDateRecord {
    return DBDateRecord(TODO("Map external type: [unspecified]"))
}

@OptIn(ExperimentalForeignApi::class)
fun DBDateRecord.toKotlin(): DateRecord {
    return DateRecord(createdAt = TODO("Map external type: [unspecified]"))
}
