// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBEmptyRecord
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun EmptyRecord.toObjc(): DBEmptyRecord {
    return DBEmptyRecord()
}

@OptIn(ExperimentalForeignApi::class)
fun DBEmptyRecord.toKotlin(): EmptyRecord {
    return EmptyRecord()
}
