// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBEmptyFlags
import kotlinx.cinterop.ExperimentalForeignApi
import platform.Foundation.NSNumber

@OptIn(ExperimentalForeignApi::class)
fun EmptyFlags.toObjc(): DBEmptyFlags {
    return when(this) {
        EmptyFlags.NONE -> TestSuite.DBEmptyFlagsNone
        EmptyFlags.ALL -> TestSuite.DBEmptyFlagsAll
    }
}

@OptIn(ExperimentalForeignApi::class)
fun EmptyFlags.toNSNumber(): NSNumber {
    return NSNumber(long = toObjc())
}

@OptIn(ExperimentalForeignApi::class)
fun EmptyFlags.Companion.fromObjc(e: DBEmptyFlags): EmptyFlags {
    return when(e) {
        TestSuite.DBEmptyFlagsNone -> EmptyFlags.NONE
        TestSuite.DBEmptyFlagsAll -> EmptyFlags.ALL
         else -> throw IllegalArgumentException("Unknown EmptyFlags: $e")
    }
}

@OptIn(ExperimentalForeignApi::class)
fun EmptyFlags.Companion.fromNSNumber(e: NSNumber): EmptyFlags {
    return fromObjc(e.integerValue)
}
