// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBColor
import TestSuite.DBEnumUsageInterfaceProtocol
import kotlinx.cinterop.ExperimentalForeignApi
import platform.darwin.NSObject

@OptIn(ExperimentalForeignApi::class)
class DBEnumUsageInterfaceImpl(private val enumUsageInterface: EnumUsageInterface): NSObject(), DBEnumUsageInterfaceProtocol {
    override fun e(e: DBColor): DBColor {
        val ret = enumUsageInterface.e(Color.fromObjc(e))

        return ret.toObjc()
    }

    override fun o(o: DBColor?): DBColor? {
        val ret = enumUsageInterface.o(o?.let { Color.fromNSNumber(it) })

        return ret?.toNSNumber()
    }

    override fun l(l: List<*>): List<*> {
        val ret = enumUsageInterface.l(l.map { Color.fromObjc((it as Long)) })

        return ArrayList(ret.map { it.toObjc() })
    }

    override fun s(s: Set<Color>): Set<Color> {
        val ret = enumUsageInterface.s(s.map { Color.fromObjc((it as Long)) }.toSet())

        return ret.map { it.toObjc() }.toSet()
    }

    override fun m(m: Map<Any?, *>): Map<Any?, *> {
        val ret = enumUsageInterface.m(m.map { Color.fromObjc((it.key as Long)) to Color.fromObjc((it.value as Long)) }.toMap())

        return ret.map { it.key.toObjc() to it.value.toObjc() }.toMap()
    }
}
