// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBEnumUsageRecord
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun EnumUsageRecord.toObjc(): DBEnumUsageRecord {
    return DBEnumUsageRecord(
        this.e.toObjc(),
        this.o?.toNSNumber(),
        ArrayList(this.l.map { it.toObjc() }),
        this.s.map { it.toObjc() }.toSet(),
        this.m.map { it.key.toObjc() to it.value.toObjc() }.toMap()
    )
}

@OptIn(ExperimentalForeignApi::class)
fun DBEnumUsageRecord.toKotlin(): EnumUsageRecord {
    return EnumUsageRecord(
        e = Color.fromObjc(this.e),
        o = this.o?.let { Color.fromNSNumber(it) },
        l = this.l.map { Color.fromObjc((it as Long)) },
        s = this.s.map { Color.fromObjc((it as Long)) }.toSet(),
        m = this.m.map { Color.fromObjc((it.key as Long)) to Color.fromObjc((it.value as Long)) }.toMap()
    )
}
