// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBExternRecordWithDerivings
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun ExternRecordWithDerivings.toObjc(): DBExternRecordWithDerivings {
    return DBExternRecordWithDerivings(
        TODO("Map external type: [unspecified]"),
        TODO("Map external type: [unspecified]")
    )
}

@OptIn(ExperimentalForeignApi::class)
fun DBExternRecordWithDerivings.toKotlin(): ExternRecordWithDerivings {
    return ExternRecordWithDerivings(
        member = TODO("Map external type: [unspecified]"),
        e = TODO("Map external type: [unspecified]")
    )
}
