// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBExternInterface2Protocol
import TestSuite.DBExternRecordWithDerivings
import TestSuite.DBTestHelpers
import kotlinx.cinterop.ExperimentalForeignApi
import platform.darwin.NSObject

@OptIn(ExperimentalForeignApi::class)
class DBExternInterface2Impl(private val externInterface2: ExternInterface2): NSObject(), DBExternInterface2Protocol {
    override fun foo(i: DBTestHelpers): DBExternRecordWithDerivings {
        val ret = externInterface2.foo(TODO("Map external type: [unspecified]"))

        return ret.toObjc()
    }
}
