// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBExtendedRecord
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun ExtendedRecord.toObjc(): DBExtendedRecord {
    return DBExtendedRecord(this.foo)
}

@OptIn(ExperimentalForeignApi::class)
fun DBExtendedRecord.toKotlin(): ExtendedRecord {
    return ExtendedRecord(foo = this.foo)
}
