// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBFirstListenerProtocol
import kotlinx.cinterop.ExperimentalForeignApi
import platform.darwin.NSObject

@OptIn(ExperimentalForeignApi::class)
class DBFirstListenerImpl(private val firstListener: FirstListener): NSObject(), DBFirstListenerProtocol {
    override fun first(): Unit {
        firstListener.first()
    }
}
