// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBFlagRoundtrip
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
internal actual fun roundtripAccessFlagRoundtrip(flag: AccessFlags): AccessFlags {
    val ret = DBFlagRoundtrip.roundtripAccess(flag.toObjc())
    return AccessFlags.fromObjc(ret)
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun roundtripEmptyFlagRoundtrip(flag: EmptyFlags): EmptyFlags {
    val ret = DBFlagRoundtrip.roundtripEmpty(flag.toObjc())
    return EmptyFlags.fromObjc(ret)
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun roundtripAccessBoxedFlagRoundtrip(flag: AccessFlags?): AccessFlags? {
    val ret = DBFlagRoundtrip.roundtripAccessBoxed(flag?.toNSNumber())
    return ret?.let { AccessFlags.fromNSNumber(it) }
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun roundtripEmptyBoxedFlagRoundtrip(flag: EmptyFlags?): EmptyFlags? {
    val ret = DBFlagRoundtrip.roundtripEmptyBoxed(flag?.toNSNumber())
    return ret?.let { EmptyFlags.fromNSNumber(it) }
}

@OptIn(ExperimentalForeignApi::class)
class FlagRoundtripImpl(private val flagRoundtrip: DBFlagRoundtrip): FlagRoundtrip {
}
