// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from function_prologue.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBFunctionPrologueHelper
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
internal actual fun fooFunctionPrologueHelper(): String {
    val ret = DBFunctionPrologueHelper.foo()
    return ret
}

@OptIn(ExperimentalForeignApi::class)
class FunctionPrologueHelperImpl(private val FunctionPrologueHelper: DBFunctionPrologueHelper): FunctionPrologueHelper {
}
