// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBInterfaceUsingExtendedRecord
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
class InterfaceUsingExtendedRecordImpl(private val interfaceUsingExtendedRecord: DBInterfaceUsingExtendedRecord): InterfaceUsingExtendedRecord {
    override fun meth(er: ExtendedRecord): ExtendedRecord {
        val ret = interfaceUsingExtendedRecord.meth(er.toObjc())
        return ret.toKotlin()
    }
}
