// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBListenerCaller
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
internal actual fun initListenerCaller(
    firstL: FirstListener,
    secondL: SecondListener
): ListenerCaller? {
    val ret = DBListenerCaller.init(
        DBFirstListenerImpl(firstL),
        DBSecondListenerImpl(secondL)
    )
    return ret?.let { ListenerCallerImpl(it) }
}

@OptIn(ExperimentalForeignApi::class)
class ListenerCallerImpl(private val listenerCaller: DBListenerCaller): ListenerCaller {
    override fun callFirst() {
        listenerCaller.callFirst()
    }

    override fun callSecond() {
        listenerCaller.callSecond()
    }
}
