// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBMapDateRecord
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun MapDateRecord.toObjc(): DBMapDateRecord {
    return DBMapDateRecord(this.datesById.map { it.key to TODO("Map external type: [unspecified]") }.toMap())
}

@OptIn(ExperimentalForeignApi::class)
fun DBMapDateRecord.toKotlin(): MapDateRecord {
    return MapDateRecord(datesById = this.datesByID.map { it.key as String to TODO("Map external type: [unspecified]") }.toMap())
}
