// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBMapListRecord
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun MapListRecord.toObjc(): DBMapListRecord {
    return DBMapListRecord(ArrayList(this.mapList.map { it.map { it.key to it.value }.toMap() }))
}

@OptIn(ExperimentalForeignApi::class)
fun DBMapListRecord.toKotlin(): MapListRecord {
    return MapListRecord(mapList = this.mapList.map { it as Map<String, Long>.map { it.key as String to it.value as Long }.toMap() })
}
