// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBMapRecord
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun MapRecord.toObjc(): DBMapRecord {
    return DBMapRecord(
        this.map.map { it.key to it.value }.toMap(),
        this.imap.map { it.key to it.value }.toMap()
    )
}

@OptIn(ExperimentalForeignApi::class)
fun DBMapRecord.toKotlin(): MapRecord {
    return MapRecord(
        map = this.map.map { it.key as String to it.value as Long }.toMap(),
        imap = this.imap.map { it.key as Int to it.value as Int }.toMap()
    )
}
