// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from outcome.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBNestedOutcome
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun NestedOutcome.toObjc(): DBNestedOutcome {
    return DBNestedOutcome(TODO("Map external type: com.safetyculture.djinni.support.Outcome"))
}

@OptIn(ExperimentalForeignApi::class)
fun DBNestedOutcome.toKotlin(): NestedOutcome {
    return NestedOutcome(o = TODO("Map external type: com.safetyculture.djinni.support.Outcome"))
}
