// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nested_collection.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBNestedCollection
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun NestedCollection.toObjc(): DBNestedCollection {
    return DBNestedCollection(ArrayList(this.setList.map { it.map { it }.toSet() }))
}

@OptIn(ExperimentalForeignApi::class)
fun DBNestedCollection.toKotlin(): NestedCollection {
    return NestedCollection(setList = this.setList.map { (it as Set<*>).map { it as String }.toSet() })
}
