// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from single_language_interfaces.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBObjcOnlyListenerProtocol
import kotlinx.cinterop.ExperimentalForeignApi
import platform.darwin.NSObject

@OptIn(ExperimentalForeignApi::class)
class DBObjcOnlyListenerImpl(private val objcOnlyListener: ObjcOnlyListener): NSObject(), DBObjcOnlyListenerProtocol {
}
