// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primitive_list.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBPrimitiveList
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun PrimitiveList.toObjc(): DBPrimitiveList {
    return DBPrimitiveList(ArrayList(this.list.map { it }))
}

@OptIn(ExperimentalForeignApi::class)
fun DBPrimitiveList.toKotlin(): PrimitiveList {
    return PrimitiveList(list = this.list.map { it as Long })
}
