// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBProtoTests
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
internal actual fun protoToStringsProtoTests(x: TODO("Map: MProtobuf")): List<String> {
    val ret = DBProtoTests.protoToStrings(TODO("Map: MProtobuf"))
    return ret.map { it as String }
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun stringsToProtoProtoTests(x: List<String>): TODO("Map: MProtobuf") {
    val ret = DBProtoTests.stringsToProto(ArrayList(x.map { it }))
    return TODO("Map: MProtobuf")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun embeddedProtoToStringProtoTests(x: RecordWithEmbeddedProto): String {
    val ret = DBProtoTests.embeddedProtoToString(x.toObjc())
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun stringToEmbeddedProtoProtoTests(x: String): RecordWithEmbeddedProto {
    val ret = DBProtoTests.stringToEmbeddedProto(x)
    return ret.toKotlin()
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun cppProtoToStringProtoTests(x: TODO("Map: MProtobuf")): String {
    val ret = DBProtoTests.cppProtoToString(TODO("Map: MProtobuf"))
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun stringToCppProtoProtoTests(x: String): TODO("Map: MProtobuf") {
    val ret = DBProtoTests.stringToCppProto(x)
    return TODO("Map: MProtobuf")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun embeddedCppProtoToStringProtoTests(x: RecordWithEmbeddedCppProto): String {
    val ret = DBProtoTests.embeddedCppProtoToString(x.toObjc())
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun stringToEmbeddedCppProtoProtoTests(x: String): RecordWithEmbeddedCppProto {
    val ret = DBProtoTests.stringToEmbeddedCppProto(x)
    return ret.toKotlin()
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun protoListToStringsProtoTests(x: List<TODO("Map: MProtobuf")>): List<String> {
    val ret = DBProtoTests.protoListToStrings(ArrayList(x.map { TODO("Map: MProtobuf") }))
    return ret.map { it as String }
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun stringsToProtoListProtoTests(x: List<String>): List<TODO("Map: MProtobuf")> {
    val ret = DBProtoTests.stringsToProtoList(ArrayList(x.map { it }))
    return ret.map { TODO("Map: MProtobuf") }
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun optionalProtoToStringProtoTests(x: TODO("Map: MProtobuf")?): String {
    val ret = DBProtoTests.optionalProtoToString(TODO("Map: MProtobuf"))
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun stringToOptionalProtoProtoTests(x: String): TODO("Map: MProtobuf")? {
    val ret = DBProtoTests.stringToOptionalProto(x)
    return TODO("Map: MProtobuf")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun stringToProtoOutcomeProtoTests(x: String): com.safetyculture.djinni.support.Outcome {
    val ret = DBProtoTests.stringToProtoOutcome(x)
    return TODO("Map external type: com.safetyculture.djinni.support.Outcome")
}

@OptIn(ExperimentalForeignApi::class)
class ProtoTestsImpl(private val protoTests: DBProtoTests): ProtoTests {
}
