// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBRecordWithEmbeddedProto
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun RecordWithEmbeddedProto.toObjc(): DBRecordWithEmbeddedProto {
    return DBRecordWithEmbeddedProto(TODO("Map: MProtobuf"))
}

@OptIn(ExperimentalForeignApi::class)
fun DBRecordWithEmbeddedProto.toKotlin(): RecordWithEmbeddedProto {
    return RecordWithEmbeddedProto(person = TODO("Map: MProtobuf"))
}
