// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBRecordWithFlags
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun RecordWithFlags.toObjc(): DBRecordWithFlags {
    return DBRecordWithFlags(this.access.toObjc())
}

@OptIn(ExperimentalForeignApi::class)
fun DBRecordWithFlags.toKotlin(): RecordWithFlags {
    return RecordWithFlags(access = AccessFlags.fromObjc(this.access))
}
