// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBRecordWithNestedDerivings
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun RecordWithNestedDerivings.toObjc(): DBRecordWithNestedDerivings {
    return DBRecordWithNestedDerivings(
        this.key,
        this.rec.toObjc()
    )
}

@OptIn(ExperimentalForeignApi::class)
fun DBRecordWithNestedDerivings.toKotlin(): RecordWithNestedDerivings {
    return RecordWithNestedDerivings(
        key = this.key,
        rec = this.rec.toKotlin()
    )
}
