// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBRecordWithDerivings
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.datetime.toKotlinInstant
import kotlinx.datetime.toNSDate

@OptIn(ExperimentalForeignApi::class)
fun RecordWithDerivings.toObjc(): DBRecordWithDerivings {
    return DBRecordWithDerivings(
        this.eight,
        this.sixteen,
        this.thirtytwo,
        this.sixtyfour,
        this.fthirtytwo,
        this.fsixtyfour,
        this.d.toNSDate(),
        this.s
    )
}

@OptIn(ExperimentalForeignApi::class)
fun DBRecordWithDerivings.toKotlin(): RecordWithDerivings {
    return RecordWithDerivings(
        eight = this.eight,
        sixteen = this.sixteen,
        thirtytwo = this.thirtytwo,
        sixtyfour = this.sixtyfour,
        fthirtytwo = this.fthirtytwo,
        fsixtyfour = this.fsixtyfour,
        d = this.d.toKotlinInstant(),
        s = this.s
    )
}
