// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBRecordWithDurationAndDerivings
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun RecordWithDurationAndDerivings.toObjc(): DBRecordWithDurationAndDerivings {
    return DBRecordWithDurationAndDerivings(TODO("Map external type: [unspecified]"))
}

@OptIn(ExperimentalForeignApi::class)
fun DBRecordWithDurationAndDerivings.toKotlin(): RecordWithDurationAndDerivings {
    return RecordWithDurationAndDerivings(dt = TODO("Map external type: [unspecified]"))
}
