// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBRecordUsingExtendedRecord
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun RecordUsingExtendedRecord.toObjc(): DBRecordUsingExtendedRecord {
    return DBRecordUsingExtendedRecord(this.er.toObjc())
}

@OptIn(ExperimentalForeignApi::class)
fun DBRecordUsingExtendedRecord.toKotlin(): RecordUsingExtendedRecord {
    return RecordUsingExtendedRecord(er = this.er.toKotlin())
}
