// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBRecordWithEmbeddedCppProto
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun RecordWithEmbeddedCppProto.toObjc(): DBRecordWithEmbeddedCppProto {
    return DBRecordWithEmbeddedCppProto(TODO("Map: MProtobuf"))
}

@OptIn(ExperimentalForeignApi::class)
fun DBRecordWithEmbeddedCppProto.toKotlin(): RecordWithEmbeddedCppProto {
    return RecordWithEmbeddedCppProto(state = TODO("Map: MProtobuf"))
}
