// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBReturnOne
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
internal actual fun getInstanceReturnOne(): ReturnOne? {
    val ret = DBReturnOne.getInstance()
    return ret?.let { ReturnOneImpl(it) }
}

@OptIn(ExperimentalForeignApi::class)
class ReturnOneImpl(private val returnOne: DBReturnOne): ReturnOne {
    override fun returnOne(): Byte {
        val ret = returnOne.returnOne()
        return ret
    }
}
