// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBReturnTwo
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
internal actual fun getInstanceReturnTwo(): ReturnTwo? {
    val ret = DBReturnTwo.getInstance()
    return ret?.let { ReturnTwoImpl(it) }
}

@OptIn(ExperimentalForeignApi::class)
class ReturnTwoImpl(private val returnTwo: DBReturnTwo): ReturnTwo {
    override fun returnTwo(): Byte {
        val ret = returnTwo.returnTwo()
        return ret
    }
}
