// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBReverseClientInterface
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
internal actual fun createReverseClientInterface(): ReverseClientInterface? {
    val ret = DBReverseClientInterface.create()
    return ret?.let { ReverseClientInterfaceImpl(it) }
}

@OptIn(ExperimentalForeignApi::class)
class ReverseClientInterfaceImpl(private val reverseClientInterface: DBReverseClientInterface): ReverseClientInterface {
    override fun returnStr(): String {
        val ret = reverseClientInterface.returnStr()
        return ret
    }

    override fun methTakingInterface(i: ReverseClientInterface): String {
        val ret = reverseClientInterface.methTakingInterface(TODO("Impossible to map ReverseClientInterface in this direction"))
        return ret
    }

    override fun methTakingOptionalInterface(i: ReverseClientInterface?): String {
        val ret = reverseClientInterface.methTakingOptionalInterface(throw UnsupportedOperationException("Impossible to map ReverseClientInterface in this direction"))
        return ret
    }
}
