// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBSampleInterface
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
class SampleInterfaceImpl(private val sampleInterface: DBSampleInterface): SampleInterface {
}
