// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBSecondListenerProtocol
import kotlinx.cinterop.ExperimentalForeignApi
import platform.darwin.NSObject

@OptIn(ExperimentalForeignApi::class)
class DBSecondListenerImpl(private val secondListener: SecondListener): NSObject(), DBSecondListenerProtocol {
    override fun second(): Unit {
        secondListener.second()
    }
}
