// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from set.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBSetRecord
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun SetRecord.toObjc(): DBSetRecord {
    return DBSetRecord(
        this.set.map { it }.toSet(),
        this.iset.map { it }.toSet()
    )
}

@OptIn(ExperimentalForeignApi::class)
fun DBSetRecord.toKotlin(): SetRecord {
    return SetRecord(
        set = this.set.map { it as String }.toSet(),
        iset = this.iset.map { it as Int }.toSet()
    )
}
