// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nscopying.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBSupportCopying
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun SupportCopying.toObjc(): DBSupportCopying {
    return DBSupportCopying(this.x)
}

@OptIn(ExperimentalForeignApi::class)
fun DBSupportCopying.toKotlin(): SupportCopying {
    return SupportCopying(x = this.x)
}
