// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from interface_and_abstract_class.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBTestJavaAbstractClassOnly
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
internal actual fun testMethodTestJavaAbstractClassOnly(): Boolean {
    val ret = DBTestJavaAbstractClassOnly.testMethod()
    return ret
}

@OptIn(ExperimentalForeignApi::class)
class TestJavaAbstractClassOnlyImpl(private val testJavaAbstractClassOnly: DBTestJavaAbstractClassOnly): TestJavaAbstractClassOnly {
}
