// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBTestOptionalExternInterfaceRecord
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun TestOptionalExternInterfaceRecord.toObjc(): DBTestOptionalExternInterfaceRecord {
    return DBTestOptionalExternInterfaceRecord(this.sampleInterface?.let { TODO("Map external type: [unspecified]") })
}

@OptIn(ExperimentalForeignApi::class)
fun DBTestOptionalExternInterfaceRecord.toKotlin(): TestOptionalExternInterfaceRecord {
    return TestOptionalExternInterfaceRecord(sampleInterface = TODO("Map external type: [unspecified]"))
}
