// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from ident_explicit.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBTestIdentRecord
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun TestIdentRecord.toObjc(): DBTestIdentRecord {
    return DBTestIdentRecord(
        this.FirstValue,
        this.secondValue
    )
}

@OptIn(ExperimentalForeignApi::class)
fun DBTestIdentRecord.toKotlin(): TestIdentRecord {
    return TestIdentRecord(
        FirstValue = this.FirstValue,
        secondValue = this.secondValue
    )
}
