// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from outcome.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBTestOutcome
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
internal actual fun getSuccessOutcomeTestOutcome(): com.safetyculture.djinni.support.Outcome {
    val ret = DBTestOutcome.getSuccessOutcome()
    return TODO("Map external type: com.safetyculture.djinni.support.Outcome")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun getErrorOutcomeTestOutcome(): com.safetyculture.djinni.support.Outcome {
    val ret = DBTestOutcome.getErrorOutcome()
    return TODO("Map external type: com.safetyculture.djinni.support.Outcome")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun putSuccessOutcomeTestOutcome(x: com.safetyculture.djinni.support.Outcome): String {
    val ret = DBTestOutcome.putSuccessOutcome(TODO("Map external type: com.safetyculture.djinni.support.Outcome"))
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun putErrorOutcomeTestOutcome(x: com.safetyculture.djinni.support.Outcome): Int {
    val ret = DBTestOutcome.putErrorOutcome(TODO("Map external type: com.safetyculture.djinni.support.Outcome"))
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun getNestedSuccessOutcomeTestOutcome(): NestedOutcome {
    val ret = DBTestOutcome.getNestedSuccessOutcome()
    return ret.toKotlin()
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun getNestedErrorOutcomeTestOutcome(): NestedOutcome {
    val ret = DBTestOutcome.getNestedErrorOutcome()
    return ret.toKotlin()
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun putNestedSuccessOutcomeTestOutcome(x: NestedOutcome): Int {
    val ret = DBTestOutcome.putNestedSuccessOutcome(x.toObjc())
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun putNestedErrorOutcomeTestOutcome(x: NestedOutcome): String {
    val ret = DBTestOutcome.putNestedErrorOutcome(x.toObjc())
    return ret
}

@OptIn(ExperimentalForeignApi::class)
class TestOutcomeImpl(private val testOutcome: DBTestOutcome): TestOutcome {
}
