// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBTestHelpers
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.io.Buffer

@OptIn(ExperimentalForeignApi::class)
internal actual fun getSetRecordTestHelpers(): SetRecord {
    val ret = DBTestHelpers.getSetRecord()
    return ret.toKotlin()
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkSetRecordTestHelpers(rec: SetRecord): Boolean {
    val ret = DBTestHelpers.checkSetRecord(rec.toObjc())
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun getPrimitiveListTestHelpers(): PrimitiveList {
    val ret = DBTestHelpers.getPrimitiveList()
    return ret.toKotlin()
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkPrimitiveListTestHelpers(pl: PrimitiveList): Boolean {
    val ret = DBTestHelpers.checkPrimitiveList(pl.toObjc())
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun getNestedCollectionTestHelpers(): NestedCollection {
    val ret = DBTestHelpers.getNestedCollection()
    return ret.toKotlin()
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkNestedCollectionTestHelpers(nc: NestedCollection): Boolean {
    val ret = DBTestHelpers.checkNestedCollection(nc.toObjc())
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun getMapTestHelpers(): Map<String, Long> {
    val ret = DBTestHelpers.getMap()
    return ret.map { it.key as String to it.value as Long }.toMap()
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkMapTestHelpers(m: Map<String, Long>): Boolean {
    val ret = DBTestHelpers.checkMap(m.map { it.key to it.value }.toMap())
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun getEmptyMapTestHelpers(): Map<String, Long> {
    val ret = DBTestHelpers.getEmptyMap()
    return ret.map { it.key as String to it.value as Long }.toMap()
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkEmptyMapTestHelpers(m: Map<String, Long>): Boolean {
    val ret = DBTestHelpers.checkEmptyMap(m.map { it.key to it.value }.toMap())
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun getMapListRecordTestHelpers(): MapListRecord {
    val ret = DBTestHelpers.getMapListRecord()
    return ret.toKotlin()
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkMapListRecordTestHelpers(m: MapListRecord): Boolean {
    val ret = DBTestHelpers.checkMapListRecord(m.toObjc())
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkClientInterfaceAsciiTestHelpers(i: ClientInterface) {
    DBTestHelpers.checkClientInterfaceAscii(DBClientInterfaceImpl(i))
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkClientInterfaceNonasciiTestHelpers(i: ClientInterface) {
    DBTestHelpers.checkClientInterfaceNonascii(DBClientInterfaceImpl(i))
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkClientInterfaceArgsTestHelpers(i: ClientInterface) {
    DBTestHelpers.checkClientInterfaceArgs(DBClientInterfaceImpl(i))
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkEnumMapTestHelpers(m: Map<Color, String>) {
    DBTestHelpers.checkEnumMap(m.map { it.key.toObjc() to it.value }.toMap())
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkEnumTestHelpers(c: Color) {
    DBTestHelpers.checkEnum(c.toObjc())
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun tokenIdTestHelpers(t: UserToken?): UserToken? {
    val ret = DBTestHelpers.tokenID(t?.let { DBUserTokenImpl(it) })
    return ret?.let { UserTokenImpl(it) }
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun createCppTokenTestHelpers(): UserToken? {
    val ret = DBTestHelpers.createCppToken()
    return ret?.let { UserTokenImpl(it) }
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkCppTokenTestHelpers(t: UserToken) {
    DBTestHelpers.checkCppToken(DBUserTokenImpl(t))
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun cppTokenIdTestHelpers(t: UserToken): Long {
    val ret = DBTestHelpers.cppTokenID(DBUserTokenImpl(t))
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkTokenTypeTestHelpers(
    t: UserToken,
    type: String
) {
    DBTestHelpers.checkTokenType(
        DBUserTokenImpl(t),
        type
    )
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun returnNoneTestHelpers(): Int? {
    val ret = DBTestHelpers.returnNone()
    return ret?.intValue()
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun assortedPrimitivesIdTestHelpers(i: AssortedPrimitives): AssortedPrimitives {
    val ret = DBTestHelpers.assortedPrimitivesID(i.toObjc())
    return ret.toKotlin()
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun idBinaryTestHelpers(b: Buffer): Buffer {
    val ret = DBTestHelpers.idBinary(TODO("Map: MBinary"))
    return TODO("Map: MBinary")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun getAsyncResultTestHelpers(): com.safetyculture.djinni.support.Future {
    val ret = DBTestHelpers.getAsyncResult()
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun futureRoundtripTestHelpers(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future {
    val ret = DBTestHelpers.futureRoundtrip(TODO("Map external type: com.safetyculture.djinni.support.Future"))
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun asyncEarlyThrowTestHelpers(): com.safetyculture.djinni.support.Future {
    val ret = DBTestHelpers.asyncEarlyThrow()
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun voidAsyncMethodTestHelpers(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future {
    val ret = DBTestHelpers.voidAsyncMethod(TODO("Map external type: com.safetyculture.djinni.support.Future"))
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun addOneIfPresentTestHelpers(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future {
    val ret = DBTestHelpers.addOneIfPresent(TODO("Map external type: com.safetyculture.djinni.support.Future"))
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun returnExceptionStringTestHelpers(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future {
    val ret = DBTestHelpers.returnExceptionString(TODO("Map external type: com.safetyculture.djinni.support.Future"))
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkAsyncInterfaceTestHelpers(i: AsyncInterface): com.safetyculture.djinni.support.Future {
    val ret = DBTestHelpers.checkAsyncInterface(DBAsyncInterfaceImpl(i))
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkAsyncCompositionTestHelpers(i: AsyncInterface): com.safetyculture.djinni.support.Future {
    val ret = DBTestHelpers.checkAsyncComposition(DBAsyncInterfaceImpl(i))
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun getOptionalListTestHelpers(): List<String?> {
    val ret = DBTestHelpers.getOptionalList()
    return ret.map { (it as NSString?) }
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkOptionalListTestHelpers(ol: List<String?>): Boolean {
    val ret = DBTestHelpers.checkOptionalList(ArrayList(ol.map { it }))
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun getOptionalSetTestHelpers(): Set<String?> {
    val ret = DBTestHelpers.getOptionalSet()
    return ret.map { (it as NSString?) }.toSet()
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkOptionalSetTestHelpers(os: Set<String?>): Boolean {
    val ret = DBTestHelpers.checkOptionalSet(os.map { it }.toSet())
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun getOptionalMapTestHelpers(): Map<String?, String?> {
    val ret = DBTestHelpers.getOptionalMap()
    return ret.map { (it.key as NSString?) to (it.value as NSString?) }.toMap()
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkOptionalMapTestHelpers(om: Map<String?, String?>): Boolean {
    val ret = DBTestHelpers.checkOptionalMap(om.map { it.key to it.value }.toMap())
    return ret
}

@OptIn(ExperimentalForeignApi::class)
class TestHelpersImpl(private val testHelpers: DBTestHelpers): TestHelpers {
}
