// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from static_method_language.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBTestStaticMethodLanguage
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
internal actual fun testMethodTestStaticMethodLanguage() {
    DBTestStaticMethodLanguage.testMethod()
}

@OptIn(ExperimentalForeignApi::class)
class TestStaticMethodLanguageImpl(private val testStaticMethodLanguage: DBTestStaticMethodLanguage): TestStaticMethodLanguage {
}
