// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from ident_explicit.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBTestIdentEnum
import kotlinx.cinterop.ExperimentalForeignApi
import platform.Foundation.NSNumber

@OptIn(ExperimentalForeignApi::class)
fun TESTIDENTENUM.toObjc(): DBTestIdentEnum {
    return when(this) {
        TESTIDENTENUM.SNAKE_ENUM -> TestSuite.DBTestIdentEnumNativeSnakeEnum
        TESTIDENTENUM.CAPS_ENUM -> TestSuite.DBTestIdentEnumNativeCapsEnum
    }
}

@OptIn(ExperimentalForeignApi::class)
fun TESTIDENTENUM.toNSNumber(): NSNumber {
    return NSNumber(long = toObjc())
}

@OptIn(ExperimentalForeignApi::class)
fun TESTIDENTENUM.Companion.fromObjc(e: DBTestIdentEnum): TESTIDENTENUM {
    return when(e) {
        TestSuite.DBTestIdentEnumNativeSnakeEnum -> TESTIDENTENUM.SNAKE_ENUM
        TestSuite.DBTestIdentEnumNativeCapsEnum -> TESTIDENTENUM.CAPS_ENUM
         else -> throw IllegalArgumentException("Unknown TESTIDENTENUM: $e")
    }
}

@OptIn(ExperimentalForeignApi::class)
fun TESTIDENTENUM.Companion.fromNSNumber(e: NSNumber): TESTIDENTENUM {
    return fromObjc(e.integerValue)
}
