// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBTestDuration
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
internal actual fun hoursStringTestDuration(dt: [unspecified]): String {
    val ret = DBTestDuration.hoursString(TODO("Map external type: [unspecified]"))
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun minutesStringTestDuration(dt: [unspecified]): String {
    val ret = DBTestDuration.minutesString(TODO("Map external type: [unspecified]"))
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun secondsStringTestDuration(dt: [unspecified]): String {
    val ret = DBTestDuration.secondsString(TODO("Map external type: [unspecified]"))
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun millisStringTestDuration(dt: [unspecified]): String {
    val ret = DBTestDuration.millisString(TODO("Map external type: [unspecified]"))
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun microsStringTestDuration(dt: [unspecified]): String {
    val ret = DBTestDuration.microsString(TODO("Map external type: [unspecified]"))
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun nanosStringTestDuration(dt: [unspecified]): String {
    val ret = DBTestDuration.nanosString(TODO("Map external type: [unspecified]"))
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun hoursTestDuration(count: Int): [unspecified] {
    val ret = DBTestDuration.hours(count)
    return TODO("Map external type: [unspecified]")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun minutesTestDuration(count: Int): [unspecified] {
    val ret = DBTestDuration.minutes(count)
    return TODO("Map external type: [unspecified]")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun secondsTestDuration(count: Int): [unspecified] {
    val ret = DBTestDuration.seconds(count)
    return TODO("Map external type: [unspecified]")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun millisTestDuration(count: Int): [unspecified] {
    val ret = DBTestDuration.millis(count)
    return TODO("Map external type: [unspecified]")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun microsTestDuration(count: Int): [unspecified] {
    val ret = DBTestDuration.micros(count)
    return TODO("Map external type: [unspecified]")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun nanosTestDuration(count: Int): [unspecified] {
    val ret = DBTestDuration.nanos(count)
    return TODO("Map external type: [unspecified]")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun hoursfTestDuration(count: Double): [unspecified] {
    val ret = DBTestDuration.hoursf(count)
    return TODO("Map external type: [unspecified]")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun minutesfTestDuration(count: Double): [unspecified] {
    val ret = DBTestDuration.minutesf(count)
    return TODO("Map external type: [unspecified]")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun secondsfTestDuration(count: Double): [unspecified] {
    val ret = DBTestDuration.secondsf(count)
    return TODO("Map external type: [unspecified]")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun millisfTestDuration(count: Double): [unspecified] {
    val ret = DBTestDuration.millisf(count)
    return TODO("Map external type: [unspecified]")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun microsfTestDuration(count: Double): [unspecified] {
    val ret = DBTestDuration.microsf(count)
    return TODO("Map external type: [unspecified]")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun nanosfTestDuration(count: Double): [unspecified] {
    val ret = DBTestDuration.nanosf(count)
    return TODO("Map external type: [unspecified]")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun boxTestDuration(count: Long): [unspecified]? {
    val ret = DBTestDuration.box(count)
    return TODO("Map external type: [unspecified]")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun unboxTestDuration(dt: [unspecified]?): Long {
    val ret = DBTestDuration.unbox(dt?.let { TODO("Map external type: [unspecified]") })
    return ret
}

@OptIn(ExperimentalForeignApi::class)
class TestDurationImpl(private val testDuration: DBTestDuration): TestDuration {
}
