// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from array.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBTestArray
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
internal actual fun testStringArrayTestArray(a: TODO("Map: MArray<String>")<String>): TODO("Map: MArray<String>")<String> {
    val ret = DBTestArray.testStringArray(TODO("Map: MArray<String>"))
    return TODO("Map: MArray<String>")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun testIntArrayTestArray(a: TODO("Map: MArray<Int>")<Int>): TODO("Map: MArray<Int>")<Int> {
    val ret = DBTestArray.testIntArray(TODO("Map: MArray<Int>"))
    return TODO("Map: MArray<Int>")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun testRecordArrayTestArray(a: TODO("Map: MArray<Vec2>")<Vec2>): TODO("Map: MArray<Vec2>")<Vec2> {
    val ret = DBTestArray.testRecordArray(TODO("Map: MArray<Vec2>"))
    return TODO("Map: MArray<Vec2>")
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun testArrayOfArrayTestArray(a: TODO("Map: MArray<TODO("Map: MArray<Int>")<Int>>")<TODO("Map: MArray<Int>")<Int>>): TODO("Map: MArray<TODO("Map: MArray<Int>")<Int>>")<TODO("Map: MArray<Int>")<Int>> {
    val ret = DBTestArray.testArrayOfArray(TODO("Map: MArray<TODO("Map: MArray<Int>")<Int>>"))
    return TODO("Map: MArray<TODO("Map: MArray<Int>")<Int>>")
}

@OptIn(ExperimentalForeignApi::class)
class TestArrayImpl(private val testArray: DBTestArray): TestArray {
}
