// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from user_token.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBUserTokenProtocol
import kotlinx.cinterop.ExperimentalForeignApi
import platform.darwin.NSObject

@OptIn(ExperimentalForeignApi::class)
class DBUserTokenImpl(private val userToken: UserToken): NSObject(), DBUserTokenProtocol {
    override fun whoami(): String {
        val ret = userToken.whoami()

        return ret
    }
}
