// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from single_language_interfaces.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBJavaOnlyListenerProtocol
import TestSuite.DBObjcOnlyListenerProtocol
import TestSuite.DBUsesSingleLanguageListenersProtocol
import kotlinx.cinterop.ExperimentalForeignApi
import platform.darwin.NSObject

@OptIn(ExperimentalForeignApi::class)
class DBUsesSingleLanguageListenersImpl(private val usesSingleLanguageListeners: UsesSingleLanguageListeners): NSObject(), DBUsesSingleLanguageListenersProtocol {
    override fun callForObjC(l: DBObjcOnlyListenerProtocol): Unit {
        usesSingleLanguageListeners.callForObjC(throw UnsupportedOperationException("Impossible to map id<DBObjcOnlyListener> in this direction"))
    }

    override fun returnForObjC(): DBObjcOnlyListenerProtocol {
        val ret = usesSingleLanguageListeners.returnForObjC()

        return DBObjcOnlyListenerImpl(ret)
    }

    override fun callForJava(l: DBJavaOnlyListenerProtocol): Unit {
        usesSingleLanguageListeners.callForJava(throw UnsupportedOperationException("Impossible to map DBJavaOnlyListener in this direction"))
    }

    override fun returnForJava(): DBJavaOnlyListenerProtocol {
        val ret = usesSingleLanguageListeners.returnForJava()

        return TODO("Impossible to map JavaOnlyListener in this direction")
    }
}
