// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from varnames.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBVarnameInterface
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
class VarnameInterfaceImpl(private val VarnameInterface: DBVarnameInterface): VarnameInterface {
    override fun Rmethod(RArg: VarnameRecord): VarnameRecord {
        val ret = VarnameInterface.Rmethod(RArg.toObjc())
        return ret.toKotlin()
    }

    override fun Imethod(IArg: VarnameInterface): VarnameInterface? {
        val ret = VarnameInterface.Imethod(TODO("Impossible to map VarnameInterface in this direction"))
        return ret?.let { VarnameInterfaceImpl(it) }
    }
}
