// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from varnames.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBVarnameRecord
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun VarnameRecord.toObjc(): DBVarnameRecord {
    return DBVarnameRecord(this.Field)
}

@OptIn(ExperimentalForeignApi::class)
fun DBVarnameRecord.toKotlin(): VarnameRecord {
    return VarnameRecord(Field = this.Field)
}
