// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from array.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBVec2
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun Vec2.toObjc(): DBVec2 {
    return DBVec2(
        this.x,
        this.y
    )
}

@OptIn(ExperimentalForeignApi::class)
fun DBVec2.toKotlin(): Vec2 {
    return Vec2(
        x = this.x,
        y = this.y
    )
}
