// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from wchar_test.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBWcharTestHelpers
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
internal actual fun getRecordWcharTestHelpers(): WcharTestRec {
    val ret = DBWcharTestHelpers.getRecord()
    return ret.toKotlin()
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun getStringWcharTestHelpers(): String {
    val ret = DBWcharTestHelpers.getString()
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkStringWcharTestHelpers(str: String): Boolean {
    val ret = DBWcharTestHelpers.checkString(str)
    return ret
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun checkRecordWcharTestHelpers(rec: WcharTestRec): Boolean {
    val ret = DBWcharTestHelpers.checkRecord(rec.toObjc())
    return ret
}

@OptIn(ExperimentalForeignApi::class)
class WcharTestHelpersImpl(private val wcharTestHelpers: DBWcharTestHelpers): WcharTestHelpers {
}
