// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from wchar_test.djinni

package com.dropbox.djinni.test.interop

import TestSuite.DBWcharTestRec
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun WcharTestRec.toObjc(): DBWcharTestRec {
    return DBWcharTestRec(this.s)
}

@OptIn(ExperimentalForeignApi::class)
fun DBWcharTestRec.toKotlin(): WcharTestRec {
    return WcharTestRec(s = this.s)
}
