// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort.interop

import java.util.ArrayList

fun ItemList.toJava(): com.dropbox.textsort.ItemList {
    return com.dropbox.textsort.ItemList(ArrayList(this.items.map { it }))
}

fun com.dropbox.textsort.ItemList.toKotlin(): ItemList {
    return ItemList(items = this.items.map { it })
}
