// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort.interop

fun SortOrder.toJava(): com.dropbox.textsort.SortOrder {
    return when(this) {
        SortOrder.ASCENDING -> com.dropbox.textsort.SortOrder.ASCENDING
        SortOrder.DESCENDING -> com.dropbox.textsort.SortOrder.DESCENDING
        SortOrder.RANDOM -> com.dropbox.textsort.SortOrder.RANDOM
    }
}

fun com.dropbox.textsort.SortOrder.toKotlin(): SortOrder {
    return when(this) {
        com.dropbox.textsort.SortOrder.ASCENDING -> SortOrder.ASCENDING
        com.dropbox.textsort.SortOrder.DESCENDING -> SortOrder.DESCENDING
        com.dropbox.textsort.SortOrder.RANDOM -> SortOrder.RANDOM
    }
}
