// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort.interop

internal actual fun createWithListenerSortItems(listener: TextboxListener): SortItems? {
    val ret = com.dropbox.textsort.SortItems.createWithListener(TextboxListenerImpl(listener))
    return ret?.let { SortItemsImpl(it) }
}

internal actual fun runSortSortItems(items: ItemList): ItemList {
    val ret = com.dropbox.textsort.SortItems.runSort(items.toJava())
    return ret.toKotlin()
}

class SortItemsImpl(private val sortItems: com.dropbox.textsort.SortItems): SortItems {
    override fun sort(
        order: SortOrder,
        items: ItemList
    ) {
        sortItems.sort(
            order.toJava(),
            items.toJava()
        )
    }
}
