// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort.interop

class TextboxListenerImpl(private val textboxListener: TextboxListener): com.dropbox.textsort.TextboxListener() {
    override fun update(items: com.dropbox.textsort.ItemList) {
        textboxListener.update (items.toKotlin())
    }
}
