// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test.interop


interface AsyncInterface {
    fun futureRoundtrip(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future
}
