// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test.interop

import kotlinx.io.Buffer


interface ClientInterface {
    fun getRecord(
        recordId: Long,
        utf8string: String,
        misc: String?
    ): ClientReturnedRecord
    fun identifierCheck(
        data: Buffer,
        r: Int,
        jret: Long
    ): Double
    fun returnStr(): String
    fun methTakingInterface(i: ClientInterface): String
    fun methTakingOptionalInterface(i: ClientInterface?): String
}
