// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

package com.dropbox.djinni.test.interop

enum class ConstantEnum {
    SOME_VALUE,
    SOME_OTHER_VALUE;
    companion object {}
}
