// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from exception.djinni

package com.dropbox.djinni.test.interop

internal expect fun getCppException(): CppException?

interface CppException {
    companion object {
        fun get(): CppException? = getCppException()
    }

    fun throwAnException(): Int
    fun callThrowingInterface(cb: ThrowingInterface): Int
    fun callThrowingAndCatch(cb: ThrowingInterface): String
}
