// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from data_ref_view.djinni

package com.dropbox.djinni.test.interop

import kotlinx.io.Buffer

internal expect fun createDataRefTest(): DataRefTest?

interface DataRefTest {
    companion object {
        fun create(): DataRefTest? = createDataRefTest()
    }

    fun sendData(data: com.safetyculture.djinni.support.ByteBuffer)
    fun retriveAsBin(): Buffer
    fun sendMutableData(data: com.safetyculture.djinni.support.ByteBuffer)
    fun generateData(): com.safetyculture.djinni.support.ByteBuffer
    fun dataFromVec(): com.safetyculture.djinni.support.ByteBuffer
    fun dataFromStr(): com.safetyculture.djinni.support.ByteBuffer
    fun sendDataView(data: com.safetyculture.djinni.support.ByteBuffer): Buffer
    fun recvDataView(): com.safetyculture.djinni.support.ByteBuffer
}
