// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

package com.dropbox.djinni.test.interop

data class ExternRecordWithDerivings(
    val member: [unspecified],
    val e: [unspecified]
)