// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

package com.dropbox.djinni.test.interop


interface ExternInterface2 {
    fun foo(i: [unspecified]): ExternRecordWithDerivings
}
