// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

package com.dropbox.djinni.test.interop

internal expect fun roundtripAccessFlagRoundtrip(flag: AccessFlags): AccessFlags
internal expect fun roundtripEmptyFlagRoundtrip(flag: EmptyFlags): EmptyFlags
internal expect fun roundtripAccessBoxedFlagRoundtrip(flag: AccessFlags?): AccessFlags?
internal expect fun roundtripEmptyBoxedFlagRoundtrip(flag: EmptyFlags?): EmptyFlags?

interface FlagRoundtrip {
    companion object {
        fun roundtripAccess(flag: AccessFlags): AccessFlags = roundtripAccessFlagRoundtrip(flag)
        fun roundtripEmpty(flag: EmptyFlags): EmptyFlags = roundtripEmptyFlagRoundtrip(flag)
        fun roundtripAccessBoxed(flag: AccessFlags?): AccessFlags? = roundtripAccessBoxedFlagRoundtrip(flag)
        fun roundtripEmptyBoxed(flag: EmptyFlags?): EmptyFlags? = roundtripEmptyBoxedFlagRoundtrip(flag)
    }

}
