// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from function_prologue.djinni

package com.dropbox.djinni.test.interop

internal expect fun fooFunctionPrologueHelper(): String

interface FunctionPrologueHelper {
    companion object {
        fun foo(): String = fooFunctionPrologueHelper()
    }

}
