// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test.interop

internal expect fun initListenerCaller(
    firstL: FirstListener,
    secondL: SecondListener
): ListenerCaller?

interface ListenerCaller {
    companion object {
        fun init(
            firstL: FirstListener,
            secondL: SecondListener
        ): ListenerCaller? = initListenerCaller(
            firstL,
            secondL
        )
    }

    fun callFirst()
    fun callSecond()
}
