// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

package com.dropbox.djinni.test.interop

data class MapDateRecord(val datesById: Map<String, [unspecified]>)