// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from outcome.djinni

package com.dropbox.djinni.test.interop

data class NestedOutcome(val o: com.safetyculture.djinni.support.Outcome)