// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test.interop

internal expect fun protoToStringsProtoTests(x: TODO("Map: MProtobuf")): List<String>
internal expect fun stringsToProtoProtoTests(x: List<String>): TODO("Map: MProtobuf")
internal expect fun embeddedProtoToStringProtoTests(x: RecordWithEmbeddedProto): String
internal expect fun stringToEmbeddedProtoProtoTests(x: String): RecordWithEmbeddedProto
internal expect fun cppProtoToStringProtoTests(x: TODO("Map: MProtobuf")): String
internal expect fun stringToCppProtoProtoTests(x: String): TODO("Map: MProtobuf")
internal expect fun embeddedCppProtoToStringProtoTests(x: RecordWithEmbeddedCppProto): String
internal expect fun stringToEmbeddedCppProtoProtoTests(x: String): RecordWithEmbeddedCppProto
internal expect fun protoListToStringsProtoTests(x: List<TODO("Map: MProtobuf")>): List<String>
internal expect fun stringsToProtoListProtoTests(x: List<String>): List<TODO("Map: MProtobuf")>
internal expect fun optionalProtoToStringProtoTests(x: TODO("Map: MProtobuf")?): String
internal expect fun stringToOptionalProtoProtoTests(x: String): TODO("Map: MProtobuf")?
internal expect fun stringToProtoOutcomeProtoTests(x: String): com.safetyculture.djinni.support.Outcome

interface ProtoTests {
    companion object {
        fun protoToStrings(x: TODO("Map: MProtobuf")): List<String> = protoToStringsProtoTests(x)
        fun stringsToProto(x: List<String>): TODO("Map: MProtobuf") = stringsToProtoProtoTests(x)
        fun embeddedProtoToString(x: RecordWithEmbeddedProto): String = embeddedProtoToStringProtoTests(x)
        fun stringToEmbeddedProto(x: String): RecordWithEmbeddedProto = stringToEmbeddedProtoProtoTests(x)
        fun cppProtoToString(x: TODO("Map: MProtobuf")): String = cppProtoToStringProtoTests(x)
        fun stringToCppProto(x: String): TODO("Map: MProtobuf") = stringToCppProtoProtoTests(x)
        fun embeddedCppProtoToString(x: RecordWithEmbeddedCppProto): String = embeddedCppProtoToStringProtoTests(x)
        fun stringToEmbeddedCppProto(x: String): RecordWithEmbeddedCppProto = stringToEmbeddedCppProtoProtoTests(x)
        fun protoListToStrings(x: List<TODO("Map: MProtobuf")>): List<String> = protoListToStringsProtoTests(x)
        fun stringsToProtoList(x: List<String>): List<TODO("Map: MProtobuf")> = stringsToProtoListProtoTests(x)
        fun optionalProtoToString(x: TODO("Map: MProtobuf")?): String = optionalProtoToStringProtoTests(x)
        fun stringToOptionalProto(x: String): TODO("Map: MProtobuf")? = stringToOptionalProtoProtoTests(x)
        fun stringToProtoOutcome(x: String): com.safetyculture.djinni.support.Outcome = stringToProtoOutcomeProtoTests(x)
    }

}
