// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test.interop

data class RecordWithEmbeddedCppProto(val state: TODO("Map: MProtobuf"))