// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

package com.dropbox.djinni.test.interop

import kotlinx.datetime.Instant

data class RecordWithDerivings(
    val eight: Byte,
    val sixteen: Short,
    val thirtytwo: Int,
    val sixtyfour: Long,
    val fthirtytwo: Float,
    val fsixtyfour: Double,
    val d: Instant,
    val s: String
)