// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

package com.dropbox.djinni.test.interop

data class RecordWithNestedDerivings(
    val key: Int,
    val rec: RecordWithDerivings
)