// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

package com.dropbox.djinni.test.interop

data class RecordWithDurationAndDerivings(val dt: [unspecified])