// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test.interop

internal expect fun getInstanceReturnTwo(): ReturnTwo?

interface ReturnTwo {
    companion object {
        fun getInstance(): ReturnTwo? = getInstanceReturnTwo()
    }

    fun returnTwo(): Byte
}
