// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test.interop

internal expect fun getInstanceReturnOne(): ReturnOne?

interface ReturnOne {
    companion object {
        fun getInstance(): ReturnOne? = getInstanceReturnOne()
    }

    fun returnOne(): Byte
}
