// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test.interop

internal expect fun createReverseClientInterface(): ReverseClientInterface?

interface ReverseClientInterface {
    companion object {
        fun create(): ReverseClientInterface? = createReverseClientInterface()
    }

    fun returnStr(): String
    fun methTakingInterface(i: ReverseClientInterface): String
    fun methTakingOptionalInterface(i: ReverseClientInterface?): String
}
