// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from outcome.djinni

package com.dropbox.djinni.test.interop

internal expect fun getSuccessOutcomeTestOutcome(): com.safetyculture.djinni.support.Outcome
internal expect fun getErrorOutcomeTestOutcome(): com.safetyculture.djinni.support.Outcome
internal expect fun putSuccessOutcomeTestOutcome(x: com.safetyculture.djinni.support.Outcome): String
internal expect fun putErrorOutcomeTestOutcome(x: com.safetyculture.djinni.support.Outcome): Int
internal expect fun getNestedSuccessOutcomeTestOutcome(): NestedOutcome
internal expect fun getNestedErrorOutcomeTestOutcome(): NestedOutcome
internal expect fun putNestedSuccessOutcomeTestOutcome(x: NestedOutcome): Int
internal expect fun putNestedErrorOutcomeTestOutcome(x: NestedOutcome): String

interface TestOutcome {
    companion object {
        fun getSuccessOutcome(): com.safetyculture.djinni.support.Outcome = getSuccessOutcomeTestOutcome()
        fun getErrorOutcome(): com.safetyculture.djinni.support.Outcome = getErrorOutcomeTestOutcome()
        fun putSuccessOutcome(x: com.safetyculture.djinni.support.Outcome): String = putSuccessOutcomeTestOutcome(x)
        fun putErrorOutcome(x: com.safetyculture.djinni.support.Outcome): Int = putErrorOutcomeTestOutcome(x)
        fun getNestedSuccessOutcome(): NestedOutcome = getNestedSuccessOutcomeTestOutcome()
        fun getNestedErrorOutcome(): NestedOutcome = getNestedErrorOutcomeTestOutcome()
        fun putNestedSuccessOutcome(x: NestedOutcome): Int = putNestedSuccessOutcomeTestOutcome(x)
        fun putNestedErrorOutcome(x: NestedOutcome): String = putNestedErrorOutcomeTestOutcome(x)
    }

}
