// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

package com.dropbox.djinni.test.interop

internal expect fun hoursStringTestDuration(dt: [unspecified]): String
internal expect fun minutesStringTestDuration(dt: [unspecified]): String
internal expect fun secondsStringTestDuration(dt: [unspecified]): String
internal expect fun millisStringTestDuration(dt: [unspecified]): String
internal expect fun microsStringTestDuration(dt: [unspecified]): String
internal expect fun nanosStringTestDuration(dt: [unspecified]): String
internal expect fun hoursTestDuration(count: Int): [unspecified]
internal expect fun minutesTestDuration(count: Int): [unspecified]
internal expect fun secondsTestDuration(count: Int): [unspecified]
internal expect fun millisTestDuration(count: Int): [unspecified]
internal expect fun microsTestDuration(count: Int): [unspecified]
internal expect fun nanosTestDuration(count: Int): [unspecified]
internal expect fun hoursfTestDuration(count: Double): [unspecified]
internal expect fun minutesfTestDuration(count: Double): [unspecified]
internal expect fun secondsfTestDuration(count: Double): [unspecified]
internal expect fun millisfTestDuration(count: Double): [unspecified]
internal expect fun microsfTestDuration(count: Double): [unspecified]
internal expect fun nanosfTestDuration(count: Double): [unspecified]
internal expect fun boxTestDuration(count: Long): [unspecified]?
internal expect fun unboxTestDuration(dt: [unspecified]?): Long

interface TestDuration {
    companion object {
        fun hoursString(dt: [unspecified]): String = hoursStringTestDuration(dt)
        fun minutesString(dt: [unspecified]): String = minutesStringTestDuration(dt)
        fun secondsString(dt: [unspecified]): String = secondsStringTestDuration(dt)
        fun millisString(dt: [unspecified]): String = millisStringTestDuration(dt)
        fun microsString(dt: [unspecified]): String = microsStringTestDuration(dt)
        fun nanosString(dt: [unspecified]): String = nanosStringTestDuration(dt)
        fun hours(count: Int): [unspecified] = hoursTestDuration(count)
        fun minutes(count: Int): [unspecified] = minutesTestDuration(count)
        fun seconds(count: Int): [unspecified] = secondsTestDuration(count)
        fun millis(count: Int): [unspecified] = millisTestDuration(count)
        fun micros(count: Int): [unspecified] = microsTestDuration(count)
        fun nanos(count: Int): [unspecified] = nanosTestDuration(count)
        fun hoursf(count: Double): [unspecified] = hoursfTestDuration(count)
        fun minutesf(count: Double): [unspecified] = minutesfTestDuration(count)
        fun secondsf(count: Double): [unspecified] = secondsfTestDuration(count)
        fun millisf(count: Double): [unspecified] = millisfTestDuration(count)
        fun microsf(count: Double): [unspecified] = microsfTestDuration(count)
        fun nanosf(count: Double): [unspecified] = nanosfTestDuration(count)
        fun box(count: Long): [unspecified]? = boxTestDuration(count)
        fun unbox(dt: [unspecified]?): Long = unboxTestDuration(dt)
    }

}
