// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from interface_and_abstract_class.djinni

package com.dropbox.djinni.test.interop

internal expect fun testMethodTestJavaAbstractClassOnly(): Boolean

interface TestJavaAbstractClassOnly {
    companion object {
        fun testMethod(): Boolean = testMethodTestJavaAbstractClassOnly()
    }

}
