// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from array.djinni

package com.dropbox.djinni.test.interop

internal expect fun testStringArrayTestArray(a: TODO("Map: MArray<String>")<String>): TODO("Map: MArray<String>")<String>
internal expect fun testIntArrayTestArray(a: TODO("Map: MArray<Int>")<Int>): TODO("Map: MArray<Int>")<Int>
internal expect fun testRecordArrayTestArray(a: TODO("Map: MArray<Vec2>")<Vec2>): TODO("Map: MArray<Vec2>")<Vec2>
internal expect fun testArrayOfArrayTestArray(a: TODO("Map: MArray<TODO("Map: MArray<Int>")<Int>>")<TODO("Map: MArray<Int>")<Int>>): TODO("Map: MArray<TODO("Map: MArray<Int>")<Int>>")<TODO("Map: MArray<Int>")<Int>>

interface TestArray {
    companion object {
        fun testStringArray(a: TODO("Map: MArray<String>")<String>): TODO("Map: MArray<String>")<String> = testStringArrayTestArray(a)
        fun testIntArray(a: TODO("Map: MArray<Int>")<Int>): TODO("Map: MArray<Int>")<Int> = testIntArrayTestArray(a)
        fun testRecordArray(a: TODO("Map: MArray<Vec2>")<Vec2>): TODO("Map: MArray<Vec2>")<Vec2> = testRecordArrayTestArray(a)
        fun testArrayOfArray(a: TODO("Map: MArray<TODO("Map: MArray<Int>")<Int>>")<TODO("Map: MArray<Int>")<Int>>): TODO("Map: MArray<TODO("Map: MArray<Int>")<Int>>")<TODO("Map: MArray<Int>")<Int>> = testArrayOfArrayTestArray(a)
    }

}
