// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from ident_explicit.djinni

package com.dropbox.djinni.test.interop

data class TestIdentRecord(
    val FirstValue: Int,
    val secondValue: String
)