// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test.interop

import kotlinx.io.Buffer

internal expect fun getSetRecordTestHelpers(): SetRecord
internal expect fun checkSetRecordTestHelpers(rec: SetRecord): Boolean
internal expect fun getPrimitiveListTestHelpers(): PrimitiveList
internal expect fun checkPrimitiveListTestHelpers(pl: PrimitiveList): Boolean
internal expect fun getNestedCollectionTestHelpers(): NestedCollection
internal expect fun checkNestedCollectionTestHelpers(nc: NestedCollection): Boolean
internal expect fun getMapTestHelpers(): Map<String, Long>
internal expect fun checkMapTestHelpers(m: Map<String, Long>): Boolean
internal expect fun getEmptyMapTestHelpers(): Map<String, Long>
internal expect fun checkEmptyMapTestHelpers(m: Map<String, Long>): Boolean
internal expect fun getMapListRecordTestHelpers(): MapListRecord
internal expect fun checkMapListRecordTestHelpers(m: MapListRecord): Boolean
internal expect fun checkClientInterfaceAsciiTestHelpers(i: ClientInterface)
internal expect fun checkClientInterfaceNonasciiTestHelpers(i: ClientInterface)
internal expect fun checkClientInterfaceArgsTestHelpers(i: ClientInterface)
internal expect fun checkEnumMapTestHelpers(m: Map<Color, String>)
internal expect fun checkEnumTestHelpers(c: Color)
internal expect fun tokenIdTestHelpers(t: UserToken?): UserToken?
internal expect fun createCppTokenTestHelpers(): UserToken?
internal expect fun checkCppTokenTestHelpers(t: UserToken)
internal expect fun cppTokenIdTestHelpers(t: UserToken): Long
internal expect fun checkTokenTypeTestHelpers(
    t: UserToken,
    type: String
)
internal expect fun returnNoneTestHelpers(): Int?
internal expect fun assortedPrimitivesIdTestHelpers(i: AssortedPrimitives): AssortedPrimitives
internal expect fun idBinaryTestHelpers(b: Buffer): Buffer
internal expect fun getAsyncResultTestHelpers(): com.safetyculture.djinni.support.Future
internal expect fun futureRoundtripTestHelpers(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future
internal expect fun asyncEarlyThrowTestHelpers(): com.safetyculture.djinni.support.Future
internal expect fun voidAsyncMethodTestHelpers(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future
internal expect fun addOneIfPresentTestHelpers(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future
internal expect fun returnExceptionStringTestHelpers(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future
internal expect fun checkAsyncInterfaceTestHelpers(i: AsyncInterface): com.safetyculture.djinni.support.Future
internal expect fun checkAsyncCompositionTestHelpers(i: AsyncInterface): com.safetyculture.djinni.support.Future
internal expect fun getOptionalListTestHelpers(): List<String?>
internal expect fun checkOptionalListTestHelpers(ol: List<String?>): Boolean
internal expect fun getOptionalSetTestHelpers(): Set<String?>
internal expect fun checkOptionalSetTestHelpers(os: Set<String?>): Boolean
internal expect fun getOptionalMapTestHelpers(): Map<String?, String?>
internal expect fun checkOptionalMapTestHelpers(om: Map<String?, String?>): Boolean

interface TestHelpers {
    companion object {
        fun getSetRecord(): SetRecord = getSetRecordTestHelpers()
        fun checkSetRecord(rec: SetRecord): Boolean = checkSetRecordTestHelpers(rec)
        fun getPrimitiveList(): PrimitiveList = getPrimitiveListTestHelpers()
        fun checkPrimitiveList(pl: PrimitiveList): Boolean = checkPrimitiveListTestHelpers(pl)
        fun getNestedCollection(): NestedCollection = getNestedCollectionTestHelpers()
        fun checkNestedCollection(nc: NestedCollection): Boolean = checkNestedCollectionTestHelpers(nc)
        fun getMap(): Map<String, Long> = getMapTestHelpers()
        fun checkMap(m: Map<String, Long>): Boolean = checkMapTestHelpers(m)
        fun getEmptyMap(): Map<String, Long> = getEmptyMapTestHelpers()
        fun checkEmptyMap(m: Map<String, Long>): Boolean = checkEmptyMapTestHelpers(m)
        fun getMapListRecord(): MapListRecord = getMapListRecordTestHelpers()
        fun checkMapListRecord(m: MapListRecord): Boolean = checkMapListRecordTestHelpers(m)
        fun checkClientInterfaceAscii(i: ClientInterface) = checkClientInterfaceAsciiTestHelpers(i)
        fun checkClientInterfaceNonascii(i: ClientInterface) = checkClientInterfaceNonasciiTestHelpers(i)
        fun checkClientInterfaceArgs(i: ClientInterface) = checkClientInterfaceArgsTestHelpers(i)
        fun checkEnumMap(m: Map<Color, String>) = checkEnumMapTestHelpers(m)
        fun checkEnum(c: Color) = checkEnumTestHelpers(c)
        fun tokenId(t: UserToken?): UserToken? = tokenIdTestHelpers(t)
        fun createCppToken(): UserToken? = createCppTokenTestHelpers()
        fun checkCppToken(t: UserToken) = checkCppTokenTestHelpers(t)
        fun cppTokenId(t: UserToken): Long = cppTokenIdTestHelpers(t)
        fun checkTokenType(
            t: UserToken,
            type: String
        ) = checkTokenTypeTestHelpers(
            t,
            type
        )
        fun returnNone(): Int? = returnNoneTestHelpers()
        fun assortedPrimitivesId(i: AssortedPrimitives): AssortedPrimitives = assortedPrimitivesIdTestHelpers(i)
        fun idBinary(b: Buffer): Buffer = idBinaryTestHelpers(b)
        fun getAsyncResult(): com.safetyculture.djinni.support.Future = getAsyncResultTestHelpers()
        fun futureRoundtrip(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future = futureRoundtripTestHelpers(f)
        fun asyncEarlyThrow(): com.safetyculture.djinni.support.Future = asyncEarlyThrowTestHelpers()
        fun voidAsyncMethod(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future = voidAsyncMethodTestHelpers(f)
        fun addOneIfPresent(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future = addOneIfPresentTestHelpers(f)
        fun returnExceptionString(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future = returnExceptionStringTestHelpers(f)
        fun checkAsyncInterface(i: AsyncInterface): com.safetyculture.djinni.support.Future = checkAsyncInterfaceTestHelpers(i)
        fun checkAsyncComposition(i: AsyncInterface): com.safetyculture.djinni.support.Future = checkAsyncCompositionTestHelpers(i)
        fun getOptionalList(): List<String?> = getOptionalListTestHelpers()
        fun checkOptionalList(ol: List<String?>): Boolean = checkOptionalListTestHelpers(ol)
        fun getOptionalSet(): Set<String?> = getOptionalSetTestHelpers()
        fun checkOptionalSet(os: Set<String?>): Boolean = checkOptionalSetTestHelpers(os)
        fun getOptionalMap(): Map<String?, String?> = getOptionalMapTestHelpers()
        fun checkOptionalMap(om: Map<String?, String?>): Boolean = checkOptionalMapTestHelpers(om)
    }

}
