// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from static_method_language.djinni

package com.dropbox.djinni.test.interop

internal expect fun testMethodTestStaticMethodLanguage()

interface TestStaticMethodLanguage {
    companion object {
        fun testMethod() = testMethodTestStaticMethodLanguage()
    }

}
