// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from ident_explicit.djinni

package com.dropbox.djinni.test.interop

enum class TESTIDENTENUM {
    SNAKE_ENUM,
    CAPS_ENUM;
    companion object {}
}
