// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from single_language_interfaces.djinni

package com.dropbox.djinni.test.interop


interface UsesSingleLanguageListeners {
    fun callForObjC(l: ObjcOnlyListener)
    fun returnForObjC(): ObjcOnlyListener
    fun callForJava(l: JavaOnlyListener)
    fun returnForJava(): JavaOnlyListener
}
