// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from varnames.djinni

package com.dropbox.djinni.test.interop


interface VarnameInterface {
    fun Rmethod(RArg: VarnameRecord): VarnameRecord
    fun Imethod(IArg: VarnameInterface): VarnameInterface?
}
