// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from wchar_test.djinni

package com.dropbox.djinni.test.interop

internal expect fun getRecordWcharTestHelpers(): WcharTestRec
internal expect fun getStringWcharTestHelpers(): String
internal expect fun checkStringWcharTestHelpers(str: String): Boolean
internal expect fun checkRecordWcharTestHelpers(rec: WcharTestRec): Boolean

interface WcharTestHelpers {
    companion object {
        fun getRecord(): WcharTestRec = getRecordWcharTestHelpers()
        fun getString(): String = getStringWcharTestHelpers()
        fun checkString(str: String): Boolean = checkStringWcharTestHelpers(str)
        fun checkRecord(rec: WcharTestRec): Boolean = checkRecordWcharTestHelpers(rec)
    }

}
