// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort.interop

enum class SortOrder {
    ASCENDING,
    DESCENDING,
    RANDOM;
    companion object {}
}
