// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort.interop

internal expect fun createWithListenerSortItems(listener: TextboxListener): SortItems?
internal expect fun runSortSortItems(items: ItemList): ItemList

interface SortItems {
    companion object {
        fun createWithListener(listener: TextboxListener): SortItems? = createWithListenerSortItems(listener)
        fun runSort(items: ItemList): ItemList = runSortSortItems(items)
    }

    fun sort(
        order: SortOrder,
        items: ItemList
    )
}
