// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort.interop

import TextSort.TXSItemList
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
fun ItemList.toObjc(): TXSItemList {
    return TXSItemList(ArrayList(this.items.map { it }))
}

@OptIn(ExperimentalForeignApi::class)
fun TXSItemList.toKotlin(): ItemList {
    return ItemList(items = this.items.map { it as String })
}
