// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort.interop

import TextSort.TXSSortOrder
import kotlinx.cinterop.ExperimentalForeignApi
import platform.Foundation.NSNumber

@OptIn(ExperimentalForeignApi::class)
fun SortOrder.toObjc(): TXSSortOrder {
    return when(this) {
        SortOrder.ASCENDING -> TextSort.TXSSortOrderAscending
        SortOrder.DESCENDING -> TextSort.TXSSortOrderDescending
        SortOrder.RANDOM -> TextSort.TXSSortOrderRandom
    }
}

@OptIn(ExperimentalForeignApi::class)
fun SortOrder.toNSNumber(): NSNumber {
    return NSNumber(long = toObjc())
}

@OptIn(ExperimentalForeignApi::class)
fun SortOrder.Companion.fromObjc(e: TXSSortOrder): SortOrder {
    return when(e) {
        TextSort.TXSSortOrderAscending -> SortOrder.ASCENDING
        TextSort.TXSSortOrderDescending -> SortOrder.DESCENDING
        TextSort.TXSSortOrderRandom -> SortOrder.RANDOM
         else -> throw IllegalArgumentException("Unknown SortOrder: $e")
    }
}

@OptIn(ExperimentalForeignApi::class)
fun SortOrder.Companion.fromNSNumber(e: NSNumber): SortOrder {
    return fromObjc(e.integerValue)
}
