// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort.interop

import TextSort.TXSSortItems
import kotlinx.cinterop.ExperimentalForeignApi

@OptIn(ExperimentalForeignApi::class)
internal actual fun createWithListenerSortItems(listener: TextboxListener): SortItems? {
    val ret = TXSSortItems.createWithListener(TXSTextboxListenerImpl(listener))
    return ret?.let { SortItemsImpl(it) }
}

@OptIn(ExperimentalForeignApi::class)
internal actual fun runSortSortItems(items: ItemList): ItemList {
    val ret = TXSSortItems.runSort(items.toObjc())
    return ret.toKotlin()
}

@OptIn(ExperimentalForeignApi::class)
class SortItemsImpl(private val sortItems: TXSSortItems): SortItems {
    override fun sort(
        order: SortOrder,
        items: ItemList
    ) {
        sortItems.sort(
            order.toObjc(),
            items.toObjc()
        )
    }
}
