// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort.interop

import TextSort.TXSItemList
import TextSort.TXSTextboxListenerProtocol
import kotlinx.cinterop.ExperimentalForeignApi
import platform.darwin.NSObject

@OptIn(ExperimentalForeignApi::class)
class TXSTextboxListenerImpl(private val textboxListener: TextboxListener): NSObject(), TXSTextboxListenerProtocol {
    override fun update(items: TXSItemList): Unit {
        textboxListener.update(items.toKotlin())
    }
}
