// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

package com.dropbox.djinni.test.interop

fun AccessFlags.toJava(): com.dropbox.djinni.test.AccessFlags {
    return when(this) {
        AccessFlags.NOBODY -> com.dropbox.djinni.test.AccessFlags.NOBODY
        AccessFlags.OWNER_READ -> com.dropbox.djinni.test.AccessFlags.OWNER_READ
        AccessFlags.OWNER_WRITE -> com.dropbox.djinni.test.AccessFlags.OWNER_WRITE
        AccessFlags.OWNER_EXECUTE -> com.dropbox.djinni.test.AccessFlags.OWNER_EXECUTE
        AccessFlags.GROUP_READ -> com.dropbox.djinni.test.AccessFlags.GROUP_READ
        AccessFlags.GROUP_WRITE -> com.dropbox.djinni.test.AccessFlags.GROUP_WRITE
        AccessFlags.GROUP_EXECUTE -> com.dropbox.djinni.test.AccessFlags.GROUP_EXECUTE
        AccessFlags.SYSTEM_READ -> com.dropbox.djinni.test.AccessFlags.SYSTEM_READ
        AccessFlags.SYSTEM_WRITE -> com.dropbox.djinni.test.AccessFlags.SYSTEM_WRITE
        AccessFlags.SYSTEM_EXECUTE -> com.dropbox.djinni.test.AccessFlags.SYSTEM_EXECUTE
        AccessFlags.EVERYBODY -> com.dropbox.djinni.test.AccessFlags.EVERYBODY
    }
}

fun com.dropbox.djinni.test.AccessFlags.toKotlin(): AccessFlags {
    return when(this) {
        com.dropbox.djinni.test.AccessFlags.NOBODY -> AccessFlags.NOBODY
        com.dropbox.djinni.test.AccessFlags.OWNER_READ -> AccessFlags.OWNER_READ
        com.dropbox.djinni.test.AccessFlags.OWNER_WRITE -> AccessFlags.OWNER_WRITE
        com.dropbox.djinni.test.AccessFlags.OWNER_EXECUTE -> AccessFlags.OWNER_EXECUTE
        com.dropbox.djinni.test.AccessFlags.GROUP_READ -> AccessFlags.GROUP_READ
        com.dropbox.djinni.test.AccessFlags.GROUP_WRITE -> AccessFlags.GROUP_WRITE
        com.dropbox.djinni.test.AccessFlags.GROUP_EXECUTE -> AccessFlags.GROUP_EXECUTE
        com.dropbox.djinni.test.AccessFlags.SYSTEM_READ -> AccessFlags.SYSTEM_READ
        com.dropbox.djinni.test.AccessFlags.SYSTEM_WRITE -> AccessFlags.SYSTEM_WRITE
        com.dropbox.djinni.test.AccessFlags.SYSTEM_EXECUTE -> AccessFlags.SYSTEM_EXECUTE
        com.dropbox.djinni.test.AccessFlags.EVERYBODY -> AccessFlags.EVERYBODY
    }
}
