// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primtypes.djinni

package com.dropbox.djinni.test.interop

fun AssortedPrimitives.toJava(): com.dropbox.djinni.test.AssortedPrimitives {
    return com.dropbox.djinni.test.AssortedPrimitives(
        this.b,
        this.eight,
        this.sixteen,
        this.thirtytwo,
        this.sixtyfour,
        this.fthirtytwo,
        this.fsixtyfour,
        this.oB,
        this.oEight,
        this.oSixteen,
        this.oThirtytwo,
        this.oSixtyfour,
        this.oFthirtytwo,
        this.oFsixtyfour
    )
}

fun com.dropbox.djinni.test.AssortedPrimitives.toKotlin(): AssortedPrimitives {
    return AssortedPrimitives(
        b = this.b,
        eight = this.eight,
        sixteen = this.sixteen,
        thirtytwo = this.thirtytwo,
        sixtyfour = this.sixtyfour,
        fthirtytwo = this.fthirtytwo,
        fsixtyfour = this.fsixtyfour,
        oB = this.oB,
        oEight = this.oEight,
        oSixteen = this.oSixteen,
        oThirtytwo = this.oThirtytwo,
        oSixtyfour = this.oSixtyfour,
        oFthirtytwo = this.oFthirtytwo,
        oFsixtyfour = this.oFsixtyfour
    )
}
