// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test.interop

class AsyncInterfaceImpl(private val asyncInterface: AsyncInterface): com.dropbox.djinni.test.AsyncInterface() {
    override fun futureRoundtrip(f: com.snapchat.djinni.Future<Int>): com.snapchat.djinni.Future<String> {
        val ret = asyncInterface.futureRoundtrip (TODO("Map external type: com.safetyculture.djinni.support.Future"))
        return TODO("Map external type: com.safetyculture.djinni.support.Future")
    }
}
