// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test.interop

import kotlinx.io.Buffer

class ClientInterfaceImpl(private val clientInterface: ClientInterface): com.dropbox.djinni.test.ClientInterface() {
    override fun getRecord(
        recordId: Long,
        utf8string: String,
        misc: String?
    ): com.dropbox.djinni.test.ClientReturnedRecord {
        val ret = clientInterface.getRecord (
            recordId,
            utf8string,
            misc
        )
        return ret.toJava()
    }

    override fun identifierCheck(
        data: Buffer,
        r: Int,
        jret: Long
    ): Double {
        val ret = clientInterface.identifierCheck (
            TODO("Map: MBinary"),
            r,
            jret
        )
        return ret
    }

    override fun returnStr(): String {
        val ret = clientInterface.returnStr ()
        return ret
    }

    override fun methTakingInterface(i: com.dropbox.djinni.test.ClientInterface): String {
        val ret = clientInterface.methTakingInterface (throw UnsupportedOperationException("Impossible to map ClientInterface in this direction"))
        return ret
    }

    override fun methTakingOptionalInterface(i: com.dropbox.djinni.test.ClientInterface?): String {
        val ret = clientInterface.methTakingOptionalInterface (throw UnsupportedOperationException("Impossible to map ClientInterface in this direction"))
        return ret
    }
}
