// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test.interop

fun ClientReturnedRecord.toJava(): com.dropbox.djinni.test.ClientReturnedRecord {
    return com.dropbox.djinni.test.ClientReturnedRecord(
        this.recordId,
        this.content,
        this.misc
    )
}

fun com.dropbox.djinni.test.ClientReturnedRecord.toKotlin(): ClientReturnedRecord {
    return ClientReturnedRecord(
        recordId = this.recordId,
        content = this.content,
        misc = this.misc
    )
}
