// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

package com.dropbox.djinni.test.interop

fun Color.toJava(): com.dropbox.djinni.test.Color {
    return when(this) {
        Color.RED -> com.dropbox.djinni.test.Color.RED
        Color.ORANGE -> com.dropbox.djinni.test.Color.ORANGE
        Color.YELLOW -> com.dropbox.djinni.test.Color.YELLOW
        Color.GREEN -> com.dropbox.djinni.test.Color.GREEN
        Color.BLUE -> com.dropbox.djinni.test.Color.BLUE
        Color.INDIGO -> com.dropbox.djinni.test.Color.INDIGO
        Color.VIOLET -> com.dropbox.djinni.test.Color.VIOLET
    }
}

fun com.dropbox.djinni.test.Color.toKotlin(): Color {
    return when(this) {
        com.dropbox.djinni.test.Color.RED -> Color.RED
        com.dropbox.djinni.test.Color.ORANGE -> Color.ORANGE
        com.dropbox.djinni.test.Color.YELLOW -> Color.YELLOW
        com.dropbox.djinni.test.Color.GREEN -> Color.GREEN
        com.dropbox.djinni.test.Color.BLUE -> Color.BLUE
        com.dropbox.djinni.test.Color.INDIGO -> Color.INDIGO
        com.dropbox.djinni.test.Color.VIOLET -> Color.VIOLET
    }
}
