// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test.interop

import java.util.HashSet

class ConflictUserImpl(private val conflictUser: com.dropbox.djinni.test.ConflictUser): ConflictUser {
    override fun Conflict(): Conflict? {
        val ret = conflictUser.Conflict()
        return ret?.let { ConflictImpl(it) }
    }

    override fun conflictArg(cs: Set<Conflict>): Boolean {
        val ret = conflictUser.conflictArg(TODO("Map: MSet<Conflict>"))
        return ret
    }
}
