// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test.interop

class ConflictImpl(private val Conflict: com.dropbox.djinni.test.Conflict): Conflict {
}
