// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

package com.dropbox.djinni.test.interop

fun ConstantEnum.toJava(): com.dropbox.djinni.test.ConstantEnum {
    return when(this) {
        ConstantEnum.SOME_VALUE -> com.dropbox.djinni.test.ConstantEnum.SOME_VALUE
        ConstantEnum.SOME_OTHER_VALUE -> com.dropbox.djinni.test.ConstantEnum.SOME_OTHER_VALUE
    }
}

fun com.dropbox.djinni.test.ConstantEnum.toKotlin(): ConstantEnum {
    return when(this) {
        com.dropbox.djinni.test.ConstantEnum.SOME_VALUE -> ConstantEnum.SOME_VALUE
        com.dropbox.djinni.test.ConstantEnum.SOME_OTHER_VALUE -> ConstantEnum.SOME_OTHER_VALUE
    }
}
