// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

package com.dropbox.djinni.test.interop

class ConstantsInterfaceImpl(private val constantsInterface: com.dropbox.djinni.test.ConstantsInterface): ConstantsInterface {
    override fun dummy() {
        constantsInterface.dummy()
    }
}
