// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

package com.dropbox.djinni.test.interop

fun Constants.toJava(): com.dropbox.djinni.test.Constants {
    return com.dropbox.djinni.test.Constants()
}

fun com.dropbox.djinni.test.Constants.toKotlin(): Constants {
    return Constants()
}
