// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

package com.dropbox.djinni.test.interop

class ConstantInterfaceWithEnumImpl(private val constantInterfaceWithEnum: com.dropbox.djinni.test.ConstantInterfaceWithEnum): ConstantInterfaceWithEnum {
}
