// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

package com.dropbox.djinni.test.interop

fun ConstantRecord.toJava(): com.dropbox.djinni.test.ConstantRecord {
    return com.dropbox.djinni.test.ConstantRecord(
        this.someInteger,
        this.someString
    )
}

fun com.dropbox.djinni.test.ConstantRecord.toKotlin(): ConstantRecord {
    return ConstantRecord(
        someInteger = this.someInteger,
        someString = this.someString
    )
}
