// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

package com.dropbox.djinni.test.interop

fun ConstantWithEnum.toJava(): com.dropbox.djinni.test.ConstantWithEnum {
    return com.dropbox.djinni.test.ConstantWithEnum()
}

fun com.dropbox.djinni.test.ConstantWithEnum.toKotlin(): ConstantWithEnum {
    return ConstantWithEnum()
}
