// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from exception.djinni

package com.dropbox.djinni.test.interop

internal actual fun getCppException(): CppException? {
    val ret = com.dropbox.djinni.test.CppException.get()
    return ret?.let { CppExceptionImpl(it) }
}

class CppExceptionImpl(private val cppException: com.dropbox.djinni.test.CppException): CppException {
    override fun throwAnException(): Int {
        val ret = cppException.throwAnException()
        return ret
    }

    override fun callThrowingInterface(cb: ThrowingInterface): Int {
        val ret = cppException.callThrowingInterface(throw UnsupportedOperationException("Impossible to map ThrowingInterface in this direction"))
        return ret
    }

    override fun callThrowingAndCatch(cb: ThrowingInterface): String {
        val ret = cppException.callThrowingAndCatch(throw UnsupportedOperationException("Impossible to map ThrowingInterface in this direction"))
        return ret
    }
}
