// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from data_ref_view.djinni

package com.dropbox.djinni.test.interop

import kotlinx.io.Buffer

internal actual fun createDataRefTest(): DataRefTest? {
    val ret = com.dropbox.djinni.test.DataRefTest.create()
    return ret?.let { DataRefTestImpl(it) }
}

class DataRefTestImpl(private val DataRefTest: com.dropbox.djinni.test.DataRefTest): DataRefTest {
    override fun sendData(data: com.safetyculture.djinni.support.ByteBuffer) {
        DataRefTest.sendData(TODO("Map external type: com.safetyculture.djinni.support.ByteBuffer"))
    }

    override fun retriveAsBin(): Buffer {
        val ret = DataRefTest.retriveAsBin()
        return TODO("Map: MBinary")
    }

    override fun sendMutableData(data: com.safetyculture.djinni.support.ByteBuffer) {
        DataRefTest.sendMutableData(TODO("Map external type: com.safetyculture.djinni.support.ByteBuffer"))
    }

    override fun generateData(): com.safetyculture.djinni.support.ByteBuffer {
        val ret = DataRefTest.generateData()
        return TODO("Map external type: com.safetyculture.djinni.support.ByteBuffer")
    }

    override fun dataFromVec(): com.safetyculture.djinni.support.ByteBuffer {
        val ret = DataRefTest.dataFromVec()
        return TODO("Map external type: com.safetyculture.djinni.support.ByteBuffer")
    }

    override fun dataFromStr(): com.safetyculture.djinni.support.ByteBuffer {
        val ret = DataRefTest.dataFromStr()
        return TODO("Map external type: com.safetyculture.djinni.support.ByteBuffer")
    }

    override fun sendDataView(data: com.safetyculture.djinni.support.ByteBuffer): Buffer {
        val ret = DataRefTest.sendDataView(TODO("Map external type: com.safetyculture.djinni.support.ByteBuffer"))
        return TODO("Map: MBinary")
    }

    override fun recvDataView(): com.safetyculture.djinni.support.ByteBuffer {
        val ret = DataRefTest.recvDataView()
        return TODO("Map external type: com.safetyculture.djinni.support.ByteBuffer")
    }
}
