// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

package com.dropbox.djinni.test.interop

fun DateRecord.toJava(): com.dropbox.djinni.test.DateRecord {
    return com.dropbox.djinni.test.DateRecord(TODO("Map external type: [unspecified]"))
}

fun com.dropbox.djinni.test.DateRecord.toKotlin(): DateRecord {
    return DateRecord(createdAt = TODO("Map external type: [unspecified]"))
}
