// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test.interop

fun EmptyRecord.toJava(): com.dropbox.djinni.test.EmptyRecord {
    return com.dropbox.djinni.test.EmptyRecord()
}

fun com.dropbox.djinni.test.EmptyRecord.toKotlin(): EmptyRecord {
    return EmptyRecord()
}
