// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

package com.dropbox.djinni.test.interop

fun EmptyFlags.toJava(): com.dropbox.djinni.test.EmptyFlags {
    return when(this) {
        EmptyFlags.NONE -> com.dropbox.djinni.test.EmptyFlags.NONE
        EmptyFlags.ALL -> com.dropbox.djinni.test.EmptyFlags.ALL
    }
}

fun com.dropbox.djinni.test.EmptyFlags.toKotlin(): EmptyFlags {
    return when(this) {
        com.dropbox.djinni.test.EmptyFlags.NONE -> EmptyFlags.NONE
        com.dropbox.djinni.test.EmptyFlags.ALL -> EmptyFlags.ALL
    }
}
