// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

package com.dropbox.djinni.test.interop

import java.util.ArrayList
import java.util.HashMap
import java.util.HashSet

class EnumUsageInterfaceImpl(private val enumUsageInterface: EnumUsageInterface): com.dropbox.djinni.test.EnumUsageInterface() {
    override fun e(e: com.dropbox.djinni.test.Color): com.dropbox.djinni.test.Color {
        val ret = enumUsageInterface.e (e.toKotlin())
        return ret.toJava()
    }

    override fun o(o: com.dropbox.djinni.test.Color?): com.dropbox.djinni.test.Color? {
        val ret = enumUsageInterface.o (o?.toKotlin())
        return ret?.toJava()
    }

    override fun l(l: ArrayList<com.dropbox.djinni.test.Color>): ArrayList<com.dropbox.djinni.test.Color> {
        val ret = enumUsageInterface.l (l.map { it.toKotlin() })
        return ArrayList(ret.map { it.toJava() })
    }

    override fun s(s: Set<Color>): Set<Color> {
        val ret = enumUsageInterface.s (s.map { it.toKotlin() }.toSet())
        return HashSet(ret.map { it.toJava() })
    }

    override fun m(m: HashMap<com.dropbox.djinni.test.Color, com.dropbox.djinni.test.Color>): HashMap<com.dropbox.djinni.test.Color, com.dropbox.djinni.test.Color> {
        val ret = enumUsageInterface.m (m.map { (k, v) -> k.toKotlin() to v.toKotlin() }.toMap())
        return ret.map { (k, v) -> k.toJava() to v.toJava() }.toMap(HashMap())
    }
}
