// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

package com.dropbox.djinni.test.interop

import java.util.ArrayList
import java.util.HashMap
import java.util.HashSet

fun EnumUsageRecord.toJava(): com.dropbox.djinni.test.EnumUsageRecord {
    return com.dropbox.djinni.test.EnumUsageRecord(
        this.e.toJava(),
        this.o?.toJava(),
        ArrayList(this.l.map { it.toJava() }),
        HashSet(this.s.map { it.toJava() }),
        this.m.map { (k, v) -> k.toJava() to v.toJava() }.toMap(HashMap())
    )
}

fun com.dropbox.djinni.test.EnumUsageRecord.toKotlin(): EnumUsageRecord {
    return EnumUsageRecord(
        e = this.e.toKotlin(),
        o = this.o?.toKotlin(),
        l = this.l.map { it.toKotlin() },
        s = this.s.map { it.toKotlin() }.toSet(),
        m = this.m.map { (k, v) -> k.toKotlin() to v.toKotlin() }.toMap()
    )
}
