// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

package com.dropbox.djinni.test.interop

class ExternInterface2Impl(private val externInterface2: ExternInterface2): com.dropbox.djinni.test.ExternInterface2() {
    override fun foo(i: com.dropbox.djinni.test.TestHelpers): com.dropbox.djinni.test.ExternRecordWithDerivings {
        val ret = externInterface2.foo (TODO("Map external type: [unspecified]"))
        return ret.toJava()
    }
}
