// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

package com.dropbox.djinni.test.interop

class ExternInterface1Impl(private val externInterface1: com.dropbox.djinni.test.ExternInterface1): ExternInterface1 {
    override fun foo(i: [unspecified]): [unspecified] {
        val ret = externInterface1.foo(TODO("Map external type: [unspecified]"))
        return TODO("Map external type: [unspecified]")
    }

    override fun bar(e: [unspecified]): [unspecified] {
        val ret = externInterface1.bar(TODO("Map external type: [unspecified]"))
        return TODO("Map external type: [unspecified]")
    }
}
