// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

package com.dropbox.djinni.test.interop

fun ExternRecordWithDerivings.toJava(): com.dropbox.djinni.test.ExternRecordWithDerivings {
    return com.dropbox.djinni.test.ExternRecordWithDerivings(
        TODO("Map external type: [unspecified]"),
        TODO("Map external type: [unspecified]")
    )
}

fun com.dropbox.djinni.test.ExternRecordWithDerivings.toKotlin(): ExternRecordWithDerivings {
    return ExternRecordWithDerivings(
        member = TODO("Map external type: [unspecified]"),
        e = TODO("Map external type: [unspecified]")
    )
}
