// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

package com.dropbox.djinni.test.interop

import java.util.EnumSet

internal actual fun roundtripAccessFlagRoundtrip(flag: AccessFlags): AccessFlags {
    val ret = com.dropbox.djinni.test.FlagRoundtrip.roundtripAccess(flag.toJava())
    return ret.toKotlin()
}

internal actual fun roundtripEmptyFlagRoundtrip(flag: EmptyFlags): EmptyFlags {
    val ret = com.dropbox.djinni.test.FlagRoundtrip.roundtripEmpty(flag.toJava())
    return ret.toKotlin()
}

internal actual fun roundtripAccessBoxedFlagRoundtrip(flag: AccessFlags?): AccessFlags? {
    val ret = com.dropbox.djinni.test.FlagRoundtrip.roundtripAccessBoxed(flag?.toJava())
    return ret?.toKotlin()
}

internal actual fun roundtripEmptyBoxedFlagRoundtrip(flag: EmptyFlags?): EmptyFlags? {
    val ret = com.dropbox.djinni.test.FlagRoundtrip.roundtripEmptyBoxed(flag?.toJava())
    return ret?.toKotlin()
}

class FlagRoundtripImpl(private val flagRoundtrip: com.dropbox.djinni.test.FlagRoundtrip): FlagRoundtrip {
}
