// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from function_prologue.djinni

package com.dropbox.djinni.test.interop

internal actual fun fooFunctionPrologueHelper(): String {
    val ret = com.dropbox.djinni.test.FunctionPrologueHelper.foo()
    return ret
}

class FunctionPrologueHelperImpl(private val FunctionPrologueHelper: com.dropbox.djinni.test.FunctionPrologueHelper): FunctionPrologueHelper {
}
