// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

package com.dropbox.djinni.test.interop

class InterfaceUsingExtendedRecordImpl(private val interfaceUsingExtendedRecord: com.dropbox.djinni.test.InterfaceUsingExtendedRecord): InterfaceUsingExtendedRecord {
    override fun meth(er: ExtendedRecord): ExtendedRecord {
        val ret = interfaceUsingExtendedRecord.meth(er.toJava())
        return ret.toKotlin()
    }
}
