// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from single_language_interfaces.djinni

package com.dropbox.djinni.test.interop

class JavaOnlyListenerImpl(private val javaOnlyListener: JavaOnlyListener): com.dropbox.djinni.test.JavaOnlyListener() {
}
