// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test.interop

internal actual fun initListenerCaller(
    firstL: FirstListener,
    secondL: SecondListener
): ListenerCaller? {
    val ret = com.dropbox.djinni.test.ListenerCaller.init(
        throw UnsupportedOperationException("Impossible to map FirstListener in this direction"),
        throw UnsupportedOperationException("Impossible to map SecondListener in this direction")
    )
    return ret?.let { ListenerCallerImpl(it) }
}

class ListenerCallerImpl(private val listenerCaller: com.dropbox.djinni.test.ListenerCaller): ListenerCaller {
    override fun callFirst() {
        listenerCaller.callFirst()
    }

    override fun callSecond() {
        listenerCaller.callSecond()
    }
}
