// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

package com.dropbox.djinni.test.interop

import java.util.HashMap

fun MapDateRecord.toJava(): com.dropbox.djinni.test.MapDateRecord {
    return com.dropbox.djinni.test.MapDateRecord(this.datesById.mapValues { TODO("Map external type: [unspecified]") }.toMap(HashMap()))
}

fun com.dropbox.djinni.test.MapDateRecord.toKotlin(): MapDateRecord {
    return MapDateRecord(datesById = this.datesById.mapValues { TODO("Map external type: [unspecified]") })
}
