// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

package com.dropbox.djinni.test.interop

import java.util.ArrayList
import java.util.HashMap

fun MapListRecord.toJava(): com.dropbox.djinni.test.MapListRecord {
    return com.dropbox.djinni.test.MapListRecord(ArrayList(this.mapList.map { it.toMap(HashMap()) }))
}

fun com.dropbox.djinni.test.MapListRecord.toKotlin(): MapListRecord {
    return MapListRecord(mapList = this.mapList.map { it.toMap() })
}
