// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

package com.dropbox.djinni.test.interop

import java.util.HashMap

fun MapRecord.toJava(): com.dropbox.djinni.test.MapRecord {
    return com.dropbox.djinni.test.MapRecord(
        this.map.toMap(HashMap()),
        this.imap.toMap(HashMap())
    )
}

fun com.dropbox.djinni.test.MapRecord.toKotlin(): MapRecord {
    return MapRecord(
        map = this.map.toMap(),
        imap = this.imap.toMap()
    )
}
