// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from outcome.djinni

package com.dropbox.djinni.test.interop

fun NestedOutcome.toJava(): com.dropbox.djinni.test.NestedOutcome {
    return com.dropbox.djinni.test.NestedOutcome(TODO("Map external type: com.safetyculture.djinni.support.Outcome"))
}

fun com.dropbox.djinni.test.NestedOutcome.toKotlin(): NestedOutcome {
    return NestedOutcome(o = TODO("Map external type: com.safetyculture.djinni.support.Outcome"))
}
