// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nested_collection.djinni

package com.dropbox.djinni.test.interop

import java.util.ArrayList
import java.util.HashSet

fun NestedCollection.toJava(): com.dropbox.djinni.test.NestedCollection {
    return com.dropbox.djinni.test.NestedCollection(ArrayList(this.setList.map { HashSet(it) }))
}

fun com.dropbox.djinni.test.NestedCollection.toKotlin(): NestedCollection {
    return NestedCollection(setList = this.setList.map { it })
}
