// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primitive_list.djinni

package com.dropbox.djinni.test.interop

import java.util.ArrayList

fun PrimitiveList.toJava(): com.dropbox.djinni.test.PrimitiveList {
    return com.dropbox.djinni.test.PrimitiveList(ArrayList(this.list.map { it }))
}

fun com.dropbox.djinni.test.PrimitiveList.toKotlin(): PrimitiveList {
    return PrimitiveList(list = this.list.map { it })
}
