// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test.interop

import djinni.test.Test.AddressBook
import djinni.test.Test.Person
import djinni.test2.Test2.PersistingState
import java.util.ArrayList

internal actual fun protoToStringsProtoTests(x: TODO("Map: MProtobuf")): List<String> {
    val ret = com.dropbox.djinni.test.ProtoTests.protoToStrings(TODO("Map: MProtobuf"))
    return ret.map { it }
}

internal actual fun stringsToProtoProtoTests(x: List<String>): TODO("Map: MProtobuf") {
    val ret = com.dropbox.djinni.test.ProtoTests.stringsToProto(ArrayList(x.map { it }))
    return TODO("Map: MProtobuf")
}

internal actual fun embeddedProtoToStringProtoTests(x: RecordWithEmbeddedProto): String {
    val ret = com.dropbox.djinni.test.ProtoTests.embeddedProtoToString(x.toJava())
    return ret
}

internal actual fun stringToEmbeddedProtoProtoTests(x: String): RecordWithEmbeddedProto {
    val ret = com.dropbox.djinni.test.ProtoTests.stringToEmbeddedProto(x)
    return ret.toKotlin()
}

internal actual fun cppProtoToStringProtoTests(x: TODO("Map: MProtobuf")): String {
    val ret = com.dropbox.djinni.test.ProtoTests.cppProtoToString(TODO("Map: MProtobuf"))
    return ret
}

internal actual fun stringToCppProtoProtoTests(x: String): TODO("Map: MProtobuf") {
    val ret = com.dropbox.djinni.test.ProtoTests.stringToCppProto(x)
    return TODO("Map: MProtobuf")
}

internal actual fun embeddedCppProtoToStringProtoTests(x: RecordWithEmbeddedCppProto): String {
    val ret = com.dropbox.djinni.test.ProtoTests.embeddedCppProtoToString(x.toJava())
    return ret
}

internal actual fun stringToEmbeddedCppProtoProtoTests(x: String): RecordWithEmbeddedCppProto {
    val ret = com.dropbox.djinni.test.ProtoTests.stringToEmbeddedCppProto(x)
    return ret.toKotlin()
}

internal actual fun protoListToStringsProtoTests(x: List<TODO("Map: MProtobuf")>): List<String> {
    val ret = com.dropbox.djinni.test.ProtoTests.protoListToStrings(ArrayList(x.map { TODO("Map: MProtobuf") }))
    return ret.map { it }
}

internal actual fun stringsToProtoListProtoTests(x: List<String>): List<TODO("Map: MProtobuf")> {
    val ret = com.dropbox.djinni.test.ProtoTests.stringsToProtoList(ArrayList(x.map { it }))
    return ret.map { TODO("Map: MProtobuf") }
}

internal actual fun optionalProtoToStringProtoTests(x: TODO("Map: MProtobuf")?): String {
    val ret = com.dropbox.djinni.test.ProtoTests.optionalProtoToString(TODO("Map: MProtobuf"))
    return ret
}

internal actual fun stringToOptionalProtoProtoTests(x: String): TODO("Map: MProtobuf")? {
    val ret = com.dropbox.djinni.test.ProtoTests.stringToOptionalProto(x)
    return TODO("Map: MProtobuf")
}

internal actual fun stringToProtoOutcomeProtoTests(x: String): com.safetyculture.djinni.support.Outcome {
    val ret = com.dropbox.djinni.test.ProtoTests.stringToProtoOutcome(x)
    return TODO("Map external type: com.safetyculture.djinni.support.Outcome")
}

class ProtoTestsImpl(private val protoTests: com.dropbox.djinni.test.ProtoTests): ProtoTests {
}
