// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

package com.dropbox.djinni.test.interop

fun RecordWithDurationAndDerivings.toJava(): com.dropbox.djinni.test.RecordWithDurationAndDerivings {
    return com.dropbox.djinni.test.RecordWithDurationAndDerivings(TODO("Map external type: [unspecified]"))
}

fun com.dropbox.djinni.test.RecordWithDurationAndDerivings.toKotlin(): RecordWithDurationAndDerivings {
    return RecordWithDurationAndDerivings(dt = TODO("Map external type: [unspecified]"))
}
