// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test.interop

import djinni.test.Test.Person

fun RecordWithEmbeddedProto.toJava(): com.dropbox.djinni.test.RecordWithEmbeddedProto {
    return com.dropbox.djinni.test.RecordWithEmbeddedProto(TODO("Map: MProtobuf"))
}

fun com.dropbox.djinni.test.RecordWithEmbeddedProto.toKotlin(): RecordWithEmbeddedProto {
    return RecordWithEmbeddedProto(person = TODO("Map: MProtobuf"))
}
