// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test.interop

import djinni.test2.Test2.PersistingState

fun RecordWithEmbeddedCppProto.toJava(): com.dropbox.djinni.test.RecordWithEmbeddedCppProto {
    return com.dropbox.djinni.test.RecordWithEmbeddedCppProto(TODO("Map: MProtobuf"))
}

fun com.dropbox.djinni.test.RecordWithEmbeddedCppProto.toKotlin(): RecordWithEmbeddedCppProto {
    return RecordWithEmbeddedCppProto(state = TODO("Map: MProtobuf"))
}
