// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

package com.dropbox.djinni.test.interop

import java.util.Date
import kotlinx.datetime.Instant

fun RecordWithDerivings.toJava(): com.dropbox.djinni.test.RecordWithDerivings {
    return com.dropbox.djinni.test.RecordWithDerivings(
        this.eight,
        this.sixteen,
        this.thirtytwo,
        this.sixtyfour,
        this.fthirtytwo,
        this.fsixtyfour,
        Date(this.d.toEpochMilliseconds()),
        this.s
    )
}

fun com.dropbox.djinni.test.RecordWithDerivings.toKotlin(): RecordWithDerivings {
    return RecordWithDerivings(
        eight = this.eight,
        sixteen = this.sixteen,
        thirtytwo = this.thirtytwo,
        sixtyfour = this.sixtyfour,
        fthirtytwo = this.fthirtytwo,
        fsixtyfour = this.fsixtyfour,
        d = Instant.fromEpochMilliseconds(this.d.time),
        s = this.s
    )
}
