// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

package com.dropbox.djinni.test.interop

fun RecordWithNestedDerivings.toJava(): com.dropbox.djinni.test.RecordWithNestedDerivings {
    return com.dropbox.djinni.test.RecordWithNestedDerivings(
        this.key,
        this.rec.toJava()
    )
}

fun com.dropbox.djinni.test.RecordWithNestedDerivings.toKotlin(): RecordWithNestedDerivings {
    return RecordWithNestedDerivings(
        key = this.key,
        rec = this.rec.toKotlin()
    )
}
