// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

package com.dropbox.djinni.test.interop

import java.util.EnumSet

fun RecordWithFlags.toJava(): com.dropbox.djinni.test.RecordWithFlags {
    return com.dropbox.djinni.test.RecordWithFlags(this.access.toJava())
}

fun com.dropbox.djinni.test.RecordWithFlags.toKotlin(): RecordWithFlags {
    return RecordWithFlags(access = this.access.toKotlin())
}
