// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

package com.dropbox.djinni.test.interop

fun RecordUsingExtendedRecord.toJava(): com.dropbox.djinni.test.RecordUsingExtendedRecord {
    return com.dropbox.djinni.test.RecordUsingExtendedRecord(this.er.toJava())
}

fun com.dropbox.djinni.test.RecordUsingExtendedRecord.toKotlin(): RecordUsingExtendedRecord {
    return RecordUsingExtendedRecord(er = this.er.toKotlin())
}
