// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test.interop

internal actual fun getInstanceReturnOne(): ReturnOne? {
    val ret = com.dropbox.djinni.test.ReturnOne.getInstance()
    return ret?.let { ReturnOneImpl(it) }
}

class ReturnOneImpl(private val returnOne: com.dropbox.djinni.test.ReturnOne): ReturnOne {
    override fun returnOne(): Byte {
        val ret = returnOne.returnOne()
        return ret
    }
}
