// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from multiple_inheritance.djinni

package com.dropbox.djinni.test.interop

internal actual fun getInstanceReturnTwo(): ReturnTwo? {
    val ret = com.dropbox.djinni.test.ReturnTwo.getInstance()
    return ret?.let { ReturnTwoImpl(it) }
}

class ReturnTwoImpl(private val returnTwo: com.dropbox.djinni.test.ReturnTwo): ReturnTwo {
    override fun returnTwo(): Byte {
        val ret = returnTwo.returnTwo()
        return ret
    }
}
