// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test.interop

internal actual fun createReverseClientInterface(): ReverseClientInterface? {
    val ret = com.dropbox.djinni.test.ReverseClientInterface.create()
    return ret?.let { ReverseClientInterfaceImpl(it) }
}

class ReverseClientInterfaceImpl(private val reverseClientInterface: com.dropbox.djinni.test.ReverseClientInterface): ReverseClientInterface {
    override fun returnStr(): String {
        val ret = reverseClientInterface.returnStr()
        return ret
    }

    override fun methTakingInterface(i: ReverseClientInterface): String {
        val ret = reverseClientInterface.methTakingInterface(throw UnsupportedOperationException("Impossible to map ReverseClientInterface in this direction"))
        return ret
    }

    override fun methTakingOptionalInterface(i: ReverseClientInterface?): String {
        val ret = reverseClientInterface.methTakingOptionalInterface(i?.let { throw UnsupportedOperationException("Impossible to map ReverseClientInterface in this direction") })
        return ret
    }
}
