// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test.interop

class SampleInterfaceImpl(private val sampleInterface: com.dropbox.djinni.test.SampleInterface): SampleInterface {
}
