// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from set.djinni

package com.dropbox.djinni.test.interop

import java.util.HashSet

fun SetRecord.toJava(): com.dropbox.djinni.test.SetRecord {
    return com.dropbox.djinni.test.SetRecord(
        HashSet(this.set),
        HashSet(this.iset)
    )
}

fun com.dropbox.djinni.test.SetRecord.toKotlin(): SetRecord {
    return SetRecord(
        set = this.set,
        iset = this.iset
    )
}
