// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nscopying.djinni

package com.dropbox.djinni.test.interop

fun SupportCopying.toJava(): com.dropbox.djinni.test.SupportCopying {
    return com.dropbox.djinni.test.SupportCopying(this.x)
}

fun com.dropbox.djinni.test.SupportCopying.toKotlin(): SupportCopying {
    return SupportCopying(x = this.x)
}
