// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from array.djinni

package com.dropbox.djinni.test.interop

internal actual fun testStringArrayTestArray(a: TODO("Map: MArray<String>")<String>): TODO("Map: MArray<String>")<String> {
    val ret = com.dropbox.djinni.test.TestArray.testStringArray(TODO("Map: MArray<String>"))
    return TODO("Map: MArray<String>")
}

internal actual fun testIntArrayTestArray(a: TODO("Map: MArray<Int>")<Int>): TODO("Map: MArray<Int>")<Int> {
    val ret = com.dropbox.djinni.test.TestArray.testIntArray(TODO("Map: MArray<Int>"))
    return TODO("Map: MArray<Int>")
}

internal actual fun testRecordArrayTestArray(a: TODO("Map: MArray<Vec2>")<Vec2>): TODO("Map: MArray<Vec2>")<Vec2> {
    val ret = com.dropbox.djinni.test.TestArray.testRecordArray(TODO("Map: MArray<Vec2>"))
    return TODO("Map: MArray<Vec2>")
}

internal actual fun testArrayOfArrayTestArray(a: TODO("Map: MArray<TODO("Map: MArray<Int>")<Int>>")<TODO("Map: MArray<Int>")<Int>>): TODO("Map: MArray<TODO("Map: MArray<Int>")<Int>>")<TODO("Map: MArray<Int>")<Int>> {
    val ret = com.dropbox.djinni.test.TestArray.testArrayOfArray(TODO("Map: MArray<TODO("Map: MArray<Int>")<Int>>"))
    return TODO("Map: MArray<TODO("Map: MArray<Int>")<Int>>")
}

class TestArrayImpl(private val testArray: com.dropbox.djinni.test.TestArray): TestArray {
}
