// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from outcome.djinni

package com.dropbox.djinni.test.interop

internal actual fun getSuccessOutcomeTestOutcome(): com.safetyculture.djinni.support.Outcome {
    val ret = com.dropbox.djinni.test.TestOutcome.getSuccessOutcome()
    return TODO("Map external type: com.safetyculture.djinni.support.Outcome")
}

internal actual fun getErrorOutcomeTestOutcome(): com.safetyculture.djinni.support.Outcome {
    val ret = com.dropbox.djinni.test.TestOutcome.getErrorOutcome()
    return TODO("Map external type: com.safetyculture.djinni.support.Outcome")
}

internal actual fun putSuccessOutcomeTestOutcome(x: com.safetyculture.djinni.support.Outcome): String {
    val ret = com.dropbox.djinni.test.TestOutcome.putSuccessOutcome(TODO("Map external type: com.safetyculture.djinni.support.Outcome"))
    return ret
}

internal actual fun putErrorOutcomeTestOutcome(x: com.safetyculture.djinni.support.Outcome): Int {
    val ret = com.dropbox.djinni.test.TestOutcome.putErrorOutcome(TODO("Map external type: com.safetyculture.djinni.support.Outcome"))
    return ret
}

internal actual fun getNestedSuccessOutcomeTestOutcome(): NestedOutcome {
    val ret = com.dropbox.djinni.test.TestOutcome.getNestedSuccessOutcome()
    return ret.toKotlin()
}

internal actual fun getNestedErrorOutcomeTestOutcome(): NestedOutcome {
    val ret = com.dropbox.djinni.test.TestOutcome.getNestedErrorOutcome()
    return ret.toKotlin()
}

internal actual fun putNestedSuccessOutcomeTestOutcome(x: NestedOutcome): Int {
    val ret = com.dropbox.djinni.test.TestOutcome.putNestedSuccessOutcome(x.toJava())
    return ret
}

internal actual fun putNestedErrorOutcomeTestOutcome(x: NestedOutcome): String {
    val ret = com.dropbox.djinni.test.TestOutcome.putNestedErrorOutcome(x.toJava())
    return ret
}

class TestOutcomeImpl(private val testOutcome: com.dropbox.djinni.test.TestOutcome): TestOutcome {
}
