// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test.interop

import java.util.ArrayList
import java.util.HashMap
import java.util.HashSet
import kotlinx.io.Buffer

internal actual fun getSetRecordTestHelpers(): SetRecord {
    val ret = com.dropbox.djinni.test.TestHelpers.getSetRecord()
    return ret.toKotlin()
}

internal actual fun checkSetRecordTestHelpers(rec: SetRecord): Boolean {
    val ret = com.dropbox.djinni.test.TestHelpers.checkSetRecord(rec.toJava())
    return ret
}

internal actual fun getPrimitiveListTestHelpers(): PrimitiveList {
    val ret = com.dropbox.djinni.test.TestHelpers.getPrimitiveList()
    return ret.toKotlin()
}

internal actual fun checkPrimitiveListTestHelpers(pl: PrimitiveList): Boolean {
    val ret = com.dropbox.djinni.test.TestHelpers.checkPrimitiveList(pl.toJava())
    return ret
}

internal actual fun getNestedCollectionTestHelpers(): NestedCollection {
    val ret = com.dropbox.djinni.test.TestHelpers.getNestedCollection()
    return ret.toKotlin()
}

internal actual fun checkNestedCollectionTestHelpers(nc: NestedCollection): Boolean {
    val ret = com.dropbox.djinni.test.TestHelpers.checkNestedCollection(nc.toJava())
    return ret
}

internal actual fun getMapTestHelpers(): Map<String, Long> {
    val ret = com.dropbox.djinni.test.TestHelpers.getMap()
    return ret.toMap()
}

internal actual fun checkMapTestHelpers(m: Map<String, Long>): Boolean {
    val ret = com.dropbox.djinni.test.TestHelpers.checkMap(m.toMap(HashMap()))
    return ret
}

internal actual fun getEmptyMapTestHelpers(): Map<String, Long> {
    val ret = com.dropbox.djinni.test.TestHelpers.getEmptyMap()
    return ret.toMap()
}

internal actual fun checkEmptyMapTestHelpers(m: Map<String, Long>): Boolean {
    val ret = com.dropbox.djinni.test.TestHelpers.checkEmptyMap(m.toMap(HashMap()))
    return ret
}

internal actual fun getMapListRecordTestHelpers(): MapListRecord {
    val ret = com.dropbox.djinni.test.TestHelpers.getMapListRecord()
    return ret.toKotlin()
}

internal actual fun checkMapListRecordTestHelpers(m: MapListRecord): Boolean {
    val ret = com.dropbox.djinni.test.TestHelpers.checkMapListRecord(m.toJava())
    return ret
}

internal actual fun checkClientInterfaceAsciiTestHelpers(i: ClientInterface) {
    com.dropbox.djinni.test.TestHelpers.checkClientInterfaceAscii(ClientInterfaceImpl(i))
}

internal actual fun checkClientInterfaceNonasciiTestHelpers(i: ClientInterface) {
    com.dropbox.djinni.test.TestHelpers.checkClientInterfaceNonascii(ClientInterfaceImpl(i))
}

internal actual fun checkClientInterfaceArgsTestHelpers(i: ClientInterface) {
    com.dropbox.djinni.test.TestHelpers.checkClientInterfaceArgs(ClientInterfaceImpl(i))
}

internal actual fun checkEnumMapTestHelpers(m: Map<Color, String>) {
    com.dropbox.djinni.test.TestHelpers.checkEnumMap(m.map { (k, v) -> k.toJava() to v }.toMap(HashMap()))
}

internal actual fun checkEnumTestHelpers(c: Color) {
    com.dropbox.djinni.test.TestHelpers.checkEnum(c.toJava())
}

internal actual fun tokenIdTestHelpers(t: UserToken?): UserToken? {
    val ret = com.dropbox.djinni.test.TestHelpers.tokenId(t?.let { UserTokenImpl(it) })
    return ret?.let { UserTokenImpl(it) }
}

internal actual fun createCppTokenTestHelpers(): UserToken? {
    val ret = com.dropbox.djinni.test.TestHelpers.createCppToken()
    return ret?.let { UserTokenImpl(it) }
}

internal actual fun checkCppTokenTestHelpers(t: UserToken) {
    com.dropbox.djinni.test.TestHelpers.checkCppToken(UserTokenImpl(t))
}

internal actual fun cppTokenIdTestHelpers(t: UserToken): Long {
    val ret = com.dropbox.djinni.test.TestHelpers.cppTokenId(UserTokenImpl(t))
    return ret
}

internal actual fun checkTokenTypeTestHelpers(
    t: UserToken,
    type: String
) {
    com.dropbox.djinni.test.TestHelpers.checkTokenType(
        UserTokenImpl(t),
        type
    )
}

internal actual fun returnNoneTestHelpers(): Int? {
    val ret = com.dropbox.djinni.test.TestHelpers.returnNone()
    return ret
}

internal actual fun assortedPrimitivesIdTestHelpers(i: AssortedPrimitives): AssortedPrimitives {
    val ret = com.dropbox.djinni.test.TestHelpers.assortedPrimitivesId(i.toJava())
    return ret.toKotlin()
}

internal actual fun idBinaryTestHelpers(b: Buffer): Buffer {
    val ret = com.dropbox.djinni.test.TestHelpers.idBinary(TODO("Map: MBinary"))
    return TODO("Map: MBinary")
}

internal actual fun getAsyncResultTestHelpers(): com.safetyculture.djinni.support.Future {
    val ret = com.dropbox.djinni.test.TestHelpers.getAsyncResult()
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

internal actual fun futureRoundtripTestHelpers(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future {
    val ret = com.dropbox.djinni.test.TestHelpers.futureRoundtrip(TODO("Map external type: com.safetyculture.djinni.support.Future"))
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

internal actual fun asyncEarlyThrowTestHelpers(): com.safetyculture.djinni.support.Future {
    val ret = com.dropbox.djinni.test.TestHelpers.asyncEarlyThrow()
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

internal actual fun voidAsyncMethodTestHelpers(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future {
    val ret = com.dropbox.djinni.test.TestHelpers.voidAsyncMethod(TODO("Map external type: com.safetyculture.djinni.support.Future"))
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

internal actual fun addOneIfPresentTestHelpers(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future {
    val ret = com.dropbox.djinni.test.TestHelpers.addOneIfPresent(TODO("Map external type: com.safetyculture.djinni.support.Future"))
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

internal actual fun returnExceptionStringTestHelpers(f: com.safetyculture.djinni.support.Future): com.safetyculture.djinni.support.Future {
    val ret = com.dropbox.djinni.test.TestHelpers.returnExceptionString(TODO("Map external type: com.safetyculture.djinni.support.Future"))
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

internal actual fun checkAsyncInterfaceTestHelpers(i: AsyncInterface): com.safetyculture.djinni.support.Future {
    val ret = com.dropbox.djinni.test.TestHelpers.checkAsyncInterface(AsyncInterfaceImpl(i))
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

internal actual fun checkAsyncCompositionTestHelpers(i: AsyncInterface): com.safetyculture.djinni.support.Future {
    val ret = com.dropbox.djinni.test.TestHelpers.checkAsyncComposition(AsyncInterfaceImpl(i))
    return TODO("Map external type: com.safetyculture.djinni.support.Future")
}

internal actual fun getOptionalListTestHelpers(): List<String?> {
    val ret = com.dropbox.djinni.test.TestHelpers.getOptionalList()
    return ret.map { it }
}

internal actual fun checkOptionalListTestHelpers(ol: List<String?>): Boolean {
    val ret = com.dropbox.djinni.test.TestHelpers.checkOptionalList(ArrayList(ol.map { it }))
    return ret
}

internal actual fun getOptionalSetTestHelpers(): Set<String?> {
    val ret = com.dropbox.djinni.test.TestHelpers.getOptionalSet()
    return TODO("Map: MSet<String?>")
}

internal actual fun checkOptionalSetTestHelpers(os: Set<String?>): Boolean {
    val ret = com.dropbox.djinni.test.TestHelpers.checkOptionalSet(TODO("Map: MSet<String?>"))
    return ret
}

internal actual fun getOptionalMapTestHelpers(): Map<String?, String?> {
    val ret = com.dropbox.djinni.test.TestHelpers.getOptionalMap()
    return ret.map { (k, v) -> k to v }.toMap()
}

internal actual fun checkOptionalMapTestHelpers(om: Map<String?, String?>): Boolean {
    val ret = com.dropbox.djinni.test.TestHelpers.checkOptionalMap(om.map { (k, v) -> k to v }.toMap(HashMap()))
    return ret
}

class TestHelpersImpl(private val testHelpers: com.dropbox.djinni.test.TestHelpers): TestHelpers {
}
