// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

package com.dropbox.djinni.test.interop

internal actual fun hoursStringTestDuration(dt: [unspecified]): String {
    val ret = com.dropbox.djinni.test.TestDuration.hoursString(TODO("Map external type: [unspecified]"))
    return ret
}

internal actual fun minutesStringTestDuration(dt: [unspecified]): String {
    val ret = com.dropbox.djinni.test.TestDuration.minutesString(TODO("Map external type: [unspecified]"))
    return ret
}

internal actual fun secondsStringTestDuration(dt: [unspecified]): String {
    val ret = com.dropbox.djinni.test.TestDuration.secondsString(TODO("Map external type: [unspecified]"))
    return ret
}

internal actual fun millisStringTestDuration(dt: [unspecified]): String {
    val ret = com.dropbox.djinni.test.TestDuration.millisString(TODO("Map external type: [unspecified]"))
    return ret
}

internal actual fun microsStringTestDuration(dt: [unspecified]): String {
    val ret = com.dropbox.djinni.test.TestDuration.microsString(TODO("Map external type: [unspecified]"))
    return ret
}

internal actual fun nanosStringTestDuration(dt: [unspecified]): String {
    val ret = com.dropbox.djinni.test.TestDuration.nanosString(TODO("Map external type: [unspecified]"))
    return ret
}

internal actual fun hoursTestDuration(count: Int): [unspecified] {
    val ret = com.dropbox.djinni.test.TestDuration.hours(count)
    return TODO("Map external type: [unspecified]")
}

internal actual fun minutesTestDuration(count: Int): [unspecified] {
    val ret = com.dropbox.djinni.test.TestDuration.minutes(count)
    return TODO("Map external type: [unspecified]")
}

internal actual fun secondsTestDuration(count: Int): [unspecified] {
    val ret = com.dropbox.djinni.test.TestDuration.seconds(count)
    return TODO("Map external type: [unspecified]")
}

internal actual fun millisTestDuration(count: Int): [unspecified] {
    val ret = com.dropbox.djinni.test.TestDuration.millis(count)
    return TODO("Map external type: [unspecified]")
}

internal actual fun microsTestDuration(count: Int): [unspecified] {
    val ret = com.dropbox.djinni.test.TestDuration.micros(count)
    return TODO("Map external type: [unspecified]")
}

internal actual fun nanosTestDuration(count: Int): [unspecified] {
    val ret = com.dropbox.djinni.test.TestDuration.nanos(count)
    return TODO("Map external type: [unspecified]")
}

internal actual fun hoursfTestDuration(count: Double): [unspecified] {
    val ret = com.dropbox.djinni.test.TestDuration.hoursf(count)
    return TODO("Map external type: [unspecified]")
}

internal actual fun minutesfTestDuration(count: Double): [unspecified] {
    val ret = com.dropbox.djinni.test.TestDuration.minutesf(count)
    return TODO("Map external type: [unspecified]")
}

internal actual fun secondsfTestDuration(count: Double): [unspecified] {
    val ret = com.dropbox.djinni.test.TestDuration.secondsf(count)
    return TODO("Map external type: [unspecified]")
}

internal actual fun millisfTestDuration(count: Double): [unspecified] {
    val ret = com.dropbox.djinni.test.TestDuration.millisf(count)
    return TODO("Map external type: [unspecified]")
}

internal actual fun microsfTestDuration(count: Double): [unspecified] {
    val ret = com.dropbox.djinni.test.TestDuration.microsf(count)
    return TODO("Map external type: [unspecified]")
}

internal actual fun nanosfTestDuration(count: Double): [unspecified] {
    val ret = com.dropbox.djinni.test.TestDuration.nanosf(count)
    return TODO("Map external type: [unspecified]")
}

internal actual fun boxTestDuration(count: Long): [unspecified]? {
    val ret = com.dropbox.djinni.test.TestDuration.box(count)
    return ret?.let { TODO("Map external type: [unspecified]") }
}

internal actual fun unboxTestDuration(dt: [unspecified]?): Long {
    val ret = com.dropbox.djinni.test.TestDuration.unbox(dt?.let { TODO("Map external type: [unspecified]") })
    return ret
}

class TestDurationImpl(private val testDuration: com.dropbox.djinni.test.TestDuration): TestDuration {
}
