// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from interface_and_abstract_class.djinni

package com.dropbox.djinni.test.interop

class TestJavaInterfaceOnlyImpl(private val testJavaInterfaceOnly: TestJavaInterfaceOnly): com.dropbox.djinni.test.TestJavaInterfaceOnly() {
    override fun testMethod(): Boolean {
        val ret = testJavaInterfaceOnly.testMethod ()
        return ret
    }
}
