// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from ident_explicit.djinni

package com.dropbox.djinni.test.interop

fun TESTIDENTENUM.toJava(): com.dropbox.djinni.test.NativeTestIdentEnum {
    return when(this) {
        TESTIDENTENUM.SNAKE_ENUM -> com.dropbox.djinni.test.NativeTestIdentEnum.SNAKE_ENUM
        TESTIDENTENUM.CAPS_ENUM -> com.dropbox.djinni.test.NativeTestIdentEnum.CAPS_ENUM
    }
}

fun com.dropbox.djinni.test.NativeTestIdentEnum.toKotlin(): TESTIDENTENUM {
    return when(this) {
        com.dropbox.djinni.test.NativeTestIdentEnum.SNAKE_ENUM -> TESTIDENTENUM.SNAKE_ENUM
        com.dropbox.djinni.test.NativeTestIdentEnum.CAPS_ENUM -> TESTIDENTENUM.CAPS_ENUM
    }
}
