// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from ident_explicit.djinni

package com.dropbox.djinni.test.interop

fun TestIdentRecord.toJava(): com.dropbox.djinni.test.NativeTestIdentRecord {
    return com.dropbox.djinni.test.NativeTestIdentRecord(
        this.FirstValue,
        this.secondValue
    )
}

fun com.dropbox.djinni.test.NativeTestIdentRecord.toKotlin(): TestIdentRecord {
    return TestIdentRecord(
        FirstValue = this.FirstValue,
        secondValue = this.secondValue
    )
}
