// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from static_method_language.djinni

package com.dropbox.djinni.test.interop

internal actual fun testMethodTestStaticMethodLanguage() {
    com.dropbox.djinni.test.TestStaticMethodLanguage.testMethod()
}

class TestStaticMethodLanguageImpl(private val testStaticMethodLanguage: com.dropbox.djinni.test.TestStaticMethodLanguage): TestStaticMethodLanguage {
}
