// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

package com.dropbox.djinni.test.interop

fun TestOptionalExternInterfaceRecord.toJava(): com.dropbox.djinni.test.TestOptionalExternInterfaceRecord {
    return com.dropbox.djinni.test.TestOptionalExternInterfaceRecord(this.sampleInterface?.let { TODO("Map external type: [unspecified]") })
}

fun com.dropbox.djinni.test.TestOptionalExternInterfaceRecord.toKotlin(): TestOptionalExternInterfaceRecord {
    return TestOptionalExternInterfaceRecord(sampleInterface = this.sampleInterface?.let { TODO("Map external type: [unspecified]") })
}
