// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from interface_and_abstract_class.djinni

package com.dropbox.djinni.test.interop

internal actual fun testMethodTestJavaAbstractClassOnly(): Boolean {
    val ret = com.dropbox.djinni.test.TestJavaAbstractClassOnly.testMethod()
    return ret
}

class TestJavaAbstractClassOnlyImpl(private val testJavaAbstractClassOnly: com.dropbox.djinni.test.TestJavaAbstractClassOnly): TestJavaAbstractClassOnly {
}
