// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from user_token.djinni

package com.dropbox.djinni.test.interop

class UserTokenImpl(private val userToken: UserToken): com.dropbox.djinni.test.UserToken() {
    override fun whoami(): String {
        val ret = userToken.whoami ()
        return ret
    }
}
