// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from single_language_interfaces.djinni

package com.dropbox.djinni.test.interop

class UsesSingleLanguageListenersImpl(private val usesSingleLanguageListeners: UsesSingleLanguageListeners): com.dropbox.djinni.test.UsesSingleLanguageListeners() {
    override fun callForObjC(l: com.dropbox.djinni.test.ObjcOnlyListener) {
        usesSingleLanguageListeners.callForObjC (throw UnsupportedOperationException("Impossible to map ObjcOnlyListener in this direction"))
    }

    override fun returnForObjC(): com.dropbox.djinni.test.ObjcOnlyListener {
        val ret = usesSingleLanguageListeners.returnForObjC ()
        return throw UnsupportedOperationException("Impossible to map ObjcOnlyListener in this direction")
    }

    override fun callForJava(l: com.dropbox.djinni.test.JavaOnlyListener) {
        usesSingleLanguageListeners.callForJava (throw UnsupportedOperationException("Impossible to map JavaOnlyListener in this direction"))
    }

    override fun returnForJava(): com.dropbox.djinni.test.JavaOnlyListener {
        val ret = usesSingleLanguageListeners.returnForJava ()
        return JavaOnlyListenerImpl(ret)
    }
}
