// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from varnames.djinni

package com.dropbox.djinni.test.interop

fun VarnameRecord.toJava(): com.dropbox.djinni.test.VarnameRecord {
    return com.dropbox.djinni.test.VarnameRecord(this.Field)
}

fun com.dropbox.djinni.test.VarnameRecord.toKotlin(): VarnameRecord {
    return VarnameRecord(Field = this.Field)
}
