// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from varnames.djinni

package com.dropbox.djinni.test.interop

class VarnameInterfaceImpl(private val VarnameInterface: com.dropbox.djinni.test.VarnameInterface): VarnameInterface {
    override fun Rmethod(RArg: VarnameRecord): VarnameRecord {
        val ret = VarnameInterface.Rmethod(RArg.toJava())
        return ret.toKotlin()
    }

    override fun Imethod(IArg: VarnameInterface): VarnameInterface? {
        val ret = VarnameInterface.Imethod(throw UnsupportedOperationException("Impossible to map VarnameInterface in this direction"))
        return ret?.let { VarnameInterfaceImpl(it) }
    }
}
