// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from array.djinni

package com.dropbox.djinni.test.interop

fun Vec2.toJava(): com.dropbox.djinni.test.Vec2 {
    return com.dropbox.djinni.test.Vec2(
        this.x,
        this.y
    )
}

fun com.dropbox.djinni.test.Vec2.toKotlin(): Vec2 {
    return Vec2(
        x = this.x,
        y = this.y
    )
}
