// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from wchar_test.djinni

package com.dropbox.djinni.test.interop

fun WcharTestRec.toJava(): com.dropbox.djinni.test.WcharTestRec {
    return com.dropbox.djinni.test.WcharTestRec(this.s)
}

fun com.dropbox.djinni.test.WcharTestRec.toKotlin(): WcharTestRec {
    return WcharTestRec(s = this.s)
}
