// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from wchar_test.djinni

package com.dropbox.djinni.test.interop

internal actual fun getRecordWcharTestHelpers(): WcharTestRec {
    val ret = com.dropbox.djinni.test.WcharTestHelpers.getRecord()
    return ret.toKotlin()
}

internal actual fun getStringWcharTestHelpers(): String {
    val ret = com.dropbox.djinni.test.WcharTestHelpers.getString()
    return ret
}

internal actual fun checkStringWcharTestHelpers(str: String): Boolean {
    val ret = com.dropbox.djinni.test.WcharTestHelpers.checkString(str)
    return ret
}

internal actual fun checkRecordWcharTestHelpers(rec: WcharTestRec): Boolean {
    val ret = com.dropbox.djinni.test.WcharTestHelpers.checkRecord(rec.toJava())
    return ret
}

class WcharTestHelpersImpl(private val wcharTestHelpers: com.dropbox.djinni.test.WcharTestHelpers): WcharTestHelpers {
}
