// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

#import "DBClientReturnedRecord.h"


@implementation DBClientReturnedRecord

- (nonnull instancetype)initWithRecordId:(int64_t)recordID
                                 content:(nonnull NSString *)content
                                    misc:(nullable NSString *)misc
{
    if (self = [super init]) {
        _recordID = recordID;
        _content = [content copy];
        _misc = [misc copy];
    }
    return self;
}

+ (nonnull instancetype)clientReturnedRecordWithRecordId:(int64_t)recordID
                                                 content:(nonnull NSString *)content
                                                    misc:(nullable NSString *)misc
{
    return [[self alloc] initWithRecordId:recordID
                                  content:content
                                     misc:misc];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p recordID:%@ content:%@ misc:%@>", self.class, (void *)self, @(self.recordID), self.content, self.misc];
}

#endif
@end
