// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

#import "DBMapDateRecord.h"


@implementation DBMapDateRecord

- (nonnull instancetype)initWithDatesById:(nonnull NSDictionary<NSString *, NSDate *> *)datesByID
{
    if (self = [super init]) {
        _datesByID = [datesByID copy];
    }
    return self;
}

+ (nonnull instancetype)mapDateRecordWithDatesById:(nonnull NSDictionary<NSString *, NSDate *> *)datesByID
{
    return [[self alloc] initWithDatesById:datesByID];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p datesByID:%@>", self.class, (void *)self, self.datesByID];
}

#endif
@end
