package djinni

import ast.{Doc, Ident, Interface, Record, TypeParam, TypeRef}
import generatorTools.{ImportRef, SkipFirst, Spec}
import meta.{MDef, MExpr, Meta}
import writer.IndentWriter

import java.io.File
import scala.collection.mutable

class KMPAndroidGenerator(spec: Spec) extends Generator(spec) {
  private val kotlinMarshal = new KotlinMarshal(spec)
  private val javaMarshal = new JavaMarshal(spec)

  private val javaMapper = new KMPAndroidJavaMapper(javaMarshal, spec)
  private val kotlinMapper = new KMPAndroidKotlinMapper(kotlinMarshal, spec)

  private val utils = new KMPUtils(spec)

  // create androidMain directory
  // create class path folder based on the contents of spec.kotlinPackage
  // e.g. 'com.safetyculture.djinni.test.bridge' -> /com/safetyculture/djinni/test/bridge
  private val androidMainOut = {
    val baseDir = new File(spec.kotlinOutFolder.get, "androidMain/kotlin")
    spec.kotlinPackage match {
      case Some(pkg) =>
        val packagePath = pkg.replace('.', File.separatorChar)
        val targetDir = new File(baseDir, packagePath)
        if (!targetDir.exists()) {
          targetDir.mkdirs()
        }
        targetDir
      case None =>
        if (!baseDir.exists()) {
          baseDir.mkdirs()
        }
        baseDir
    }
  }

  /* helper class which assembles set of required imports for types used within a generated files */
  private class KMPAndroidRefs() {
    var kotlin: mutable.Set[String] = mutable.TreeSet[String]()
    var java: mutable.Set[String] = mutable.TreeSet[String]()

    def find(ty: TypeRef): Unit = {
      find(ty.resolved)
    }

    def find(tm: MExpr): Unit = {
      tm.args.foreach(find)
      find(tm.base)
    }

    def find(m: Meta): Unit = {
      for (r <- kotlinMarshal.references(m)) r match {
        case ImportRef(arg) => kotlin.add(arg)
        case _ =>
      }
      for (r <- javaMarshal.references(m)) r match {
        case ImportRef(arg) => java.add(arg)
        case _ =>
      }
    }
  }

  def writeKotlinFile(ident: String, origin: String, refs: Iterable[String], f: IndentWriter => Unit) {
    createFile(androidMainOut, idKotlin.ty(ident) + ".kt", (w: IndentWriter) => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      w.wl
      spec.kotlinPackage.foreach(s => w.wl(s"package $s").wl)
      if (refs.nonEmpty) {
        refs.foreach(s => w.wl(s"import $s"))
        w.wl
      }
      f(w)
    })
  }

  override def generateInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface): Unit = {
    if(i.ext.java) {
      generateJavaInterface(origin, ident, doc, typeParams, i)
    } else if(i.ext.cpp) {
      generateCppInterface(origin, ident, doc, typeParams, i)
    }
  }

  def generateCppInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface): Unit = {
    val refs = new KMPAndroidRefs()

    // filter for supported methods
    val interfaceMethods = utils.supportedMethods(i)

    // find any required imports for all method parameters / return types
    interfaceMethods.foreach(m => {
      m.params.foreach(p => refs.find(p.ty))
      m.ret.foreach(refs.find)
    })

    // find any required imports for constant types
    i.consts.foreach(c => {
      refs.find(c.ty)
    })

    writeKotlinFile(ident.name, origin, refs.kotlin ++ refs.java, w => {
      val commonInterfaceType = idKotlin.ty(ident.name)
      val javaInterfaceLocal = idKotlin.local(ident.name)
      val javaInterfaceType = javaMarshal.fqTypename(ident, i)

      // wrap the java generated interface in a class which conforms to the generated commonMain interface.
      w.w(s"class ${commonInterfaceType}Impl(private val $javaInterfaceLocal: $javaInterfaceType): $commonInterfaceType").braced {
        val skipFirst = SkipFirst()
        for (m <- interfaceMethods) {
          skipFirst { w.wl }

          /* method implementation:
           * override fun method( $commonMainParams ): $commonMainReturn {
           *   val ret = $javaInterfaceLocal.$javaMethod(
           *     javaMapper.map($commonMainParam),
           *     ...
           *   )
           *   return kotlinMapper.map(ret)
           * }
           */

          val commonMainMethod = idKotlin.method(m.ident)

          w.w(s"override fun $commonMainMethod").parens(m.params) { p =>
            val paramName = idKotlin.local(p.ident)
            val paramType = kotlinMarshal.paramType(p.ty)
            w.w(s"$paramName: $paramType")
          }

          m.ret.map { ty =>
            val commonReturnType = ty.resolved.base match {
              case MDef(_, _, _, i: Interface) if i.ext.cpp => kotlinMarshal.returnType(m.ret) + "?"
              case _ => kotlinMarshal.returnType(m.ret)
            }
            w.w(s": $commonReturnType")
          }

          w.braced {
            /* store return value if any */
            if(m.ret.nonEmpty) w.w(s"val ret = ")

            /* kotlin likes us to use it's synthesized property accessors */
            kotlinMarshal.synthesisedJavaProperty(m).map { javaProperty =>
              w.w(s"$javaInterfaceLocal.$javaProperty")
            }.getOrElse {
              val javaMethod = idJava.method(m.ident)
              w.w(s"$javaInterfaceLocal.$javaMethod").parens(m.params) { p =>
                val paramName = idKotlin.local(p.ident)
                w.w(s"${javaMapper.map(paramName, p.ty.resolved)}")
              }
            }

            w.wl

            // if m.ret isn't empty then write output of retToKotlin
            m.ret.map { ty =>
              w.wl(s"return ${kotlinMapper.map("ret", ty.resolved)}")
            }
          }
        }
      }
    })

  }

  def generateJavaInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface): Unit = {
    val refs = new KMPAndroidRefs()

    // filter for supported methods
    val interfaceMethods = utils.supportedMethods(i)

    // find any required imports for all method parameters / return types
    interfaceMethods.foreach(m => {
      m.params.foreach(p => refs.find(p.ty))
      m.ret.foreach(refs.find)
    })

    // find any required imports for constant types
    i.consts.foreach(c => {
      refs.find(c.ty)
    })

    writeKotlinFile(ident.name, origin, refs.kotlin ++ refs.java, w => {
      val commonInterfaceType = idKotlin.ty(ident.name)
      val commonInterfaceLocal = idKotlin.local(ident.name)
      val javaInterfaceType = javaMarshal.fqTypename(ident, i)

      w.w(s"class ${commonInterfaceType}Impl(private val $commonInterfaceLocal: $commonInterfaceType): $javaInterfaceType()").braced {
        val skipFirst = SkipFirst()
        for (m <- interfaceMethods) {
          skipFirst { w.wl }

          /* method implementation:
           * override fun $javaMethod( $javaParams ): $javaReturnType {
           *   val ret = $commonInterfaceLocal.$commonInterfaceMethod(
           *     kotlinMapper.map($paramName),
           *     ...
           *   )
           *   return javaMapper.map(ret)
           * }
           */

          val javaMethod = idJava.method(m.ident)
          val commonInterfaceMethod = idKotlin.method(m.ident)

          w.w(s"override fun $javaMethod").parens(m.params) { p =>
            val paramName = idJava.local(p.ident)
            val paramType = kotlinMarshal.javaInteropType(p.ty.resolved)
            w.w(s"$paramName: $paramType")
          }

          m.ret.map { ty =>
            val javaReturnType = kotlinMarshal.javaInteropReturnType(m.ret)
            w.w(s": $javaReturnType")
          }

          w.braced {
            /* store return value if any */
            if(m.ret.nonEmpty) w.w(s"val ret = ")

            w.w(s"$commonInterfaceLocal.$commonInterfaceMethod ").parens(m.params) { p =>
              val paramName = idKotlin.local(p.ident)
              w.w(s"${kotlinMapper.map(paramName, p.ty.resolved)}")
            }

            w.wl

            /* map return value if any */
            m.ret.map { ty =>
              w.wl(s"return ${javaMapper.map("ret", ty.resolved)}")
            }
          }
        }
      }
    })

  }

  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: ast.Enum): Unit = {
    val refs = new KMPAndroidRefs()

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      val kotlinEnum = idKotlin.ty(ident.name)
      val javaEnum = javaMarshal.fqTypename(ident, e)

      /* generate the toJava() method */
      w.w(s"fun $kotlinEnum.toJava(): $javaEnum").braced {
        w.w("return when(this)").braced {
          for (o <- e.options) {
            val kotlinOption = idKotlin.enum(o.ident)
            val javaOption = idJava.enum(o.ident)
            w.wl(s"$kotlinEnum.$kotlinOption -> $javaEnum.$javaOption")
          }
        }
      }

      w.wl

      /* generate the toKotlin() method */
      w.w(s"fun $javaEnum.toKotlin(): $kotlinEnum").braced {
        w.w("return when(this)").braced {
          for (o <- e.options) {
            val kotlinOption = idKotlin.enum(o.ident)
            val javaOption = idJava.enum(o.ident)
            w.wl(s"$javaEnum.$javaOption -> $kotlinEnum.$kotlinOption")
          }
        }
      }
    })
  }

  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: Record): Unit = {
    val refs = new KMPAndroidRefs()

    r.fields.foreach(f => {
      refs.find(f.ty)
    })

    writeKotlinFile(ident.name, origin, refs.kotlin ++ refs.java, w => {
      val kotlinRecord = idKotlin.ty(ident.name)
      val javaRecord = javaMarshal.fqTypename(ident.name, r)

      /* generate the toJava() method */
      w.w(s"fun $kotlinRecord.toJava(): $javaRecord").braced {
        w.w(s"return $javaRecord").parens(r.fields) { f =>
          val fieldName = idJava.local(f.ident)
          w.w(s"${javaMapper.map(s"this.$fieldName", f.ty.resolved)}")
        }
      }

      /* generate the toKotlin() method */
      w.w(s"fun $javaRecord.toKotlin(): $kotlinRecord").braced {
        w.w(s"return $kotlinRecord").parens(r.fields) { f =>
            val fieldName = idKotlin.local(f.ident)
            w.w(s"$fieldName = ${kotlinMapper.map(s"this.$fieldName", f.ty.resolved)}")
        }
      }
    })
  }
}
