package djinni

import generatorTools.{ImportRef, SkipFirst, Spec}

import djinni.ast.{Doc, Field, Ident, Interface, Record, TypeParam, TypeRef}
import djinni.meta.{DEnum, DInterface, DRecord, MDef, MExpr, MExtern, MList, MMap, MOpaque, MOptional, MPrimitive, MString, Meta}
import djinni.writer.IndentWriter

import java.io.File
import scala.collection.mutable

class KMPAndroidGenerator(spec: Spec) extends Generator(spec) {
  val marshal = new KotlinMarshal(spec)
  val javaMarshal = new JavaMarshal(spec)

  // create androidMain directory
  val androidMainOut = new File(spec.kotlinOutFolder.get, "androidMain/kotlin")
  if (!androidMainOut.exists()) {
    androidMainOut.mkdirs()
  }

  /* helper class which assembles set of required imports for types used within a generated files */
  private class KMPAndroidRefs() {
    var kotlin: mutable.Set[String] = mutable.TreeSet[String]()
    var java: mutable.Set[String] = mutable.TreeSet[String]()

    def find(ty: TypeRef): Unit = {
      find(ty.resolved)
    }

    def find(tm: MExpr): Unit = {
      tm.args.foreach(find)
      find(tm.base)
    }

    def find(m: Meta): Unit = {
      for (r <- marshal.references(m)) r match {
        case ImportRef(arg) => kotlin.add(arg)
        case _ =>
      }
      for (r <- javaMarshal.references(m)) r match {
        case ImportRef(arg) => java.add(arg)
        case _ =>
      }
    }
  }

  def writeKotlinFile(ident: String, origin: String, refs: Iterable[String], f: IndentWriter => Unit) {
    createFile(androidMainOut, idKotlin.ty(ident) + ".kt", (w: IndentWriter) => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      w.wl
      spec.kotlinPackage.foreach(s => w.wl(s"package $s").wl)
      if (refs.nonEmpty) {
        refs.foreach(s => w.wl(s"import $s"))
        w.wl
      }
      f(w)
    })
  }

  def mapToJava(valueName: String, tm: MExpr): String = {
    tm.base match {
      case _: MPrimitive => valueName
      case MMap =>
        val key = tm.args.head.base
        val value = tm.args.last.base
        (key, value) match {
          case (_: MPrimitive, _: MPrimitive) |
               (MString, _: MPrimitive) |
               (_: MPrimitive, MString) |
               (MString, MString) => s"$valueName.toMap(HashMap())"

          case (_: MPrimitive, _) |
               (MString, _) => s"$valueName.mapValues { ${mapToJava("it.value", tm.args.last)} }.toMap(HashMap())"

          case _ => s"$valueName.map { (k, v) -> ${mapToJava("k", tm.args.head)} to ${mapToJava("v", tm.args.last)}) }.toMap(HashMap())"
        }

      case m: MDef => m.defType match {
        case DEnum | DRecord => s"$valueName.toJava()"
        case DInterface => throw new AssertionError("mapToJava called on DInterface")
      }

      case MList =>
        s"ArrayList($valueName.map { " + mapToJava("it", tm.args.head) + " })"

      case e: MExtern if e.kotlin.isProtobufMessage =>
        val javaType = javaMarshal.fqTypename(tm)
        s"$javaType.parseFrom($valueName.encode())"
      case e: MExtern =>
        throw new AssertionError("mapToJava called on extern type which isn't a protobuf message")

      case MOptional =>
        val arg = tm.args.head
        arg.base match {
          case _: MPrimitive | MString => mapToJava(s"$valueName", arg)
          case _ => mapToJava(s"$valueName?", arg)
        }

      case _ => valueName
    }
  }

  def mapToKotlin(valueName: String, tm: MExpr): String = {
    tm.base match {
      case _: MPrimitive => valueName
      case MMap =>
        val key = tm.args.head.base
        val value = tm.args.last.base
        (key, value) match {
        case (_: MPrimitive, _: MPrimitive) |
             (MString, _: MPrimitive) |
             (_: MPrimitive, MString) |
             (MString, MString) => s"$valueName.toMap()"

        case (_: MPrimitive, _) |
             (MString, _) => s"$valueName.mapValues { ${mapToKotlin("it.value", tm.args.last)} }"

        case _ => s"$valueName.map { (k, v) -> ${mapToKotlin("k", tm.args.head)} to ${mapToKotlin("v", tm.args.last)}) }.toMap()"
      }

      case d: MDef => d.defType match {
        case DEnum | DRecord => s"$valueName.toKotlin()"
        case DInterface => throw new AssertionError("fieldToKotlin called on DInterface")
      }

      case MList =>
        s"$valueName.map { " + mapToKotlin("it", tm.args.head) + " }"

      case e: MExtern if e.kotlin.isProtobufMessage =>
        val kotlinType = e.kotlin.typename
        s"$kotlinType.ADAPTER.decode($valueName.toByteArray())"

      case MOptional =>
        val arg = tm.args.head
        arg.base match {
          case _: MPrimitive | MString => mapToKotlin(s"$valueName", arg)
          case _ => mapToKotlin(s"$valueName?", arg)
        }

      case _ => valueName
    }
  }

  override def generateInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface): Unit = {
    val refs = new KMPAndroidRefs()

    // find any required imports for all method parameters / return types
    i.methods.filterNot(_.static).foreach(m => {
      m.params.foreach(p => refs.find(p.ty))
      m.ret.foreach(refs.find)
    })

    // find any required imports for constant types
    i.consts.foreach(c => {
      refs.find(c.ty)
    })

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      val commonInterfaceType = idKotlin.ty(ident.name)
      val javaInterfaceLocal = idKotlin.local(ident.name)
      val javaInterfaceType = javaMarshal.fqTypename(ident, i)

      // wrap the java generated interface in a class which conforms to the generated commonMain interface.
      w.w(s"class ${commonInterfaceType}Impl(private val $javaInterfaceLocal: $javaInterfaceType): $commonInterfaceType").braced {
        val skipFirst = SkipFirst()
        for (m <- i.methods if !m.static) {

          skipFirst { w.wl }

          /* method implementation:
           * override fun method( $commonMainParams ): $commonMainReturn {
           *   val ret = $javaInterfaceLocal.$javaMethod(
           *     mapToJava($commonMainParam),
           *     ...
           *   )
           *   return mapToKotlin(ret)
           * }
           */

          val commonMainMethod = idKotlin.method(m.ident)
          val commonMainReturn = marshal.returnType(m.ret)

          w.w(s"override fun $commonMainMethod").parens(m.params) { p =>
                val paramName = idKotlin.local(p.ident)
                val paramType = marshal.paramType(p.ty)
                w.w(s"$paramName: $paramType")
          }

          w.w(s": $commonMainReturn").braced {
            /* store return value if any */
            if(m.ret.nonEmpty) w.w(s"val ret = ")

            w.w(s"$javaInterfaceLocal.$commonMainMethod").parens(m.params) { p =>
              val paramName = idKotlin.local(p.ident)
              w.w(s"${mapToJava(paramName, p.ty.resolved)}")
            }

            // if m.ret isn't empty then write output of retToKotlin
            m.ret.map { ty =>
              w.wl.wl(s"return ${mapToKotlin("ret", ty.resolved)}")
            }
          }
        }
      }
    })
  }

  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: ast.Enum): Unit = {
    val refs = new KMPAndroidRefs()

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      val kotlinEnum = idKotlin.ty(ident.name)
      val javaEnum = javaMarshal.fqTypename(ident, e)

      /* generate the toJava() method */
      w.w(s"fun $kotlinEnum.toJava(): $javaEnum").braced {
        w.w("return when(this)").braced {
          for (o <- e.options) {
            val kotlinOption = idKotlin.enum(o.ident)
            val javaOption = idJava.enum(o.ident)
            w.wl(s"$kotlinEnum.$kotlinOption -> $javaEnum.$javaOption")
          }
        }
      }

      w.wl

      /* generate the toKotlin() method */
      w.w(s"fun $javaEnum.toKotlin(): $kotlinEnum").braced {
        w.w("return when(this)").braced {
          for (o <- e.options) {
            val kotlinOption = idKotlin.enum(o.ident)
            val javaOption = idJava.enum(o.ident)
            w.wl(s"$javaEnum.$javaOption -> $kotlinEnum.$kotlinOption")
          }
        }
      }
    })
  }

  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: Record): Unit = {
    val refs = new KMPAndroidRefs()

    r.fields.foreach(f => {
      refs.find(f.ty)
    })

    writeKotlinFile(ident.name, origin, refs.kotlin ++ refs.java, w => {
      val kotlinRecord = idKotlin.ty(ident.name)
      val javaRecord = javaMarshal.fqTypename(ident.name, r)

      /* generate the toJava() method */
      w.w(s"fun $kotlinRecord.toJava(): $javaRecord").braced {
        w.w(s"return $javaRecord").parens(r.fields) { f =>
          val fieldName = idJava.local(f.ident)
          w.w(s"${mapToJava(s"this.$fieldName", f.ty.resolved)}")
        }
      }

      /* generate the toKotlin() method */
      w.w(s"fun $javaRecord.toKotlin(): $kotlinRecord").braced {
        w.w(s"return $kotlinRecord").parens(r.fields) { f =>
            val fieldName = idKotlin.local(f.ident)
            w.w(s"$fieldName = ${mapToKotlin(s"this.$fieldName", f.ty.resolved)}")
        }
      }
    })
  }
}
