package djinni

import generatorTools.{ImportRef, Spec}

import djinni.ast.{Doc, Ident, Interface, Record, TypeParam, TypeRef}
import djinni.meta.{MExpr, Meta}
import djinni.writer.IndentWriter

import java.io.File
import scala.collection.mutable

class KMPCommonGenerator(spec: Spec) extends Generator(spec) {

  val marshal = new KotlinMarshal(spec)

  // create commonMain directory
  private val commonMainOut = new File(spec.kotlinOutFolder.get, "commonMain/kotlin")
  if (!commonMainOut.exists()) {
    commonMainOut.mkdirs()
  }

  /* helper class which assembles set of required imports for types used within a generated files */
  private class KMPCommonRefs() {
    var kotlin: mutable.Set[String] = mutable.TreeSet[String]()

    def find(ty: TypeRef): Unit = {
      find(ty.resolved)
    }

    def find(tm: MExpr): Unit = {
      tm.args.foreach(find)
      find(tm.base)
    }

    def find(m: Meta): Unit = for (r <- marshal.references(m)) r match {
      case ImportRef(arg) => kotlin.add(arg)
      case _ =>
    }
  }

  def writeKotlinFile(ident: String, origin: String, refs: Iterable[String], f: IndentWriter => Unit) {
    createFile(commonMainOut, idKotlin.ty(ident) + ".kt", (w: IndentWriter) => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      w.wl
      spec.kotlinPackage.foreach(s => w.wl(s"package $s").wl)
      if (refs.nonEmpty) {
        refs.foreach(s => w.wl(s"import $s"))
        w.wl
      }
      f(w)
    })
  }

  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: ast.Enum): Unit = {
    val refs = new KMPCommonRefs()

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      w.w("enum class " + idKotlin.ty(ident.name)).braced {
        for (o <- e.options) {
          val optionName = idKotlin.enum(o.ident)
          w.w(optionName)
          if (o != e.options.last) w.wl(",") else w.wl
        }
      }
    })
  }

  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: Record): Unit = {
    val refs = new KMPCommonRefs()
    r.fields.foreach(f => refs.find(f.ty))

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      val recordName = idKotlin.ty(ident.name)
      w.w(s"data class $recordName").parens(r.fields) { f =>
        // field definitions
        val fieldName = idKotlin.field(f.ident)
        val fieldType = marshal.fieldType(f.ty)
        w.w(s"val $fieldName: $fieldType")
      }
    })
  }

  override def generateInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface): Unit = {
    val refs = new KMPCommonRefs()

    i.methods.filterNot(_.static).map(m => {
      m.params.map(p => refs.find(p.ty))
      m.ret.foreach(refs.find)
    })

    i.consts.map(c => {
      refs.find(c.ty)
    })

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      val interfaceName = idKotlin.ty(ident.name)
      w.w(s"interface $interfaceName").braced {
        for (m <- i.methods if !m.static) {
          // method definitions
          val methodName = idKotlin.method(m.ident)
          w.w(s"fun $methodName").parens(m.params) { p =>
            val paramName = idKotlin.local(p.ident)
            val paramType = marshal.paramType(p.ty)
            w.w(s"$paramName: $paramType")
          }
          // return type
          w.wl(s": ${marshal.returnType(m.ret)}")
        }
      }
    })
  }
}
