package djinni

import ast.{Doc, Field, Ident, Interface, Record, TypeParam, TypeRef}
import generatorTools.{ImportRef, SkipFirst, Spec}
import meta.{MDef, MExpr, Meta}
import writer.IndentWriter

import java.io.File
import scala.collection.mutable

class KMPCommonGenerator(spec: Spec) extends Generator(spec) {
  private val kotlinMarshal = new KotlinMarshal(spec)

  // create commonMain directory
  // we want to put it in the class path folder based on the contents of spec.kotlinPackage
  // e.g. 'com.safetyculture.krux.domain' -> /com/safetyculture.krux.domain
  private val commonMainOut = {
    val baseDir = new File(spec.kotlinOutFolder.get, "commonMain/kotlin")
    spec.kotlinPackage match {
      case Some(pkg) =>
        val packagePath = pkg.replace('.', File.separatorChar)
        val targetDir = new File(baseDir, packagePath)
        if (!targetDir.exists()) {
          targetDir.mkdirs()
        }
        targetDir
      case None =>
        if (!baseDir.exists()) {
          baseDir.mkdirs()
        }
        baseDir
    }
  }

  /* helper class which assembles set of required imports for types used within a generated files */
  private class KMPCommonRefs() {
    var kotlin: mutable.Set[String] = mutable.TreeSet[String]()

    def find(ty: TypeRef): Unit = {
      find(ty.resolved)
    }

    def find(tm: MExpr): Unit = {
      tm.args.foreach(find)
      find(tm.base)
    }

    def find(m: Meta): Unit = for (r <- kotlinMarshal.references(m)) r match {
      case ImportRef(arg) => kotlin.add(arg)
      case _ =>
    }
  }

  def writeKotlinFile(ident: String, origin: String, refs: Iterable[String], f: IndentWriter => Unit) {
    createFile(commonMainOut, idKotlin.ty(ident) + ".kt", (w: IndentWriter) => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      w.wl
      spec.kotlinPackage.foreach(s => w.wl(s"package $s").wl)
      if (refs.nonEmpty) {
        refs.foreach(s => w.wl(s"import $s"))
        w.wl
      }
      f(w)
    })
  }

  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: ast.Enum): Unit = {
    val refs = new KMPCommonRefs()

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      w.w("enum class " + idKotlin.ty(ident.name)).braced {
        for (o <- e.options) {
          val optionName = idKotlin.enum(o.ident)
          w.w(optionName)
          if (o != e.options.last) w.wl(",") else w.wl(";")
        }
        w.wl("companion object {}")
      }
    })
  }

  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: Record): Unit = {
    val refs = new KMPCommonRefs()
    r.fields.foreach(f => refs.find(f.ty))

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      val recordName = idKotlin.ty(ident.name)
      w.w(s"data class $recordName").parens(r.fields) { f =>
        // field definitions
        val fieldName = idKotlin.field(f.ident)
        val fieldType = kotlinMarshal.fieldType(f.ty)
        w.w(s"val $fieldName: $fieldType")
      }
    })
  }

  implicit class InterfaceIndentWriter(w: IndentWriter) {

    /**
     * Writes a method function declaration, including its name, parameters, and return type,
     * for a method defined in the `Interface.Method` object.
     *
     * {{{
     * fun $methodName($methodParams): $returnType
     * }}}
     *
     * @param m The Interface.Method object containing the method's identifier, parameters,
     *          and return type.
     * @return The IndentWriter instance with the formatted function declaration appended.
     */
    def method(m: Interface.Method): IndentWriter = {
      val methodName = idKotlin.method(m.ident)
      w.w(s"fun $methodName").methodParams(m).returnType(m).wl
    }

    /**
     * Prints the parameter section of an interface method's signature.
     *
     * {{{
     * ($paramName: $paramType, $paramName: $paramType, ...)
     * }}}
     *
     * @param m The Interface.Method containing the parameters to format
     * @return The IndentWriter with the method parameters signature appended.
     */
    def methodParams(m: Interface.Method): IndentWriter = {
      w.parens(m.params) { p =>
        val paramName = idKotlin.local(p.ident)
        val paramType = kotlinMarshal.paramType(p.ty)
        w.w(s"$paramName: $paramType")
      }
      w
    }

    /**
     * Writes the return type section of an interface method's signature.
     *
     * {{{
     * : $returnType
     * }}}
     *
     * @param m The Interface.Method to write the return type for.
     * @param explicitUnitType 'Unit' return type is omitted unless explicitUnitType is true, defaults to false.
     * @return The IndentWriter with the return type declaration appended.
     */
    def returnType(m: Interface.Method, explicitUnitType: Boolean = false): IndentWriter = {
      val returnType: Option[String] = m.ret.map { ty =>
        ty.resolved.base match {
          // iOS cinterop interface return types are optional
          case MDef(_, _, _, i: Interface) if i.ext.cpp => kotlinMarshal.returnType(m.ret) + "?"
          case _ => kotlinMarshal.returnType(m.ret)
        }
      }.orElse { if (explicitUnitType) Some("Unit") else None }

      returnType.map(r => w.w(s": $r"))
      w
    }

    /**
     * Writes an internal 'expect' declaration for a static method, including its name, parameters,
     * and return type.
     *
     * {{{
     * internal expect fun $methodName$interfaceName($methodParams): $returnType
     * }}}
     *
     * @param m     The Interface.Method containing the details of the static method,
     *              including its identifier, parameters, and return type.
     * @param ident The Ident representing the interface containing the static method.
     * @return The IndentWriter with the static method declaration appended.
     */
    def staticMethod(m: Interface.Method, ident: Ident): IndentWriter = {
      val interfaceName = idKotlin.ty(ident.name)
      val methodName = idKotlin.method(m.ident)
      w.w(s"internal expect fun $methodName$interfaceName").methodParams(m).returnType(m).wl
    }

    /**
     * Writes a companion object method declaration for a given static interface method and maps it to an
     * internal 'expect' declaration generated by `staticMethod`.
     *
     * {{{
     * fun $methodName($paramName: $paramType, ...): $returnType = $methodName$interfaceName($paramName, ...)
     * }}}
     *
     * @param m     The Interface.Method that contains the static method's information such as its
     *              identifier, parameters, and optional return type.
     * @param ident The Ident representing the parent interface for which the static method
     *              is being defined.
     * @return The IndentWriter instance with the formatted companion object static method
     *         declaration appended.
     */
    def staticMethodCompanion(m: Interface.Method, ident: Ident): IndentWriter = {
      val interfaceName = idKotlin.ty(ident.name)
      val methodName = idKotlin.method(m.ident)
      w.w(s"fun $methodName").methodParams(m).returnType(m)
        .w(s" = $methodName$interfaceName").parens(m.params) { p =>
          val localParamName = idKotlin.local(p.ident)
          w.w(s"$localParamName")
        }
      w.wl
    }
  }

  override def generateInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface): Unit = {
    val refs = new KMPCommonRefs()

    /* find any imports associated with all interface method parameters and return types */
    i.methods.map(m => {
      m.params.map(p => refs.find(p.ty))
      m.ret.foreach(refs.find)
    })

    /* separate static methods from interface methods */
    val (staticMethods, interfaceMethods) = i.methods.partition(_.static)

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {

      /* static method 'expect' declarations */
      staticMethods.foreach(m => w.staticMethod(m, ident))

      w.wl

      /* interface declaration */
      val interfaceName = idKotlin.ty(ident.name)
      w.w(s"interface $interfaceName").braced {

        /* companion object */
        if (staticMethods.nonEmpty) {
          w.w("companion object").braced {
            /* static method companion declarations, mapped to internal expect declarations */
            staticMethods.foreach {
              m => w.staticMethodCompanion(m, ident)
            }
          }
        }

        w.wl

        /* interface method declarations */
        interfaceMethods.foreach(w.method)
      }
    })
  }
}
