package djinni

import ast._
import generatorTools.{ImportRef, SkipFirst, Spec, SymbolReference}
import meta._
import writer.IndentWriter

import java.io.File
import scala.collection.mutable

class KMPIOSGenerator(spec: Spec) extends Generator(spec) {
  private val kotlinMarshal = new KotlinMarshal(spec)
  private val objcMarshal = new ObjcMarshal(spec)

  private val objcMapper = new KMPIOSObjcMapper()
  private val kotlinMapper = new KMPIOSKotlinMapper(kotlinMarshal)

  // create iosMain directory
  val iosMainOut = new File(spec.kotlinOutFolder.get, "iosMain/kotlin")
  if (!iosMainOut.exists()) {
    iosMainOut.mkdirs()
  }

  /* helper class which assembles set of required imports for types used within a generated files */
  private class KMPIOSRefs() {
    var kotlin: mutable.Set[String] = mutable.TreeSet[String]()

    def find(ty: TypeRef): Unit = {
      find(ty.resolved)
    }

    def find(tm: MExpr): Unit = {
      tm.args.foreach(find)
      find(tm.base)
    }

    def find(m: Meta): Unit = {
      for (r <- kotlinMarshal.references(m)) r match {
        case ImportRef(arg) => kotlin.add(arg)
        case _ =>
      }
    }

    def findCInterop(tm: MExpr): Unit = {
      tm.args.foreach(findCInterop)
      findCInterop(tm.base)
    }

    def findCInterop(m: Meta): Unit = {
      for (r <- cinteropReferences(m)) r match {
        case ImportRef(arg) => kotlin.add(arg)
        case _ =>
      }
    }

    def cinteropReferences(m: Meta): Seq[SymbolReference] = m match {
      case e: MExtern =>
        List(ImportRef(withCInteropPackage(e.objc.typename)))

      case d: MDef =>
        List(ImportRef(withCInteropPackage(idObjc.ty(d.name))))

      case _ => List()
    }
  }


  def writeKotlinFile(ident: String, origin: String, refs: Iterable[String], f: IndentWriter => Unit) {
    createFile(iosMainOut, idKotlin.ty(ident) + ".kt", (w: IndentWriter) => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      w.wl
      spec.kotlinPackage.foreach(s => w.wl(s"package $s").wl)
      if (refs.nonEmpty) {
        refs.foreach(s => w.wl(s"import $s"))
        w.wl
      }
      f(w)
    })
  }

  override def generateInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface): Unit = {
    val commonInterfaceType = idKotlin.ty(ident.name)
    val objcInterfaceLocal = idKotlin.local(ident.name)
    val objcInterfaceType = objcMarshal.typename(ident, i)


    val refs = new KMPIOSRefs()
    refs.kotlin.add("kotlinx.cinterop.ExperimentalForeignApi")

    // import the objc type from the cinterop package
    refs.kotlin.add(withCInteropPackage(objcInterfaceType))

    // find any required imports for all method parameters / return types
    i.methods.filterNot(_.static).foreach(m => {
      // for each parameter
      m.params.foreach { p =>
        // gather any imports required to map this parameter
        refs.kotlin ++= kotlinMapper.typeRefs(p.ty.resolved)
        refs.kotlin ++= objcMapper.typeRefs(p.ty.resolved)

        // find imports associated with the parameter type
        refs.find(p.ty)

        // special case for any external types
        p.ty.resolved.base match {
          // include cinterop import for this external type
          case e: MExtern => refs.findCInterop(e)
          case _ =>
        }
      }

      // check for required imports for the return type
      m.ret.foreach(r => {
        // gather any imports required to map the return type
        refs.kotlin ++= kotlinMapper.typeRefs(r.resolved)
        refs.kotlin ++= objcMapper.typeRefs(r.resolved)

        // find imports associated with the return type
        refs.find(r)
      })
    })

    // search for imports associated with constants
    i.consts.foreach(c => {
      refs.find(c.ty)
    })

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {

      // wrap the objc generated interface in a class which conforms to the generated commonMain interface.
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"class ${commonInterfaceType}Impl(private val $objcInterfaceLocal: $objcInterfaceType): $commonInterfaceType").braced {
        val skipFirst = SkipFirst()
        for (m <- i.methods if !m.static) {

          skipFirst { w.wl }

          /* method implementation:
           * override fun method( $commonMainParams ): $commonMainReturn {
           *   val ret = $objcInterfaceLocal.$objcMethod(
           *     objcMapper.map($commonMainParam),
           *     ...
           *   )
           *   return kotlinMapper.map(ret)
           * }
           */

          val commonMainMethod = idKotlin.method(m.ident)
          val commonMainReturn = kotlinMarshal.returnType(m.ret)

          w.w(s"override fun $commonMainMethod").parens(m.params) { p =>
                val paramName = idKotlin.local(p.ident)
                val paramType = kotlinMarshal.paramType(p.ty)
                w.w(s"$paramName: $paramType")
          }

          w.w(s": $commonMainReturn").braced {
            /* store return value if any */
            if(m.ret.nonEmpty) w.w(s"val ret = ")

            w.w(s"$objcInterfaceLocal.$commonMainMethod").parens(m.params) { p =>
              val paramName = idKotlin.local(p.ident)
              w.w(s"${objcMapper.map(paramName, p.ty.resolved)}")
            }

            // return stored value if any
            m.ret.map { ty =>
              w.wl.wl(s"return ${kotlinMapper.map("ret", ty.resolved)}")
            }
          }
        }
      }
    })
  }

  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: ast.Enum): Unit = {
    val objcEnumType = objcMarshal.typename(ident, e)

    val refs = new KMPIOSRefs()
    refs.kotlin.add("kotlinx.cinterop.ExperimentalForeignApi")

    // import the enum type from the cinterop package
    refs.kotlin.add(withCInteropPackage(objcEnumType))

    // import NSNumber for a helper function
    refs.kotlin.add("platform.Foundation.NSNumber")

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      val kotlinEnum = idKotlin.ty(ident.name)
      val objcEnum = objcMarshal.fqTypename(ident, e)

      /* generate the toObjc() method */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $kotlinEnum.toObjc(): $objcEnum").braced {
        w.w("return when(this)").braced {
          for (o <- e.options) {
            val kotlinOption = idKotlin.enum(o.ident)
            val objcOption = objcEnumType + idObjc.enum(o.ident)
            w.wl(s"$kotlinEnum.$kotlinOption -> ${withCInteropPackage(objcOption)}")
          }
        }
      }

      w.wl

      /* helper to convert to NSNumber */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $kotlinEnum.toNSNumber(): NSNumber").braced {
        w.wl("return NSNumber(long = toObjc())")
      }

      w.wl

      /* generate the fromObjc() method */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $kotlinEnum.Companion.fromObjc(e: $objcEnum): $kotlinEnum").braced {
        w.w("return when(e)").braced {
          for (o <- e.options) {
            val kotlinOption = idKotlin.enum(o.ident)
            val objcOption = objcEnumType + idObjc.enum(o.ident)
            w.wl(s"${withCInteropPackage(objcOption)} -> $kotlinEnum.$kotlinOption")
          }
          w.wl(s" else -> throw IllegalArgumentException(${'"'}Unknown ${kotlinEnum}: $$e${'"'})")
        }
      }

      w.wl

      /* helper to derive this enum from an NSNumber */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $kotlinEnum.Companion.fromNSNumber(e: NSNumber): $kotlinEnum").braced {
        w.wl("return fromObjc(e.integerValue)")
      }
    })
  }

  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: Record): Unit = {
    val kotlinRecord = idKotlin.ty(ident.name)
    val objcRecord = objcMarshal.typename(ident.name, r)

    val refs = new KMPIOSRefs()
    refs.kotlin.add("kotlinx.cinterop.ExperimentalForeignApi")
    refs.kotlin.add(withCInteropPackage(objcRecord))

    r.fields.foreach(f => {
      // search for imports required when mapping this field
      refs.kotlin ++= kotlinMapper.typeRefs(f.ty.resolved)
      refs.kotlin ++=  objcMapper.typeRefs(f.ty.resolved)
    })

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {

      /* generate the toObjc() method */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $kotlinRecord.toObjc(): $objcRecord").braced {
        w.w(s"return $objcRecord").parens(r.fields) { f =>
          val kotlinFieldName = idKotlin.local(f.ident)
          w.w(s"${objcMapper.map(s"this.$kotlinFieldName", f.ty.resolved)}")
        }
        w.wl
      }

      w.wl

      /* generate the toKotlin() method */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $objcRecord.toKotlin(): $kotlinRecord").braced {
        w.w(s"return $kotlinRecord").parens(r.fields) { f =>
            val kotlinFieldName = idKotlin.local(f.ident)
            val objcFieldName = idObjc.local(f.ident)
            w.w(s"$kotlinFieldName = ${kotlinMapper.map(s"this.$objcFieldName", f.ty.resolved)}")
        }
        w.wl
      }
    })
  }

  def withCInteropPackage(typeName: String): String = {
    spec.kotlinCInteropPackage.fold(typeName)(_ + "." + typeName)
  }

  def withSupportPackage(typeName: String): String = {
    spec.kotlinSupportPackage.fold(typeName)(_ + "." + typeName)
  }
}
