package djinni

import ast._
import generatorTools.{ImportRef, SkipFirst, Spec, SymbolReference}
import meta._
import writer.IndentWriter

import java.io.File
import scala.collection.mutable

class KMPIOSGenerator(spec: Spec) extends Generator(spec) {
  private val kotlinMarshal = new KotlinMarshal(spec)
  private val objcMarshal = new ObjcMarshal(spec)

  private val objcMapper = new KMPIOSObjcMapper(kotlinMarshal, objcMarshal, spec)
  private val kotlinMapper = new KMPIOSKotlinMapper(kotlinMarshal, objcMarshal, spec)

  private val utils = new KMPUtils(kotlinMarshal, spec)

  // create iosMain directory
  // we want to put it in the class path folder based on the contents of spec.kotlinPackage
  // e.g. 'com.safetyculture.krux.domain' -> /com/safetyculture.krux.domain
  private val iosMainOut = {
    val baseDir = new File(spec.kotlinOutFolder.get, "iosMain/kotlin")
    spec.kotlinPackage match {
      case Some(pkg) =>
        val packagePath = pkg.replace('.', File.separatorChar)
        val targetDir = new File(baseDir, packagePath)
        if (!targetDir.exists()) {
          targetDir.mkdirs()
        }
        targetDir
      case None =>
        if (!baseDir.exists()) {
          baseDir.mkdirs()
        }
        baseDir
    }
  }

  /* helper class which assembles set of required imports for types used within a generated files */
  private class KMPIOSRefs() {
    var kotlin: mutable.Set[String] = mutable.TreeSet[String]()

    def find(ty: TypeRef): Unit = {
      find(ty.resolved)
    }

    def find(tm: MExpr): Unit = {
      tm.args.foreach(find)
      find(tm.base)
    }

    def find(m: Meta): Unit = {
      for (r <- kotlinMarshal.references(m)) r match {
        case ImportRef(arg) => kotlin.add(arg)
        case _ =>
      }
    }

    def findCInterop(tm: MExpr): Unit = {
      tm.args.foreach(findCInterop)
      findCInterop(tm.base)
    }

    def findCInterop(m: Meta): Unit = {
      for (r <- cinteropReferences(m)) r match {
        case ImportRef(arg) => kotlin.add(arg)
        case _ =>
      }
    }

    def cinteropReferences(m: Meta): Seq[SymbolReference] = m match {
      case e: MExtern =>
        List(ImportRef(utils.withCInteropPackage(e.objc.typename)))

      case d: MDef =>
        val typeName = idObjc.ty(d.name)
        d.defType match {
        case DInterface =>
          List(ImportRef(utils.withCInteropPackage(typeName + "Protocol")))
        case _ =>
          List(ImportRef(utils.withCInteropPackage(typeName)))
        }
      case MDate => List(ImportRef("platform.Foundation.NSDate"))

      case _ => List()
    }
  }


  def writeKotlinFile(ident: String, origin: String, refs: Iterable[String], f: IndentWriter => Unit) {
    createFile(iosMainOut, idKotlin.ty(ident) + ".kt", (w: IndentWriter) => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      w.wl
      spec.kotlinPackage.foreach(s => w.wl(s"package $s").wl)
      if (refs.nonEmpty) {
        refs.foreach(s => w.wl(s"import $s"))
        w.wl
      }
      f(w)
    })
  }


  override def generateInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface): Unit = {
    if(i.ext.objc) {
      generateObjcInterface(origin, ident, doc, typeParams, i)
    } else if(i.ext.cpp) {
      generateCppInterface(origin, ident, doc, typeParams, i)
    }
  }

  def generateCppInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface): Unit = {
    val refs = new KMPIOSRefs()
    refs.kotlin.add("kotlinx.cinterop.ExperimentalForeignApi")

    /* import the objc interface type from the cinterop package */
    val objcInterfaceType: String = objcMarshal.typename(ident, i)
    refs.kotlin.add(utils.withCInteropPackage(objcInterfaceType))

    /* find any imports associated with all interface method parameters and return types */
    i.methods.foreach(m => {
      m.params.foreach { p =>
        // gather any imports required to map this parameter from kotlin to objc
        refs.kotlin ++= objcMapper.typeRefs(p.ty.resolved)

        // find imports associated with the parameter type
        refs.find(p.ty)
      }

      // check for required imports for the return type
      m.ret.foreach(r => {
        // gather any imports required to map the return type from objc back to kotlin
        refs.kotlin ++= kotlinMapper.typeRefs(r.resolved)

        // find imports associated with the return type
        refs.find(r)
      })
    })

    /* separate static methods from interface methods */
    val (staticMethods, interfaceMethods) = i.methods.partition(_.static)

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      /* static method 'actual' implementations */
      staticMethods.foreach(m => w.staticMethod(m, ident, i))

      /* wrap the C++ generated interface in a class which conforms to the generated commonMain interface. */
      w.cppInterfaceClass(ident, i).braced {
        /* interface method implementations */
        w.wlDivider(interfaceMethods) { m =>
          w.cppInterfaceMethod(m, ident)
        }
      }
    })
  }

  def generateObjcInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface): Unit = {
    val refs = new KMPIOSRefs()
    refs.kotlin.add("kotlinx.cinterop.ExperimentalForeignApi")
    refs.kotlin.add("platform.darwin.NSObject")

    /* import the objc interface type from the cinterop package */
    val objcProtocolName: String = s"${idObjc.ty(ident.name)}Protocol"
    refs.kotlin.add(utils.withCInteropPackage(objcProtocolName))

    val interfaceMethods = i.methods.filterNot(_.static)

    /* find any required imports for all method parameters / return types */
    interfaceMethods.foreach(m => {
      /* for each parameter */
      m.params.foreach { p =>
        /* gather any imports required to map this parameter from objc to kotlin */
        refs.kotlin ++= kotlinMapper.typeRefs(p.ty.resolved)

        /* find imports associated with the parameter type */
        refs.findCInterop(p.ty.resolved)
      }

      /* check for required imports for the return type */
      m.ret.foreach(r => {
        /* gather any imports required to map the return type from kotlin back to objc */
        refs.kotlin ++= objcMapper.typeRefs(r.resolved)

        /* find imports associated with the return type */
        refs.findCInterop(r.resolved)
      })
    })

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      /* wrap the objc generated interface in a class which conforms to the generated commonMain interface */
      w.objcInterfaceClass(ident, i).braced {
        /* interface method implementations */
        w.wlDivider(interfaceMethods) { m =>
          w.objcInterfaceMethod(m, ident)
        }
      }
    })
  }

  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: ast.Enum): Unit = {
    val objcEnumType = objcMarshal.typename(ident, e)

    val refs = new KMPIOSRefs()
    refs.kotlin.add("kotlinx.cinterop.ExperimentalForeignApi")

    // import the enum type from the cinterop package
    refs.kotlin.add(utils.withCInteropPackage(objcEnumType))

    // import NSNumber for a helper function
    refs.kotlin.add("platform.Foundation.NSNumber")

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      val kotlinEnum = idKotlin.ty(ident.name)
      val objcEnum = objcMarshal.fqTypename(ident, e)

      /* generate the toObjc() method */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $kotlinEnum.toObjc(): $objcEnum").braced {
        w.w("return when(this)").braced {
          for (o <- e.options) {
            val kotlinOption = idKotlin.enum(o.ident)
            val objcOption = objcEnumType + idObjc.enum(o.ident)
            w.wl(s"$kotlinEnum.$kotlinOption -> ${utils.withCInteropPackage(objcOption)}")
          }
        }
      }

      w.wl

      /* helper to convert to NSNumber */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $kotlinEnum.toNSNumber(): NSNumber").braced {
        w.wl("return NSNumber(long = toObjc())")
      }

      w.wl

      /* generate the fromObjc() method */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $kotlinEnum.Companion.fromObjc(e: $objcEnum): $kotlinEnum").braced {
        w.w("return when(e)").braced {
          for (o <- e.options) {
            val kotlinOption = idKotlin.enum(o.ident)
            val objcOption = objcEnumType + idObjc.enum(o.ident)
            w.wl(s"${utils.withCInteropPackage(objcOption)} -> $kotlinEnum.$kotlinOption")
          }
          w.wl(s" else -> throw IllegalArgumentException(${'"'}Unknown ${kotlinEnum}: $$e${'"'})")
        }
      }

      w.wl

      /* helper to derive this enum from an NSNumber */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $kotlinEnum.Companion.fromNSNumber(e: NSNumber): $kotlinEnum").braced {
        w.wl("return fromObjc(e.integerValue)")
      }
    })
  }

  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: Record): Unit = {
    val kotlinRecord = idKotlin.ty(ident.name)
    val objcRecord = objcMarshal.typename(ident.name, r)

    val refs = new KMPIOSRefs()
    refs.kotlin.add("kotlinx.cinterop.ExperimentalForeignApi")
    refs.kotlin.add(utils.withCInteropPackage(objcRecord))

    r.fields.foreach(f => {
      // search for imports required when mapping this field
      refs.kotlin ++= kotlinMapper.typeRefs(f.ty.resolved)
      refs.kotlin ++=  objcMapper.typeRefs(f.ty.resolved)
    })

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {

      /* generate the toObjc() method */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $kotlinRecord.toObjc(): $objcRecord").braced {
        w.w(s"return $objcRecord").parens(r.fields) { f =>
          val kotlinFieldName = idKotlin.local(f.ident)
          w.w(s"${objcMapper.map(s"this.$kotlinFieldName", f.ty.resolved)}")
        }
        w.wl
      }

      w.wl

      /* generate the toKotlin() method */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $objcRecord.toKotlin(): $kotlinRecord").braced {
        w.w(s"return $kotlinRecord").parens(r.fields) { f =>
            val kotlinFieldName = idKotlin.local(f.ident)
            val objcFieldName = idObjc.local(f.ident)
            w.w(s"$kotlinFieldName = ${kotlinMapper.map(s"this.$objcFieldName", f.ty.resolved)}")
        }
        w.wl
      }
    })
  }

  implicit class InterfaceIndentWriter(w: IndentWriter) {

    /**
     * Writes the declaration of a class which implements a given Kotlin common interface and serves as
     * a wrapper around the underlying C++ implementation which is exposed via an Objective-C interface.
     *
     * e.g.
     * {{{
     * @OptIn(ExperimentalForeignApi::class)
     * class ${commonInterfaceName}(private val $objcInterfaceLocal: $objcInterfaceType): $commonInterfaceType
     * }}}
     *
     * @param ident The `Ident` object containing the name and metadata of the interface.
     * @param i     The `Interface` for which to generate the declaration for.
     * @return The `IndentWriter` with the Kotlin class code corresponding to the Objective-C interface appended.
     */
    def cppInterfaceClass(ident: Ident, i: Interface): IndentWriter = {
      val commonInterfaceName = s"${idKotlin.ty(ident.name)}Impl"
      val commonInterfaceType = idKotlin.ty(ident.name)
      val objcInterfaceLocal = idKotlin.local(ident.name)
      val objcInterfaceType: String = objcMarshal.typename(ident, i)

      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"class ${commonInterfaceName}(private val $objcInterfaceLocal: $objcInterfaceType): $commonInterfaceType")
    }

    /**
     * Writes an implementation of the given interface method that calls an instance of the underlying
     * wrapped interface with mapped parameter values, mapping the return value if any.
     *
     * e.g.
     * {{{
     * override fun $methodName($methodParams): $returnType {
     *   val ret = $objcInterfaceLocal.$objcMethodName($objcMappedParams)
     *   return $kotlinMappedReturnValue
     * }
     * }}}
     *
     * @param m The Interface.Method object containing the method's identifier, parameters,
     *          and return type.
     * @return The IndentWriter instance with the formatted function declaration appended.
     */
    def cppInterfaceMethod(m: Interface.Method, ident: Ident): IndentWriter = {
      val objcInterfaceLocal = idKotlin.local(ident.name)
      val methodName = idKotlin.method(m.ident)
      val objcMethodName = idObjc.method(m.ident)

      w.w(s"override fun $methodName").cppMethodParams(m).returnType(m).braced {

        /* store return value if any */
        if(m.ret.nonEmpty) w.w(s"val ret = ")

        w.w(s"$objcInterfaceLocal.$objcMethodName").objcMappedParams(m).wl

        /* map return value if any */
        m.ret.map { ty =>
          w.wl(s"return ${kotlinMapper.map("ret", ty.resolved)}")
        }
      }
      w
    }

    /**
     * Prints the parameter section of an interface method's signature.
     *
     * e.g.
     * {{{
     * ($paramName: $paramType, $paramName: $paramType, ...)
     * }}}
     *
     * @param m The Interface.Method containing the parameters to format
     * @return The IndentWriter with the method parameters signature appended.
     */
    def cppMethodParams(m: Interface.Method): IndentWriter = {
      w.parens(m.params) { p =>
        val paramName = idKotlin.local(p.ident)
        val paramType = kotlinMarshal.paramType(p.ty)
        w.w(s"$paramName: $paramType")
      }
      w
    }

    /**
     * Writes the return type section of an interface method's signature.
     *
     * e.g.
     * {{{
     * : $returnType
     * }}}
     *
     * @param m The Interface.Method to write the return type for.
     * @param explicitUnitType 'Unit' return type is omitted unless explicitUnitType is true, defaults to false.
     * @return The IndentWriter with the return type declaration appended.
     */
    def returnType(m: Interface.Method, explicitUnitType: Boolean = false): IndentWriter = {
      val returnType: Option[String] = m.ret.map { ty =>
        ty.resolved.base match {
          // iOS cinterop interface return types are optional
          case MDef(_, _, _, i: Interface) if i.ext.cpp => kotlinMarshal.returnType(m.ret) + "?"
          case _ => kotlinMarshal.returnType(m.ret)
        }
      }.orElse { if (explicitUnitType) Some("Unit") else None }

      returnType.map(r => w.w(s": $r"))
      w
    }

    /**
     * Writes the local Kotlin parameters mapped to their Objective-C counterparts for use
     * when invoking an Objective-C interface method.
     *
     * e.g.
     * {{{
     * ($mappedParamValue, $mappedParamValue, ...)
     * }}}
     *
     * @param m The `Interface.Method` containing the parameters to be mapped.
     * @return The `IndentWriter` with the mapped parameters appended.
     */
    def objcMappedParams(m: Interface.Method): IndentWriter = {
      w.parens(m.params) { p =>
        val paramName = idKotlin.local(p.ident)
        w.w(s"${objcMapper.map(paramName, p.ty.resolved)}")
      }
      w
    }

    /**
     * Writes an internal 'actual' implementation for a static method, including its name, parameters,
     * and return type.
     *
     * e.g.
     * {{{
     * internal actual fun $methodName$interfaceName($methodParams): $returnType {
     *   val ret = $objcInterfaceType.$objcMethodName($mappedParams)
     *   return $mappedReturnValue
     * }
     * }}}
     *
     * @param m     The Interface.Method containing the details of the static method,
     *              including its identifier, parameters, and return type.
     * @param ident The Ident representing the interface containing the static method.
     * @param i     The interface which this method belongs to.
     * @return      The IndentWriter with the static method implementation appended.
     */
    def staticMethod(m: Interface.Method, ident: Ident, i: Interface): IndentWriter = {
      val interfaceType = idKotlin.ty(ident.name)
      val objcInterfaceType: String = objcMarshal.typename(ident, i)
      val methodName = idKotlin.method(m.ident)
      val objcMethodName = idObjc.method(m.ident)

      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"internal actual fun $methodName$interfaceType").cppMethodParams(m).returnType(m).braced {

        /* store the returned value if any */
        if(m.ret.nonEmpty) w.w(s"val ret = ")

        w.w(s"$objcInterfaceType.$objcMethodName").parens(m.params) { p =>
          val paramName = idKotlin.local(p.ident)
          w.w(s"${objcMapper.map(paramName, p.ty.resolved)}")
        }

        w.wl

        /* map return value if any */
        m.ret.map { ty =>
          w.wl(s"return ${kotlinMapper.map("ret", ty.resolved)}")
        }
      }
      w.wl
    }

    /**
     * Writes the declaration header of a class which serves as a wrapper around a Kotlin implementation of a
     * common interface which conforms to a corresponding Objective-C protocol.
     *
     * e.g.
     * {{{
     * @OptIn(ExperimentalForeignApi::class)
     * class ${objcInterfaceName}(private val $commonInterfaceLocal: $commonInterfaceType): NSObject(), $objcProtocolName
     * }}}
     *
     * @param ident The `Ident` object containing the name and metadata of the interface.
     * @param i     The `Interface` for which to generate the declaration for.
     * @return      The `IndentWriter` with the Objective-C interface class header appended.
     */
    def objcInterfaceClass(ident: Ident, i: Interface): IndentWriter = {
      val objcInterfaceClassName = s"${idObjc.ty(ident.name)}Impl"
      val commonInterfaceLocal = idKotlin.local(ident.name)
      val commonInterfaceType = idKotlin.ty(ident.name)
      val objcProtocolName: String = s"${idObjc.ty(ident.name)}Protocol"

      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"class ${objcInterfaceClassName}(private val $commonInterfaceLocal: $commonInterfaceType): NSObject(), $objcProtocolName")
    }

    /**
     * Writes an implementation of the given interface method that calls an instance of the underlying
     * wrapped Objective-C interface with mapped parameter values, mapping the return value if any.
     *
     * e.g.
     * {{{
     * override fun $methodName($methodParams): $returnType {
     *   val ret = $objcInterfaceLocal.$objcMethodName($objcMappedParams)
     *   return $kotlinMappedReturnValue
     * }
     * }}}
     *
     * @param m The Interface.Method object containing the method's identifier, parameters,
     *          and return type.
     * @return The IndentWriter instance with the formatted function declaration appended.
     */
    def objcInterfaceMethod(m: Interface.Method, ident: Ident): IndentWriter = {
      val objcMethod = idObjc.method(m.ident)
      val commonMethod = idKotlin.method(m.ident)
      val commonInterfaceLocal = idKotlin.local(ident.name)
      val methodReturnType = kotlinMarshal.cinteropReturnType(m.ret)

      w.w(s"override fun $objcMethod").objcMethodParams(m).w(s": $methodReturnType").braced {

        /* store return value if any */
        if (m.ret.nonEmpty) w.w(s"val ret = ")

        w.w(s"$commonInterfaceLocal.$commonMethod").kotlinMappedParams(m).wl

        /* return stored value if any */
        m.ret.map { ty =>
          w.wl.wl(s"return ${objcMapper.map("ret", ty.resolved)}")
        }
      }
      w
    }

    /**
     * Prints the parameter section of an Objective-C interface method's signature.
     *
     * e.g.
     * {{{
     * ($paramName: $paramType, $paramName: $paramType, ...)
     * }}}
     *
     * @param m The Interface.Method containing the parameters to format
     * @return The IndentWriter with the method parameters signature appended.
     */
    def objcMethodParams(m: Interface.Method): IndentWriter = {
      w.parens(m.params) { p =>
        val paramName = idObjc.local(p.ident)
        val paramType = kotlinMarshal.cinteropType(p.ty.resolved)
        w.w(s"$paramName: $paramType")
      }
      w
    }

    /**
     * Writes the Objective-C parameters mapped to their Kotlin counterparts for use
     * when invoking a common Kotlin interface method.
     *
     * e.g.
     * {{{
     * ($mappedParamValue, $mappedParamValue, ...)
     * }}}
     *
     * @param m The `Interface.Method` containing the parameters to be mapped.
     * @return The `IndentWriter` with the mapped parameters appended.
     */
    def kotlinMappedParams(m: Interface.Method): IndentWriter = {
      w.parens(m.params) { p =>
        val paramName = idObjc.local(p.ident)
        w.w(s"${kotlinMapper.map(paramName, p.ty.resolved)}")
      }
      w
    }

  }
}
