package djinni

import ast._
import generatorTools.{ImportRef, SkipFirst, Spec, SymbolReference}
import meta._
import writer.IndentWriter

import java.io.File
import scala.collection.mutable

class KMPIOSGenerator(spec: Spec) extends Generator(spec) {
  val marshal = new KotlinMarshal(spec)
  val objcMarshal = new ObjcMarshal(spec)

  // create iosMain directory
  val iosMainOut = new File(spec.kotlinOutFolder.get, "iosMain/kotlin")
  if (!iosMainOut.exists()) {
    iosMainOut.mkdirs()
  }

  /* helper class which assembles set of required imports for types used within a generated files */
  private class KMPIOSRefs() {
    var kotlin: mutable.Set[String] = mutable.TreeSet[String]()
    var objc: mutable.Set[String] = mutable.TreeSet[String]()

    def find(ty: TypeRef): Unit = {
      find(ty.resolved)
    }

    def find(tm: MExpr): Unit = {
      tm.args.foreach(find)
      find(tm.base)
    }

    def find(m: Meta): Unit = {
      for (r <- marshal.references(m)) r match {
        case ImportRef(arg) => kotlin.add(arg)
        case _ =>
      }
    }

    def findCInterop(tm: MExpr): Unit = {
      tm.args.foreach(findCInterop)
      findCInterop(tm.base)
    }

    def findCInterop(m: Meta): Unit = {
      for (r <- cinteropReferences(m)) r match {
        case ImportRef(arg) => objc.add(arg)
        case _ =>
      }
    }

    def cinteropReferences(m: Meta): Seq[SymbolReference] = m match {
      case o: MOpaque =>
        o match {
          case MDate => List(ImportRef("NSDate"))
          case _ => List()
        }
      case e: MExtern =>
        List(ImportRef(withCInteropPackage(e.objc.typename)))

      case d: MDef =>
        List(ImportRef(withCInteropPackage(idObjc.ty(d.name))))

      case _ => List()
    }
  }


  def writeKotlinFile(ident: String, origin: String, refs: Iterable[String], f: IndentWriter => Unit) {
    createFile(iosMainOut, idKotlin.ty(ident) + ".kt", (w: IndentWriter) => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      w.wl
      spec.kotlinPackage.foreach(s => w.wl(s"package $s").wl)
      if (refs.nonEmpty) {
        refs.foreach(s => w.wl(s"import $s"))
        w.wl
      }
      f(w)
    })
  }

  def mapToObjc(valueName: String, tm: MExpr, optional: Boolean = false): String = {
    tm.base match {
      case _: MPrimitive | MString => valueName
      case MDate => s"TransformDate.toObjc($valueName)"

//      case MMap =>
//        val key = tm.args.head.base
//        val value = tm.args.last.base
//        (key, value) match {
//          case (_: MPrimitive, _: MPrimitive) |
//               (MString, _: MPrimitive) |
//               (_: MPrimitive, MString) |
//               (MString, MString) => s"$valueName.toMap(HashMap())"
//
//          case (_: MPrimitive, _) |
//               (MString, _) => s"$valueName.mapValues { ${mapToObjc("it.value", tm.args.last)} }.toMap(HashMap())"
//
//          case _ => s"$valueName.map { (k, v) -> ${mapToObjc("k", tm.args.head)} to ${mapToObjc("v", tm.args.last)}) }.toMap(HashMap())"
//        }

      case m: MDef => m.defType match {
        case DEnum => s"$valueName.toObjc()"
        case DRecord => s"$valueName.toObjc()"
        case DInterface => "TODO()"
      }

//      case MList =>
//        s"ArrayList($valueName.map { " + mapToObjc("it", tm.args.head) + " })"

//      case e: MExtern if e.kotlin.isProtobufMessage =>
//        val objcType = objcMarshal.typename(tm)
//        s"$objcType.parseFromData($valueName.encode().toData(), null)"
//      case e: MExtern =>
//        throw new AssertionError("mapToObjc called on extern type which isn't a protobuf message")

      case MOptional =>
        val arg = tm.args.head
        arg.base match {
          case _: MPrimitive | MString => mapToObjc(s"$valueName", arg)
          case MDate => s"$valueName?.let { ${mapToObjc("it", arg)} }"
          case d: MDef if d.defType == DEnum => s"$valueName?.toNSNumber()"
          case _ => mapToObjc(s"$valueName?", arg)
        }

      case _ => s"TODO(${'"'}Map ${tm.base.getClass.getSimpleName.replace("$", "")}${'"'})"
    }
  }

  def mapToKotlin(valueName: String, tm: MExpr): String = {
    tm.base match {
      case _: MPrimitive | MString => valueName
      case MDate => s"TransformDate.fromObjc($valueName)"
//      case MMap =>
//        val key = tm.args.head.base
//        val value = tm.args.last.base
//        (key, value) match {
//        case (_: MPrimitive, _: MPrimitive) |
//             (MString, _: MPrimitive) |
//             (_: MPrimitive, MString) |
//             (MString, MString) => s"$valueName.toMap()"
//
//        case (_: MPrimitive, _) |
//             (MString, _) => s"$valueName.mapValues { ${mapToKotlin("it.value", tm.args.last)} }"
//
//        case _ => s"$valueName.map { (k, v) -> ${mapToKotlin("k", tm.args.head)} to ${mapToKotlin("v", tm.args.last)}) }.toMap()"
//      }

      case d: MDef => d.defType match {
        case DEnum => s"${marshal.typename(tm)}.fromObjc($valueName)"
        case DRecord => s"$valueName.toKotlin()"
        case DInterface => "TODO()"
      }

//      case MList =>
//        s"$valueName.map { " + mapToKotlin("it", tm.args.head) + " }"

//      case e: MExtern if e.kotlin.isProtobufMessage =>
//        val kotlinType = e.kotlin.typename
//        s"$valueName.data()?.let { $kotlinType.ADAPTER.decode(it.toByteArray()) }"

      case MOptional =>
        val arg = tm.args.head
        arg.base match {
          case _: MPrimitive | MString => mapToKotlin(s"$valueName", arg)
          case MDate => s"$valueName?.let { ${mapToKotlin("it", arg)} }"
          case d: MDef if d.defType == DEnum => s"$valueName?.let { ${marshal.typename(arg)}.fromNSNumber(it) }"
          case _ => mapToKotlin(s"$valueName?", arg)
        }

      case _ => s"TODO(${'"'}Map ${tm.base.getClass.getSimpleName.replace("$", "")}${'"'})"
    }
  }

  override def generateInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface): Unit = {
    val commonInterfaceType = idKotlin.ty(ident.name)
    val objcInterfaceLocal = idKotlin.local(ident.name)
    val objcInterfaceType = objcMarshal.typename(ident, i)

    val refs = new KMPIOSRefs()
    refs.kotlin.add("kotlinx.cinterop.ExperimentalForeignApi")
    refs.kotlin.add(withCInteropPackage(objcInterfaceType))

    // find any required imports for all method parameters / return types
    i.methods.filterNot(_.static).foreach(m => {
      m.params.foreach { p =>
        p.ty.resolved.base match {
          // add imports for any external types
          case e: MExtern => refs.findCInterop(e)
          case _ =>
        }

        refs.find(p.ty)
      }

      m.ret.foreach(refs.find)
    })

    // find any required imports for constant types
    i.consts.foreach(c => {
      refs.find(c.ty)
    })

    writeKotlinFile(ident.name, origin, refs.kotlin ++ refs.objc, w => {

      w.wl("@OptIn(ExperimentalForeignApi::class)")

      // wrap the objc generated interface in a class which conforms to the generated commonMain interface.
      w.w(s"class ${commonInterfaceType}Impl(private val $objcInterfaceLocal: $objcInterfaceType): $commonInterfaceType").braced {
        val skipFirst = SkipFirst()
        for (m <- i.methods if !m.static) {

          skipFirst { w.wl }

          /* method implementation:
           * override fun method( $commonMainParams ): $commonMainReturn {
           *   val ret = $objcInterfaceLocal.$objcMethod(
           *     mapToObjc($commonMainParam),
           *     ...
           *   )
           *   return mapToKotlin(ret)
           * }
           */

          val commonMainMethod = idKotlin.method(m.ident)
          val commonMainReturn = marshal.returnType(m.ret)

          w.w(s"override fun $commonMainMethod").parens(m.params) { p =>
                val paramName = idKotlin.local(p.ident)
                val paramType = marshal.paramType(p.ty)
                w.w(s"$paramName: $paramType")
          }

          w.w(s": $commonMainReturn").braced {
            /* store return value if any */
            if(m.ret.nonEmpty) w.w(s"val ret = ")

            w.w(s"$objcInterfaceLocal.$commonMainMethod").parens(m.params) { p =>
              val paramName = idKotlin.local(p.ident)
              w.w(s"${mapToObjc(paramName, p.ty.resolved)}")
            }

            // if m.ret isn't empty then write output of retToKotlin
            m.ret.map { ty =>
              w.wl.wl(s"return ${mapToKotlin("ret", ty.resolved)}")
            }
          }
        }
      }
    })
  }

  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: ast.Enum): Unit = {
    val objcEnumType = objcMarshal.typename(ident, e)

    val refs = new KMPIOSRefs()
    refs.kotlin.add("kotlinx.cinterop.ExperimentalForeignApi")
    refs.kotlin.add(withCInteropPackage(objcEnumType))
    refs.kotlin.add("platform.Foundation.NSNumber")

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      val kotlinEnum = idKotlin.ty(ident.name)
      val objcEnum = objcMarshal.fqTypename(ident, e)

      /* generate the toObjc() method */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $kotlinEnum.toObjc(): $objcEnum").braced {
        w.w("return when(this)").braced {
          for (o <- e.options) {
            val kotlinOption = idKotlin.enum(o.ident)
            val objcOption = objcEnumType + idObjc.enum(o.ident)
            w.wl(s"$kotlinEnum.$kotlinOption -> ${withCInteropPackage(objcOption)}")
          }
        }
      }

      w.wl

      /* helper to convert to NSNumber */
      w.w(s"fun $kotlinEnum.toNSNumber(): NSNumber").braced {
        w.wl("return NSNumber(toObjc())")
      }

      w.wl

      /* generate the fromObjc() method */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $kotlinEnum.Companion.fromObjc(e: $objcEnum): $kotlinEnum").braced {
        w.w("return when(e)").braced {
          for (o <- e.options) {
            val kotlinOption = idKotlin.enum(o.ident)
            val objcOption = objcEnumType + idObjc.enum(o.ident)
            w.wl(s"${withCInteropPackage(objcOption)} -> $kotlinEnum.$kotlinOption")
          }
          w.wl(s" else -> throw IllegalArgumentException(${'"'}Unknown ${kotlinEnum}: $$e${'"'})")
        }
      }

      w.wl

      /* helper to handle enum as an NSNumber */
      w.w(s"fun $kotlinEnum.Companion.fromNSNumber(e: NSNumber): $kotlinEnum").braced {
        w.wl("return fromObjc(e.integerValue)")
      }
    })
  }

  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: Record): Unit = {
    val kotlinRecord = idKotlin.ty(ident.name)
    val objcRecord = objcMarshal.typename(ident.name, r)

    val refs = new KMPIOSRefs()
    refs.kotlin.add("kotlinx.cinterop.ExperimentalForeignApi")
    refs.kotlin.add(withCInteropPackage(objcRecord))

    def helperRefs(m: MExpr): Unit = {
      m.base match {
        case MOptional => helperRefs(m.args.head)
        case MDate => refs.objc.add(withSupportPackage("TransformDate"))
        case _ =>
      }
    }

    r.fields.foreach(f => {
      refs.find(f.ty)
      helperRefs(f.ty.resolved)
    })

    writeKotlinFile(ident.name, origin, refs.kotlin ++ refs.objc, w => {

      /* generate the toObjc() method */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $kotlinRecord.toObjc(): $objcRecord").braced {
        w.w(s"return $objcRecord").parens(r.fields) { f =>
          val kotlinFieldName = idKotlin.local(f.ident)
          w.w(s"${mapToObjc(s"this.$kotlinFieldName", f.ty.resolved)}")
        }
        w.wl
      }

      w.wl

      /* generate the toKotlin() method */
      w.wl("@OptIn(ExperimentalForeignApi::class)")
      w.w(s"fun $objcRecord.toKotlin(): $kotlinRecord").braced {
        w.w(s"return $kotlinRecord").parens(r.fields) { f =>
            val kotlinFieldName = idKotlin.local(f.ident)
            val objcFieldName = idObjc.local(f.ident)
            w.w(s"$kotlinFieldName = ${mapToKotlin(s"this.$objcFieldName", f.ty.resolved)}")
        }
        w.wl
      }
    })
  }

  def withCInteropPackage(typeName: String): String = {
    spec.kotlinCInteropPackage.fold(typeName)(_ + "." + typeName)
  }

  def withSupportPackage(typeName: String): String = {
    spec.kotlinSupportPackage.fold(typeName)(_ + "." + typeName)
  }
}
