package djinni

import generatorTools.{ImportRef, Spec}

import djinni.ast.{Doc, Ident, Interface, Record, TypeParam, TypeRef}
import djinni.meta.{MExpr, Meta}
import djinni.writer.IndentWriter

import java.io.File
import scala.collection.mutable
import scala.reflect.io.Path.jfile2path

class KotlinCommonGenerator(spec: Spec) extends Generator(spec) {

  val marshal = new KotlinMarshal(spec)

  // create commonMain directory
  val commonMainOut = new File(spec.kotlinOutFolder.get, "commonMain/kotlin")
  if (!commonMainOut.exists()) {
    commonMainOut.mkdirs()
  }

  /* helper class which assembles set of any required imports for types used within a generated files */
  class KotlinRefs() {
    var kotlin: mutable.Set[String] = mutable.TreeSet[String]()

    def find(ty: TypeRef): Unit = {
      find(ty.resolved)
    }

    def find(tm: MExpr): Unit = {
      tm.args.foreach(find)
      find(tm.base)
    }

    def find(m: Meta): Unit = for (r <- marshal.references(m)) r match {
      case ImportRef(arg) => kotlin.add(arg)
      case _ =>
    }
  }

  def writeKotlinFile(ident: String, origin: String, refs: Iterable[String], f: IndentWriter => Unit) {
    createFile(commonMainOut, idKotlin.ty(ident) + ".kt", (w: IndentWriter) => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      w.wl
      spec.kotlinPackage.foreach(s => w.wl(s"package $s").wl)
      if (refs.nonEmpty) {
        refs.foreach(s => w.wl(s"import $s"))
        w.wl
      }
      f(w)
    })
  }

  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: ast.Enum): Unit = {
    val refs = new KotlinRefs()

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      w.w("enum class " + idKotlin.ty(ident.name)).braced {
        for (o <- e.options) {
          w.wl(idKotlin.enum(o.ident) + ",")
        }
      }
    })
  }

  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: Record): Unit = {
    val refs = new KotlinRefs()
    r.fields.foreach(f => refs.find(f.ty))

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      w.wl("data class " + idKotlin.ty(ident.name) + "(")
      w.increase()
      // Field definitions.
      for (f <- r.fields) {
        w.wl(s"val ${idKotlin.field(f.ident)}: ${marshal.fieldType(f.ty)},")
      }
      w.decrease()
      w.wl(")")
    })
  }

  override def generateInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface): Unit = {
    val refs = new KotlinRefs()

    i.methods.map(m => {
      m.params.map(p => refs.find(p.ty))
      m.ret.foreach(refs.find)
    })

    i.consts.map(c => {
      refs.find(c.ty)
    })

    writeKotlinFile(ident.name, origin, refs.kotlin, w => {
      w.w("interface " + idKotlin.ty(ident.name)).braced {
        for (m <- i.methods) {
          val params = m.params.map(p => s"${idKotlin.local(p.ident)}: ${marshal.paramType(p.ty)}")
          w.wl(s"fun ${idKotlin.method(m.ident)}" + params.mkString("(", ", ", ")") + ": " + marshal.returnType(m.ret) )
        }
      }
    })
  }
}
